/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.6.8, Date: 13-Oct-2015.
 * This file has been generated from 25.331V10.12.0(2013-06) ASN
 * $Header: //components/rel/wcdma.mpss/8.4.0/rrc/inc/rrcasn1Enc.h#2 $ $DateTime: 2020/01/24 03:56:36 $ $Author: pwbldsvc $
 */
#ifndef RRCASN1ENC_H
#define RRCASN1ENC_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rrcasn1.h"
#include "rtpersrc/asn1per.h"

EXTERN int asn1PE_rrc_UL_DCCH_MessageType_ext (OSCTXT* pctxt, rrc_UL_DCCH_MessageType_ext* pvalue);

EXTERN int asn1PE_rrc_UL_DCCH_MessageType (OSCTXT* pctxt, rrc_UL_DCCH_MessageType* pvalue);

EXTERN int asn1PE_rrc_UL_DCCH_Message (OSCTXT* pctxt, rrc_UL_DCCH_Message* pvalue);

EXTERN int asn1PE_rrc_UL_CCCH_MessageType (OSCTXT* pctxt, rrc_UL_CCCH_MessageType* pvalue);

EXTERN int asn1PE_rrc_UL_CCCH_Message (OSCTXT* pctxt, rrc_UL_CCCH_Message* pvalue);

#ifdef __cplusplus
}
#endif

#endif
