/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.6.8, Date: 13-Oct-2015.
 * This file has been generated from 25.331V10.12.0(2013-06) ASN
 * $Header: //components/rel/wcdma.mpss/8.4.0/rrc/inc/rrcasn1Dec.h#2 $ $DateTime: 2020/01/24 03:56:36 $ $Author: pwbldsvc $
 */
#ifndef RRCASN1DEC_H
#define RRCASN1DEC_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "rrcasn1.h"
#include "rtpersrc/asn1per.h"

EXTERN int asn1PD_rrc_DL_DCCH_MessageType (OSCTXT* pctxt, rrc_DL_DCCH_MessageType* pvalue);

EXTERN int asn1PD_rrc_DL_DCCH_Message (OSCTXT* pctxt, rrc_DL_DCCH_Message* pvalue);

EXTERN int asn1PD_rrc_DL_CCCH_MessageType (OSCTXT* pctxt, rrc_DL_CCCH_MessageType* pvalue);

EXTERN int asn1PD_rrc_DL_CCCH_Message (OSCTXT* pctxt, rrc_DL_CCCH_Message* pvalue);

EXTERN int asn1PD_rrc_PCCH_MessageType (OSCTXT* pctxt, rrc_PCCH_MessageType* pvalue);

EXTERN int asn1PD_rrc_PCCH_Message (OSCTXT* pctxt, rrc_PCCH_Message* pvalue);

EXTERN int asn1PD_rrc_BCCH_FACH_MessageType (OSCTXT* pctxt, rrc_BCCH_FACH_MessageType* pvalue);

EXTERN int asn1PD_rrc_BCCH_FACH_Message (OSCTXT* pctxt, rrc_BCCH_FACH_Message* pvalue);

EXTERN int asn1PD_rrc_BCCH_BCH_Message (OSCTXT* pctxt, rrc_BCCH_BCH_Message* pvalue);

#ifdef __cplusplus
}
#endif

#endif
