#ifndef MSG_QSR_H
#define MSG_QSR_H
/*
 QSHRINK SUPPORTED = 40
*/

/* 
   Qshrink parser will search for the above line in this file and only then 
   it will modify source code based on the new parameter processing feature
   Otherwise it will modify source code as before. 
*/

/*!
  @ingroup diag_message_service
  @file msg_qsr.h 
  @brief
  All the declarations and definitions necessary to support the optimized f3 
  messages (a.k.a. QSHRINK messages) for errors and debugging.

  This file includes support for the extended capabilities as well as the 
  legacy messaging scheme.
  @note
  Please do NOT include this file directly. Clients 
  need to include msg.h to use Diagnostic Debug Message Service.
  
  @par 
  The Qshrink message service is designed to optimize memory use in debug 
  messages. Qshrink extended messages do not contain format strings and file 
  names as compared to extended debug messages (Command_code 121/0x79). The 
  debug strings associated with debug messages are hashed and stored locally 
  to reduce their memory foot-print. The hash value is sent as a message field 
  to the tool to print the actual debug string.
  The packet with CMD_CODE 146/0x92 is generated by the DMSS with no 
  associated request packet. The service is configured using the Extended 
  Configuration Request/Response message (command 125)
*/

/*
Copyright (c) 2010-2016,2018-2019 by QUALCOMM Technologies, Incorporated.
All Rights Reserved.
Qualcomm Confidential and Proprietary
*/

/*===========================================================================
                        EDIT HISTORY FOR FILE

$Header: //components/rel/core.mpss/10.0/api/services/msg_qsr.h#2 $

when       who     what, where, why
--------   ---   ----------------------------------------------------------
02/05/18   sa      Removed Unused APIs.
09/29/16   ph      Diag and ULOG integration.
07/08/16   gn      Unused Public API removal
06/16/16   gn      Changes for MultiSim Optimized API FR
10/29/15   nk      Changes to support for Qshrink 4.0 in MSG_ERR_LOG_EXT macro
09/30/15   is      Add workaround for shadow packet DV issue on Hexagon compiler
04/11/16   ph      Added support for QShrink 4.0
01/12/15   sr      Added support for DLL clients
09/11/14   is      Push Qshrink variables to DATA section explicitly
08/08/14   is      Route MSG macros to Qshrink 2 functions for user pd for bringup
02/13/14   is      Changing section from ".rodata.*" to ".qsr.rodata.*" for the DIAG message structures
12/27/13   sa      Updated the names of the QSR strings section in the memory
10/14/13   sr      Added support for extended event, log and F3 pkts
08/02/13   sr      Added support for extended message APIs
03/28/13   rh      Support for QShrink 3.0
07/20/11   is      Support for QShrink 2.0
03/31/11   hm      Changes in QSR_MSG_XXX macros to support Parameter Processing
06/10/10   mad     Doxygenated.
06/08/10   vs      Fixed compile error in QSR_MSG_ERR_LOG
05/20/10   vs      Changed QSR_ERR_LOG to QSR_MSG_ERR_LOG
04/08/10   vs      Changes to include memory optimizations for ERR macro
04/01/10   sg      Removed the undefines for QSR_MSG_LOW,MEDIUM,HIGH,ERROR,
                   FATAL
10/11/09   vg      8200 Warning Clean Up
20/05/09   ps      Created new file for qsr feature based on msg.h

===========================================================================*/

/*===========================================================================

                     INCLUDE FILES FOR MODULE

===========================================================================*/
#include "comdef.h"		       /* Definitions for byte, word, etc. */
#include "msg_pkt_defs.h"
#include "msgcfg.h" 
#include "diagbuffer_defs.h"



#define MAX_MSG_V4_SSID_TABLE_ENTRY 4000         /*Maxinum number of entries in SSID table*/
#define MAX_MSG_V4_SSID_AAM_TABLE_ENTRY 4000     /*Maxinum number of entries in aligned address mapping table*/
#define MAX_MSG_V4_SSID_UAM_TABLE_ENTRY 8192      /*Maxinum number of entries in unaligned address mapping table*/	    
#define MAX_MSG_V4_DBASE_NAME_SIZE 50

/*---------------------------------------------------------------------------
  The extended message packet is defined to be processed as efficiently as
  possible in the caller's context.  Therefore, the packet is divided into
  logical blocks that are aligned w/out declaring the structure as PACK.
  
  A header, static constant block, and argument list are defined to minimize
  the work done by the caller's task.
   
   1. Header
   2. Constant variable length data (format string and filename string, etc).
   3. Arguments ("Variable" variable-length data)
   
  The data is delivered in this order in the packet to simplify the runtime 
  processing of each message.  All constant data is handled in DIAG task 
  context, leaving the caller's task to only process variable data at runtime.
   
  The phone will never process the constant data directly, except to copy 
  format and filename strings. 
---------------------------------------------------------------------------*/

#ifdef __cplusplus
  #define SECT_EXT __FILE__
#else
  #define SECT_EXT
#endif

#ifdef __HEXMSGABI_2_SUPPORTED__
  #define ERR_HEXMSGABI_ATTRIBUTE __attribute__((hexmsgabi))
#else
  #define ERR_HEXMSGABI_ATTRIBUTE
#endif

#define _MSG_STR(A) #A
#define MSG_STR(A) _MSG_STR(A)

/*!
  QShrink attribute flag to move QSR strings into QSR_STR region of scatter load file
*/
#define QSR_ATTR __attribute__((section ("QSR_STR.fmt.rodata." SECT_EXT),aligned (4))) 
#define QSR_MSG_ATTR __attribute__((section (".qsr.rodata.QSR_F3_MSG." SECT_EXT)))
#define QSR_MSG_LEGACY_ATTR __attribute__((section (".qsr.rodata.QSR_LEGACY." SECT_EXT),used))
#define QSR_MSG_V3_ATTR __attribute__((section (".sdata.qsr"),aligned (4)))
#define QSR_MSG_V4_ATTR_DATA __attribute__((section (".data.qsr"),aligned (4)))
#define QSR_4_0_ATTR __attribute__((section ("QSR_4_0_STR.fmt.rodata." SECT_EXT),aligned (4),used)) 





/*!
@ingroup diag_message_service
  All constant information stored for an optimized debug message.
   
  The values for the fields of this structure are known at compile time. 
  So this is to be defined as a "static " in the MACRO, so it ends up
  being defined and initialized at compile time for each and every message 
  in the software. This minimizes the amount of work to do during run time.
  
  So this structure is to be used in the "caller's" context. "Caller" is the
  client of the Message Services.
*/
typedef struct
{
  msg_desc_type desc;	/*!< contains mask, line number and subsystem-id. defined in msg_pkt_defs.h */
  uint32 msg_hash;		 /*!< message hash value */
}
msg_qsr_const_type;

/*!
@ingroup diag_message_service
  All constant information stored for an optimized debug message, for use by 
  error service.
   
  The values for the fields of this structure are known at compile time. 
  So this is to be defined as a "static " in the MACRO, so it ends up
  being defined and initialized at compile time for each and every message 
  in the software. This minimizes the amount of work to do during run time.
  
  So this structure is to be used in the "caller's" context. "Caller" is the
  client of the Message Services.
*/ 
typedef struct
{
  msg_qsr_const_type qsr_const_blk; /*!< contains mask, line number, subsystem-id and hash value. */
  const char *fname;                /*!<file name */
} err_msg_qsr_const_type;

/*!
Bit flag for qsr_flag to check if msg contains a QSR hash.
*/
#define QSR_BITFLAG_UNHASHED (0x00000000)
#define QSR_BITFLAG_IS_HASH (0x00000001)
#define QSR_BITFLAG_IS_V3 (0x00000002)
#define QSR_BITFLAG_IS_V4 (0x10000000)

/*!
@ingroup diag_message_service
	This is the structure that is stored by the caller's task in qsr_msg_send().
	The DIAG task will expand the constant data into the final packet before
	sending to the external device.
*/
typedef struct
{
  msg_hdr_type hdr; /*!< Header, defined in msg_pkt_defs.h */
  const msg_qsr_const_type* qsr_const_data_ptr; /*!< contains mask, line number, subsystem-id and hash value. */
  uint32 qsr_flag; /*!< Bit 0: True, if hash value is passed, False, if string pointer is passed */
  uint32 args[1]; /*!< starting address of arguments */
}
msg_qsr_store_type;
  

/* QShrink 3.0 MACROS */

/*!
@ingroup diag_message_service
  All constant information stored for an optimized debug message.
   
  The values for the fields of this structure are known at compile time. 
  So this is to be defined as a "static " in the MACRO, so it ends up
  being defined and initialized at compile time for each and every message 
  in the software. This minimizes the amount of work to do during run time.
  
  So this structure is to be used in the "caller's" context. "Caller" is the
  client of the Message Services.
*/
typedef struct
{
  uint16 ssid_index; /* Index to msg_v3_ssid_table_type */
  uint16 line;  /* Line number of the F3 message*/
  uint32 msg;		  /*!will contain Message hash , if  hashed */
                /*  (char*)< filename + format string - if not hashed */
}
msg_v3_const_hash;

/* This struct exists only for initialization purposes.  It will be replaced
   with a msg_v3_const_hash by the QShrink 3.0 tool. */
typedef struct
{
  uint32 ss_mask;
  const char *msg;
}
msg_v3_const_string;

/* This will statically initialize to the first entry. */
typedef union
{
  msg_v3_const_string msg_const_string;
  msg_v3_const_hash qsr_const_blk;
}
msg_v3_const_type;

/*!
@ingroup diag_message_service
 This union points to either a v2-style descrptor or a v3-style descriptor.
 You can find out which one it is from the accompanying field:
 msg_qsr_flag_enum qsr_flag;
*/
typedef union
{
  const msg_qsr_const_type* msg_desc;
  const msg_v3_const_hash* v3_index;
}
msg_qsr_const_ptr;

/* The structure will map to msg_qsr_const_type, after QShrink tool runs */

/*!
@ingroup diag_message_service
	This is the structure that is stored by the caller's task in qsr_msg_send().
	The DIAG task will expand the constant data into the final packet before
	sending to the external device.
*/
typedef struct
{
  msg_hdr_type hdr; /*!< Header, defined in msg_pkt_defs.h */
  msg_qsr_const_ptr qsr_const_data_ptr; /*!< contains mask, line number, subsystem-id and hash value. */
  uint32 qsr_flag; /*!< Bit 0: True, if hash value is passed, False, if string pointer is passed */
  uint32 args[1]; /*!< starting address of arguments */
}
msg_v3_store_type;

typedef struct
{
  uint8 cmd_code; /*!< cmd code for the extended pkts */
  uint8 version; /*!< version of the pkt; currently we support 1 */
  uint16 proc_id;/*!< Processor ID in which this F3 is being generated */
  uint32 id; /*!< Generic field for clients to use as needed */
  msg_v3_store_type msg;
}
msg_v3_multi_client_store_type;

/* QShrink 4.0 MACROS */
 /* This will statically initialize to the first entry. */
 typedef struct
 {
   msg_v3_const_string msg_const_string;
 }
 msg_v4_const_type;

typedef PACK(struct) {
  msg_hdr_type hdr; /*!< Header, defined in msg_pkt_defs.h */
  uint32 qsr_hash; /*!< Hash -structure pointer*/
  uint8 dbase_guid[2];    /*!< Last two bytes of  */
  uint32 args[1]; /*!< starting address of arguments */
 }msg_v4_store_type;

typedef struct
{
  uint8 cmd_code; /*!< cmd code for the extended pkts */
  uint8 version; /*!< version of the pkt; currently we support 1 */
  uint16 proc_id;/*!< Processor ID in which this F3 is being generated */
  uint32 id; /*!< Generic field for clients to use as needed */
  msg_v4_store_type msg;
}
msg_v4_multi_client_store_type;
 /* QShrink 4.0 MACROS */

/* DO NOT COMMENT BELOW section
     If QSHrink 4.0 is not preferred for some targets, QShrink 3.0 will be used */
//#if 0

 /*!
   Constructs a msg_v3_const_type from the SSID, mask and format-string
 */
  #define XX_MSG_V3_CONST(xx_ss_id, xx_ss_mask, xx_fmt) \
    static const char QSR_string_ptr[] QSR_ATTR  \
      = MSG_STR(xx_ss_id) ":" MSG_STR(__LINE__)":" msg_file ":" xx_fmt ; \
    static const msg_v3_const_type xx_msg_v3_const QSR_MSG_ATTR = \
      { { xx_ss_mask, (char*)&QSR_string_ptr} }
    

/* QShrink 4.0 MACROS */

/*!
  Constructs a msg_v4_const_type from the SSID, mask and format-string
*/
 #define XX_MSG_V4_CONST(xx_ss_id, xx_ss_mask, xx_fmt) \
   static const char QSR_string_ptr[] QSR_4_0_ATTR  \
     = MSG_STR(xx_ss_id) ":" MSG_STR(__LINE__)":" msg_file ":" xx_fmt ; \
   static const msg_v4_const_type xx_msg_v4_const \
     __attribute__((section ("QSR_4_0_MSG.fmt.rodata." MSG_STR(xx_ss_id)"." MSG_STR(xx_ss_mask)"." SECT_EXT),used))= \
     { { xx_ss_mask, (char*)&QSR_string_ptr} }
   


/*!
@ingroup diag_message_service
@name QSR MSG 2.0 macros
These are the optimized message macros that support messages with 0-9 integer 
arguments.Build-time mask-check is done against @a xx_ss_mask before macro expansion.
Defining the macro in a do{}while() limits the scope and guarantees the 
uniqueness of the variable name defined by the XX_QSR_MSG_CONST macros.
@a xx_ss_id specifies the Sub-system ID of the client, @a xx_fmt is the 
format-string that gets replaced with the hash value and @a xx_arg1 etc 
specify the integer arguments.
*/
/*@{*/ /*Start group QSR MSG 2.0 macros */


/* QSHRINK 3.0 - All QSR_MSG_MACROS Will be deprecated START ---------------------*/


typedef struct
{
  msg_desc_type desc; /*!< ss_mask, line, ss_id */
  const char * msg;   /*!< filename + format string - This field may be changed to a hash value when the 
                           QSHRINK20 script runs on the linker output */
}
msg_v2_const_type;

#ifdef __cplusplus
  #define SECT_EXT __FILE__
#else
  #define SECT_EXT
#endif


  /*!
    Constructs a msg_v2_const_type from the SSID, mask and format-string
  */
  #define XX_MSG_V2_CONST(xx_ss_id, xx_ss_mask, xx_fmt) \
    static const char QSR_string_ptr[] QSR_ATTR  \
      = msg_file ":" xx_fmt ; \
    static const msg_v2_const_type xx_msg_v2_const = { \
      {__LINE__, (xx_ss_id), (xx_ss_mask)}, \
          (char*)&QSR_string_ptr }
    

/* QSHRINK 30 - All QSR_MSG_MACROS Will be deprecated END---------------------*/


/*!
@ingroup diag_message_service
@name XX_QSR_MSG_CONST macros
The purpose of these macros is to define the constant part of the message
that can be initialized at compile time and stored in ROM. msg_qsr_const_type 
is constructed from the Subsystem-ID (@a xx_ss_id), Mask (@a xx_ss_mask) 
and hash value (@a hash).The "static" limits the scope to the file the 
macro is called from.
@note 
Please do not call these directly, these are to be used internally,
by the different externalised MSG_ macros, which in-turn get text-substituted 
with QSR_MSG_ macros and the corresponding hash.
@note
XX_QSR_MSG_CONST_FMT_VAR can be removed. (!!!!!!!)
*/
/*@{*/ /* start group XX_QSR_MSG_CONST macros */         


/* QSHRINK 3.0 - All QSR_MSG_MACROS Will be deprecated START ---------------------*/



/* QSHRINK 3.0 - All QSR_MSG_MACROS Will be deprecated END---------------------*/

/* -------------------------------------------------------------------------
   Function Definitions
   ------------------------------------------------------------------------- */

#ifdef __cplusplus
extern "C"
{
#endif

/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with no parameters. 

   @warning
   Do not call directly; use macro MSG()

   @param[in] *xx_msg_v2_const static constant constructed using 
   the different XX_MSG_V2_CONST macros

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v2_send_1, msg_v2_send_2, msg_v2_send_3, msg_v2_send_var
*/
  void msg_v2_send ( const msg_v2_const_type * xx_msg_const_ptr);

  /*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with no parameters
   specific for DLL clients. 

   @warning
   Do not call directly; use macro MSG()

   @param[in] *xx_msg_v2_const static constant constructed using 
   the different XX_MSG_V2_CONST macros

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v2_send_1_dll, msg_v2_send_2_dll, msg_v2_send_3_dll, msg_v2_send_var_dll
*/
  void msg_v2_send_dll ( const msg_v2_const_type * xx_msg_const_ptr);
  
/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with no parameters. 

   @warning
   Do not call directly; use macro MSG()

   @param[in] *xx_msg_v3_const static constant constructed using 
   the different XX_MSG_V3_CONST macros

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v3_send_1, msg_v3_send_2, msg_v3_send_3, msg_v3_send_var
*/
  void msg_v3_send ( const msg_v3_const_type * xx_msg_const_ptr) ERR_HEXMSGABI_ATTRIBUTE;

/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with no parameters. 

   @warning
   Do not call directly; use macro MSG()

   @param[in] *xx_msg_v4 const static constant constructed using 
   the different XX_MSG_V4_CONST macros

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v4_send_1, msg_v4_send_2, msg_v4_send_3, msg_v4_send_var
*/
  void msg_v4_send (const msg_v4_const_type * xx_msg_const_ptr)ERR_HEXMSGABI_ATTRIBUTE;


/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with no parameters. 

   @warning
   Do not call directly; use macro MSG_EXT()

   @param[in] *xx_msg_v3_const static constant constructed using 
   the different XX_MSG_V3_CONST macros
   @param[in] version                  Specifies the version - currently, there are two versions 
                                       0 - same as msg_v3_send() (for backwards compatibility)
                                       1 - The outgoing msg header will have the support to
                                           include ID field to differentiate messages
                                           coming from different instances of the processor.
   
   @param[in] *parameter               Based on the version passed in, this pointer is interpreted
                                       as follows-
                                       version       pointer
                                       0             NULL
                                       1             uint32 * . The uint32 value this pointer points to,
                                                     is the ID of the instance generating the msg.

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v3_send_1, msg_v3_send_2, msg_v3_send_3, msg_v3_send_var
*/
  void msg_v3_send_ext ( const msg_v3_const_type * xx_msg_const_ptr, uint32 version, void* parameter);
/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with no parameters. 

   @warning
   Do not call directly; use macro MSG_EXT()

   @param[in] *xx_msg_v4_const static constant constructed using 
   the different XX_MSG_V4_CONST macros
   @param[in] version                  Specifies the version - currently, there are two versions 
                                       0 - same as msg_v4_send() (for backwards compatibility)
                                       1 - The outgoing msg header will have the support to
                                           include ID field to differentiate messages
                                           coming from different instances of the processor.

   @param[in] *parameter               Based on the version passed in, this pointer is interpreted
                                       as follows-
                                       version       pointer
                                       0             NULL
                                       1             uint32 * . The uint32 value this pointer points to,
                                                     is the ID of the instance generating the msg.

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v4_send_1_ext, msg_v4_send_2_ext, msg_v4_send_3_ext, msg_v4_send_var_ext
*/

  void msg_v4_send_ext ( const msg_v4_const_type * xx_msg_const_ptr, uint32 version, void* parameter);
/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with no parameters. 
   This function is a shim API which calls msg_v4_send_ext_v1.  

   @warning
   Do not call directly; use macro MSG_EXT_V1()

   @param[in] *xx_msg_v4_const static constant constructed using 
   the different XX_MSG_V4_CONST macros
   
   @param[in] parameter                The version is hardcoded to 1
									   This uint32 value is the ID of the instance generating the msg.

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v4_send_1_ext_v1, msg_v4_send_2_ext_v1, msg_v4_send_3_ext_v1, msg_v4_send_4_ext_v1 ...
*/  
  void msg_v4_send_ext_v1 (const msg_v4_const_type * xx_msg_const_ptr, uint32 parameter); 				

/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 1 parameter. 

   @warning
   Do not call directly; use macro DIAGBUFFER_MSG_EXT()

   @param[in] *xx_msg_v4_const static constant constructed using
   the different XX_MSG_V4_CONST macros
   @param[in] xx_handle                Specifies the diagbuffer handle.
   @param[in] version                  Specifies the version - currently, there are two versions
                                       0 - Legacy/Normal messages (for backwards compatibility)
                                       1 - The outgoing msg header will have the support to
                                           include ID field to differentiate messages
                                           coming from different instances of the processor.

   @param[in] *parameter               Based on the version passed in, this pointer is interpreted
                                       as follows-
                                       version       pointer
                                       0             NULL
                                       1             uint32 * . The uint32 value this pointer points to,
                                                     is the ID of the instance generating the msg.

   @param[in]  xx_arg1           integer parameter 1 for the optimized message

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v4_send_ext, msg_v4_send_2_ext, msg_v4_send_3_ext, msg_v4_send_var_ext
*/
  void _msg_v4_diagbuffer_send_ext(diagbuffer_handle xx_handle, const msg_v4_const_type * xx_msg_const_ptr, uint32 version, void* parameter);
  
/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 1 parameter. 

   @warning
   Do not call directly; use macro MSG_1()

   @param[in] *xx_msg_v2_const  static constant constructed using 
   the different XX_MSG_V2_CONST macros
   @param[in]  xx_arg1           integer parameter 1 for the optimized message

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v2_send, msg_v2_send_2, msg_v2_send_3, msg_v2_send_var
*/
  void msg_v2_send_1 (const msg_v2_const_type * xx_msg_const_ptr, uint32 xx_arg1);

/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 1 parameter
   specific for DLL clients. 

   @warning
   Do not call directly; use macro MSG()

   @param[in] *xx_msg_v2_const static constant constructed using 
   the different XX_MSG_V2_CONST macros

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v2_send_dll, msg_v2_send_2_dll, msg_v2_send_3_dll, msg_v2_send_var_dll
*/
  void msg_v2_send_1_dll (const msg_v2_const_type * xx_msg_const_ptr, uint32 xx_arg1);
   
/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 1 parameter. 

   @warning
   Do not call directly; use macro MSG_1()

   @param[in] *xx_msg_v3_const  static constant constructed using 
   the different XX_MSG_V3_CONST macros
   @param[in]  xx_arg1           integer parameter 1 for the optimized message

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v3_send, msg_v3_send_2, msg_v3_send_3, msg_v3_send_var
*/
  void msg_v3_send_1 (const msg_v3_const_type * xx_msg_const_ptr, uint32 xx_arg1) ERR_HEXMSGABI_ATTRIBUTE;

/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 1 parameter. 

   @warning
   Do not call directly; use macro MSG_1()

   @param[in] *xx_msg_v4_const  static constant constructed using 
   the different XX_MSG_V4_CONST macros
   @param[in]  xx_arg1           integer parameter 1 for the optimized message

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v4_send, msg_v4_send_2, msg_v4_send_3, msg_v4_send_var
*/
  void msg_v4_send_1 (const msg_v4_const_type * xx_msg_const_ptr, uint32 xx_arg1)ERR_HEXMSGABI_ATTRIBUTE;
/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 1 parameter. 

   @warning
   Do not call directly; use macro MSG_1_EXT()

   @param[in] *xx_msg_v3_const  static constant constructed using 
   the different XX_MSG_V3_CONST macros
   @param[in] version                  Specifies the version - currently, there are two versions 
                                       0 - same as msg_v3_send_1() (for backwards compatibility)
                                       1 - The outgoing msg header will have the support to
                                           include ID field to differentiate messages
                                           coming from different instances of the processor.
   
   @param[in] *parameter               Based on the version passed in, this pointer is interpreted
                                       as follows-
                                       version       pointer
                                       0             NULL
                                       1             uint32 * . The uint32 value this pointer points to,
                                                     is the ID of the instance generating the msg.

   @param[in]  xx_arg1           integer parameter 1 for the optimized message

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v3_send, msg_v3_send_2, msg_v3_send_3, msg_v3_send_var
*/
  void msg_v3_send_1_ext (const msg_v3_const_type * xx_msg_const_ptr, uint32 version, void* parameter, uint32 xx_arg1);
/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 1 parameter. 

   @warning
   Do not call directly; use macro MSG_1_EXT()

   @param[in] *xx_msg_v4_const  static constant constructed using 
   the different XX_MSG_V4_CONST macros
   @param[in] version                  Specifies the version - currently, there are two versions 
                                       0 - same as msg_v3_send_1() (for backwards compatibility)
                                       1 - The outgoing msg header will have the support to
                                           include ID field to differentiate messages
                                           coming from different instances of the processor.
   
   @param[in] *parameter               Based on the version passed in, this pointer is interpreted
                                       as follows-
                                       version       pointer
                                       0             NULL
                                       1             uint32 * . The uint32 value this pointer points to,
                                                     is the ID of the instance generating the msg.

   @param[in]  xx_arg1           integer parameter 1 for the optimized message

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v4_send_ext, msg_v4_send_2_ext, msg_v4_send_3_ext, msg_v4_send_var_ext
*/
  void msg_v4_send_1_ext (const msg_v4_const_type * xx_msg_const_ptr, uint32 version, void* parameter, uint32 xx_arg1);
/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 1 parameter. 

   @warning
   Do not call directly; use macro DIAGBUFFER_MSG_1_EXT()

   @param[in] *xx_msg_v4_const  static constant constructed using
   the different XX_MSG_V4_CONST macros
   @param[in] xx_handle                Specifies the diagbuffer handle.
   @param[in] version                  Specifies the version - currently, there are two versions
                                       0 - same as msg_v3_send_1() (for backwards compatibility)
                                       1 - The outgoing msg header will have the support to
                                           include ID field to differentiate messages
                                           coming from different instances of the processor.

   @param[in] *parameter               Based on the version passed in, this pointer is interpreted
                                       as follows-
                                       version       pointer
                                       0             NULL
                                       1             uint32 * . The uint32 value this pointer points to,
                                                     is the ID of the instance generating the msg.

   @param[in]  xx_arg1           integer parameter 1 for the optimized message

   @dependencies
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v4_send_ext, msg_v4_send_2_ext, msg_v4_send_3_ext, msg_v4_send_var_ext
*/
  void _msg_v4_diagbuffer_send_1_ext (diagbuffer_handle xx_handle, const msg_v4_const_type * xx_msg_const_ptr, uint32 version, void* parameter, uint32 xx_arg1);
/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 1 parameter.
   This function is a shim API which calls msg_v4_send_1_ext_v1.  

   @warning
   Do not call directly; use macro MSG_1_EXT_V1()

   @param[in] *xx_msg_v4_const static constant constructed using 
   the different XX_MSG_V4_CONST macros
   
   @param[in] parameter                The version is hardcoded to 1
									   This uint32 value is the ID of the instance generating the msg.

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v4_send_ext_v1, msg_v4_send_2_ext_v1, msg_v4_send_3_ext_v1, msg_v4_send_4_ext_v1 ...
*/    
  void msg_v4_send_1_ext_v1 (const msg_v4_const_type * xx_msg_const_ptr, uint32 parameter, uint32 xx_arg1);

/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 2 parameters. 

   @warning
   Do not call directly; use macro MSG_2()

   @param[in] *xx_msg_v2_const  static constant constructed using 
   the different XX_MSG_V2_CONST macros
   @param[in]  xx_arg1           integer parameter 1 for the optimized message
   @param[in]  xx_arg2           integer parameter 2 for the optimized message

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v2_send, msg_v2_send_1, msg_v2_send_3, msg_v2_send_var
*/
  void msg_v2_send_2 ( const msg_v2_const_type * xx_msg_const_ptr,uint32 xx_arg1,
    uint32 xx_arg2);

	/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 2 parameters
   specific for DLL clients. 

   @warning
   Do not call directly; use macro MSG_2()

   @param[in] *xx_msg_v2_const  static constant constructed using 
   the different XX_MSG_V2_CONST macros
   @param[in]  xx_arg1           integer parameter 1 for the optimized message
   @param[in]  xx_arg2           integer parameter 2 for the optimized message

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v2_send_dll, msg_v2_send_1_dll, msg_v2_send_3_dll, msg_v2_send_var_dll
*/
  void msg_v2_send_2_dll ( const msg_v2_const_type * xx_msg_const_ptr,uint32 xx_arg1,
    uint32 xx_arg2);

/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 2 parameters. 

   @warning
   Do not call directly; use macro MSG_2()

   @param[in] *xx_msg_v3_const  static constant constructed using 
   the different XX_MSG_V3_CONST macros
   @param[in]  xx_arg1           integer parameter 1 for the optimized message
   @param[in]  xx_arg2           integer parameter 2 for the optimized message

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v3_send, msg_v3_send_1, msg_v3_send_3, msg_v3_send_var
*/
  void msg_v3_send_2 ( const msg_v3_const_type * xx_msg_const_ptr,uint32 xx_arg1,
    uint32 xx_arg2) ERR_HEXMSGABI_ATTRIBUTE;

/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 2 parameters. 

   @warning
   Do not call directly; use macro MSG_2()

   @param[in] *xx_msg_v4_const  static constant constructed using 
   the different XX_MSG_V4_CONST macros
   @param[in]  xx_arg1           integer parameter 1 for the optimized message
   @param[in]  xx_arg2           integer parameter 2 for the optimized message

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v4_send, msg_v4_send_1, msg_v4_send_3, msg_v4_send_var
*/
  void msg_v4_send_2 (const msg_v4_const_type * xx_msg_const_ptr, uint32 xx_arg1,uint32 xx_arg2)ERR_HEXMSGABI_ATTRIBUTE;
/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 2 parameters. 

   @warning
   Do not call directly; use macro MSG_2()

   @param[in] *xx_msg_v3_const  static constant constructed using 
   the different XX_MSG_V3_CONST macros
   @param[in] version                  Specifies the version - currently, there are two versions 
                                       0 - same as msg_v3_send_2() (for backwards compatibility)
                                       1 - The outgoing msg header will have the support to
                                           include ID field to differentiate messages
                                           coming from different instances of the processor.
   
   @param[in] *parameter                Based on the version passed in, this pointer is interpreted
                                       as follows-
                                       version       pointer
                                       0             NULL
                                       1             uint32 * . The uint32 value this pointer points to,
                                                     is the ID of the instance generating the msg.

   @param[in]  xx_arg1          integer parameter 1 for the optimized message
   @param[in]  xx_arg2          integer parameter 2 for the optimized message

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v3_send, msg_v3_send_1, msg_v3_send_3, msg_v3_send_var
*/
  void msg_v3_send_2_ext ( const msg_v3_const_type * xx_msg_const_ptr, uint32 version, void* parameter,
                           uint32 xx_arg1, uint32 xx_arg2);
/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 2 parameters. 

   @warning
   Do not call directly; use macro MSG_2()

   @param[in] *xx_msg_v4_const  static constant constructed using 
   the different XX_MSG_V4_CONST macros
   @param[in] version                  Specifies the version - currently, there are two versions 
                                       0 - same as msg_v4_send_2() (for backwards compatibility)
                                       1 - The outgoing msg header will have the support to
                                           include ID field to differentiate messages
                                           coming from different instances of the processor.
   
   @param[in] *parameter                Based on the version passed in, this pointer is interpreted
                                       as follows-
                                       version       pointer
                                       0             NULL
                                       1             uint32 * . The uint32 value this pointer points to,
                                                     is the ID of the instance generating the msg.

   @param[in]  xx_arg1          integer parameter 1 for the optimized message
   @param[in]  xx_arg2          integer parameter 2 for the optimized message

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v4_send_ext, msg_v4_send_1_ext, msg_v4_send_3_ext, msg_v4_send_var_ext
*/
  void msg_v4_send_2_ext ( const msg_v4_const_type * xx_msg_const_ptr, uint32 version, void* parameter,
                           uint32 xx_arg1, uint32 xx_arg2);
/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 2 parameters. 

   @warning
   Do not call directly; use macro DIAGBUFFER_MSG_2_EXT()

   @param[in] *xx_msg_v4_const  static constant constructed using
   the different XX_MSG_V4_CONST macros
   @param[in] xx_handle                Specifies the diagbuffer handle.
   @param[in] version                  Specifies the version - currently, there are two versions
                                       0 - same as msg_v4_send_2() (for backwards compatibility)
                                       1 - The outgoing msg header will have the support to
                                           include ID field to differentiate messages
                                           coming from different instances of the processor.

   @param[in] *parameter                Based on the version passed in, this pointer is interpreted
                                       as follows-
                                       version       pointer
                                       0             NULL
                                       1             uint32 * . The uint32 value this pointer points to,
                                                     is the ID of the instance generating the msg.

   @param[in]  xx_arg1          integer parameter 1 for the optimized message
   @param[in]  xx_arg2          integer parameter 2 for the optimized message

   @dependencies
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v4_send_ext, msg_v4_send_1_ext, msg_v4_send_3_ext, msg_v4_send_var_ext
*/

  void _msg_v4_diagbuffer_send_2_ext (diagbuffer_handle h,
                                   const msg_v4_const_type * xx_msg_const_ptr,
                                   uint32 version, void* parameter, uint32 xx_arg1, uint32 xx_arg2);

/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 2 parameters.
   This function is a shim API which calls msg_v4_send_2_ext_v1.  

   @warning
   Do not call directly; use macro MSG_2_EXT_V1()

   @param[in] *xx_msg_v4_const static constant constructed using 
   the different XX_MSG_V4_CONST macros
   
   @param[in] parameter                The version is hardcoded to 1
									   This uint32 value is the ID of the instance generating the msg.

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v4_send_ext_v1, msg_v4_send_1_ext_v1, msg_v4_send_3_ext_v1, msg_v4_send_4_ext_v1 ...
*/   
  void msg_v4_send_2_ext_v1 ( const msg_v4_const_type * xx_msg_const_ptr, uint32 parameter,
                           uint32 xx_arg1, uint32 xx_arg2);

/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 3 parameters. 

   @warning
   Do not call directly; use macro MSG_3()

   @param[in] *xx_msg_v2_const  static constant constructed using 
   the different XX_MSG_V2_CONST macros
   @param[in]  xx_arg1           integer parameter 1 for the optimized message
   @param[in]  xx_arg2           integer parameter 2 for the optimized message
   @param[in]  xx_arg3           integer parameter 3 for the optimized message

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v2_send, msg_v2_send_1, msg_v2_send_2, msg_v2_send_var
*/
  void msg_v2_send_3 ( const msg_v2_const_type * xx_msg_const_ptr, uint32 xx_arg1,
    uint32 xx_arg2, uint32 xx_arg3);

	/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 3 parameters
   specific for DLL clients. 

   @warning
   Do not call directly; use macro MSG_3()

   @param[in] *xx_msg_v2_const  static constant constructed using 
   the different XX_MSG_V2_CONST macros
   @param[in]  xx_arg1           integer parameter 1 for the optimized message
   @param[in]  xx_arg2           integer parameter 2 for the optimized message
   @param[in]  xx_arg3           integer parameter 3 for the optimized message

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v2_send_dll, msg_v2_send_1_dll, msg_v2_send_2_dll, msg_v2_send_var_dll
*/
  void msg_v2_send_3_dll ( const msg_v2_const_type * xx_msg_const_ptr, uint32 xx_arg1,
    uint32 xx_arg2, uint32 xx_arg3);

/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 3 parameters. 

   @warning
   Do not call directly; use macro MSG_3()

   @param[in] *xx_msg_v3_const  static constant constructed using 
   the different XX_MSG_V3_CONST macros
   @param[in]  xx_arg1           integer parameter 1 for the optimized message
   @param[in]  xx_arg2           integer parameter 2 for the optimized message
   @param[in]  xx_arg3           integer parameter 3 for the optimized message

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v3_send, msg_v3_send_1, msg_v3_send_2, msg_v3_send_var
*/
  void msg_v3_send_3 ( const msg_v3_const_type * xx_msg_const_ptr, uint32 xx_arg1,
    uint32 xx_arg2, uint32 xx_arg3) ERR_HEXMSGABI_ATTRIBUTE;

/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 3 parameters. 

   @warning
   Do not call directly; use macro MSG_3()

   @param[in] *xx_msg_v4_const  static constant constructed using 
   the different XX_MSG_V4_CONST macros
   @param[in]  xx_arg1           integer parameter 1 for the optimized message
   @param[in]  xx_arg2           integer parameter 2 for the optimized message
   @param[in]  xx_arg3           integer parameter 3 for the optimized message

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v4_send, msg_v4_send_1, msg_v4_send_2, msg_v4_send_var
*/
  void msg_v4_send_3 ( const msg_v4_const_type * xx_msg_const_ptr, uint32 xx_arg1,uint32 xx_arg2, uint32 xx_arg3)ERR_HEXMSGABI_ATTRIBUTE;
/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 3 parameters. 

   @warning
   Do not call directly; use macro MSG_3()

   @param[in] *xx_msg_v3_const  static constant constructed using 
   the different XX_MSG_V3_CONST macros
   @param[in] version                  Specifies the version - currently, there are two versions 
                                       0 - same as msg_v3_send_3() (for backwards compatibility)
                                       1 - The outgoing msg header will have the support to
                                           include ID field to differentiate messages
                                           coming from different instances of the processor.
   
   @param[in] *parameter                Based on the version passed in, this pointer is interpreted
                                       as follows-
                                       version       pointer
                                       0             NULL
                                       1             uint32 * . The uint32 value this pointer points to,
                                                     is the ID of the instance generating the msg.

   @param[in]  xx_arg1                integer parameter 1 for the optimized message
   @param[in]  xx_arg2                integer parameter 2 for the optimized message
   @param[in]  xx_arg3                integer parameter 3 for the optimized message

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v3_send, msg_v3_send_1, msg_v3_send_2, msg_v3_send_var
*/
  void msg_v3_send_3_ext ( const msg_v3_const_type * xx_msg_const_ptr, uint32 version, void* parameter,
                           uint32 xx_arg1, uint32 xx_arg2, uint32 xx_arg3);

/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 3 parameters. 

   @warning
   Do not call directly; use macro MSG_3()

   @param[in] *xx_msg_v4_const  static constant constructed using 
   the different XX_MSG_V4_CONST macros
   @param[in] version                  Specifies the version - currently, there are two versions 
                                       0 - same as msg_v4_send_3() (for backwards compatibility)
                                       1 - The outgoing msg header will have the support to
                                           include ID field to differentiate messages
                                           coming from different instances of the processor.
   
   @param[in] *parameter                Based on the version passed in, this pointer is interpreted
                                       as follows-
                                       version       pointer
                                       0             NULL
                                       1             uint32 * . The uint32 value this pointer points to,
                                                     is the ID of the instance generating the msg.

   @param[in]  xx_arg1                integer parameter 1 for the optimized message
   @param[in]  xx_arg2                integer parameter 2 for the optimized message
   @param[in]  xx_arg3                integer parameter 3 for the optimized message

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v4_send, msg_v4_send_1, msg_v4_send_2, msg_v4_send_var
*/
  void msg_v4_send_3_ext ( const msg_v4_const_type * xx_msg_const_ptr, uint32 version, void* parameter,
                           uint32 xx_arg1, uint32 xx_arg2, uint32 xx_arg3);
/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 3 parameters. 

   @warning
   Do not call directly; use macro DIAGBUFFER_MSG_3_EXT()

   @param[in] *xx_msg_v4_const  static constant constructed using
   the different XX_MSG_V4_CONST macros
   @param[in] xx_handle                Specifies the diagbuffer handle.
   @param[in] version                  Specifies the version - currently, there are two versions
                                       0 - same as msg_v4_send_3() (for backwards compatibility)
                                       1 - The outgoing msg header will have the support to
                                           include ID field to differentiate messages
                                           coming from different instances of the processor.

   @param[in] *parameter                Based on the version passed in, this pointer is interpreted
                                       as follows-
                                       version       pointer
                                       0             NULL
                                       1             uint32 * . The uint32 value this pointer points to,
                                                     is the ID of the instance generating the msg.

   @param[in]  xx_arg1                integer parameter 1 for the optimized message
   @param[in]  xx_arg2                integer parameter 2 for the optimized message
   @param[in]  xx_arg3                integer parameter 3 for the optimized message

   @dependencies
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v4_send, msg_v4_send_1, msg_v4_send_2, msg_v4_send_var
*/
  void _msg_v4_diagbuffer_send_3_ext (diagbuffer_handle h,
                                   const msg_v4_const_type * xx_msg_const_ptr,
                                   uint32 version, void* parameter, uint32 xx_arg1, uint32 xx_arg2, uint32 xx_arg3);
/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 3 parameters.
   This function is a shim API which calls msg_v4_send_3_ext_v1.  

   @warning
   Do not call directly; use macro MSG_3_EXT_V1()

   @param[in] *xx_msg_v4_const static constant constructed using 
   the different XX_MSG_V4_CONST macros
   
   @param[in] parameter                The version is hardcoded to 1
									   This uint32 value is the ID of the instance generating the msg.

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v4_send_ext_v1, msg_v4_send_1_ext_v1, msg_v4_send_2_ext_v1, msg_v4_send_4_ext_v1 ...
*/ 
  void msg_v4_send_3_ext_v1 ( const msg_v4_const_type * xx_msg_const_ptr, uint32 parameter,
                           uint32 xx_arg1, uint32 xx_arg2, uint32 xx_arg3);						   
  
/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with variable number 
   of (4 to 9) parameters.  

   @warning
   Do not call directly; use macros MSG_4(), ..MSG_9()

   @param[in] *xx_msg_v2_const            static constant constructed using 
   the different XX_MSG_V2_CONST macros
   @param[in] num_args                     number of parameters

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v2_send, msg_v2_send_1, msg_v2_send_2, msg_v2_send_3
*/
  void msg_v2_send_var ( const msg_v2_const_type * xx_msg_const_ptr, uint32 num_args, ...);

  /*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with variable number 
   of (4 to 9) parameters specific for DLL clients.  

   @warning
   Do not call directly; use macros MSG_4(), ..MSG_9()

   @param[in] *xx_msg_v2_const            static constant constructed using 
   the different XX_MSG_V2_CONST macros
   @param[in] num_args                     number of parameters

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v2_send_dll, msg_v2_send_1_dll, msg_v2_send_2_dll, msg_v2_send_3_dll
*/
  void msg_v2_send_var_dll ( const msg_v2_const_type * xx_msg_const_ptr, uint32 num_args, ...);

/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with variable number 
   of (4 to 9) parameters.  

   @warning
   Do not call directly; use macros MSG_4(), ..MSG_9()

   @param[in] *xx_msg_v3_const            static constant constructed using 
   the different XX_MSG_V3_CONST macros
   @param[in] num_args                     number of parameters

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v3_send, msg_v3_send_1, msg_v3_send_2, msg_v3_send_3
*/
  void msg_v3_send_var ( const msg_v3_const_type * xx_msg_const_ptr, uint32 num_args, ...);
/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with variable number 
   of (4 to 9) parameters.  

   @warning
   Do not call directly; use macros MSG_4(), ..MSG_9()

   @param[in] *xx_msg_v4_const            static constant constructed using 
   the different XX_MSG_V4_CONST macros
   @param[in] num_args                     number of parameters

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v4_send, msg_v4_send_1, msg_v4_send_2, msg_v4_send_3
*/
  void msg_v4_send_var(const msg_v4_const_type * xx_msg_const_ptr, uint32 num_args, ...);
/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with variable number 
   of (4 to 9) parameters.  

   @warning
   Do not call directly; use macros MSG_4(), ..MSG_9()

   @param[in] *xx_msg_v3_const            static constant constructed using 
   the different XX_MSG_V3_CONST macros
   @param[in] version                  Specifies the version - currently, there are two versions 
                                       0 - same as msg_v3_send_var() (for backwards compatibility)
                                       1 - The outgoing msg header will have the support to
                                           include ID field to differentiate messages
                                           coming from different instances of the processor.
   
   @param[in] *parameter                Based on the version passed in, this pointer is interpreted
                                       as follows-
                                       version       pointer
                                       0             NULL
                                       1             uint32 * . The uint32 value this pointer points to,
                                                     is the ID of the instance generating the msg.

   @param[in] num_args                number of parameters

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v3_send, msg_v3_send_1, msg_v3_send_2, msg_v3_send_3
*/
  void msg_v3_send_var_ext ( const msg_v3_const_type * xx_msg_const_ptr, uint32 version, void* parameter,
                              uint32 num_args, ...);
/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with variable number 
   of (4 to 9) parameters.  

   @warning
   Do not call directly; use macros MSG_4(), ..MSG_9()

   @param[in] *xx_msg_v4_const            static constant constructed using 
   the different XX_MSG_V4_CONST macros
   @param[in] version                  Specifies the version - currently, there are two versions 
                                       0 - same as msg_v4_send_var() (for backwards compatibility)
                                       1 - The outgoing msg header will have the support to
                                           include ID field to differentiate messages
                                           coming from different instances of the processor.
   
   @param[in] *parameter                Based on the version passed in, this pointer is interpreted
                                       as follows-
                                       version       pointer
                                       0             NULL
                                       1             uint32 * . The uint32 value this pointer points to,
                                                     is the ID of the instance generating the msg.

   @param[in] num_args                number of parameters

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v4_send, msg_v4_send_1, msg_v4_send_2, msg_v4_send_3
*/
  void msg_v4_send_var_ext ( const msg_v4_const_type * xx_msg_const_ptr, uint32 version, void* parameter,
                              uint32 num_args, ...);
/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with variable number
   of (4 to 9) parameters.

   @warning
   Do not call directly; use macros DIAGBUFFER_MSG_N_EXT

   @param[in] *xx_msg_v4_const            static constant constructed using
   the different XX_MSG_V4_CONST macros
   @param[in] xx_handle                Specifies the diagbuffer handle.
   @param[in] version                  Specifies the version - currently, there are two versions
                                       0 - same as msg_v4_send_var() (for backwards compatibility)
                                       1 - The outgoing msg header will have the support to
                                           include ID field to differentiate messages
                                           coming from different instances of the processor.

   @param[in] *parameter                Based on the version passed in, this pointer is interpreted
                                       as follows-
                                       version       pointer
                                       0             NULL
                                       1             uint32 * . The uint32 value this pointer points to,
                                                     is the ID of the instance generating the msg.

   @param[in] num_args                number of parameters

   @dependencies
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v4_send, msg_v4_send_1, msg_v4_send_2, msg_v4_send_3
*/
  void _msg_v4_diagbuffer_send_var_ext (diagbuffer_handle h,
                                   const msg_v4_const_type * xx_msg_const_ptr,
                                   uint32 version, void* parameter,uint32 num_args, ...);
/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 4 parameters. 
   This function is a shim API which calls msg_v4_send_4_ext_v1.  

   @warning
   Do not call directly; use macro MSG_4_EXT_V1()

   @param[in] *xx_msg_v4_const static constant constructed using 
   the different XX_MSG_V4_CONST macros
   
   @param[in] parameter                The version is hardcoded to 1
									   This uint32 value is the ID of the instance generating the msg.

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v4_send_ext_v1, msg_v4_send_2_ext_v1, msg_v4_send_3_ext_v1, msg_v4_send_5_ext_v1 ...
*/   
  void msg_v4_send_4_ext_v1 (const msg_v4_const_type * xx_msg_const_ptr, uint32 parameter, uint32 num_args, uint32 xx_arg1, uint32 xx_arg2, uint32 xx_arg3, uint32 xx_arg4);  
/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 5 parameters. 
   This function is a shim API which calls msg_v4_send_5_ext_v1.  

   @warning
   Do not call directly; use macro MSG_5_EXT_V1()

   @param[in] *xx_msg_v4_const static constant constructed using 
   the different XX_MSG_V4_CONST macros
   
   @param[in] parameter                The version is hardcoded to 1
									   This uint32 value is the ID of the instance generating the msg.

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v4_send_ext_v1, msg_v4_send_2_ext_v1, msg_v4_send_3_ext_v1, msg_v4_send_4_ext_v1 ...
*/   
  void msg_v4_send_5_ext_v1 (const msg_v4_const_type * xx_msg_const_ptr, uint32 parameter, uint32 num_args, uint32 xx_arg1, uint32 xx_arg2, uint32 xx_arg3, uint32 xx_arg4, uint32 xx_arg5);
/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 6 parameters. 
   This function is a shim API which calls msg_v4_send_6_ext_v1.  

   @warning
   Do not call directly; use macro MSG_6_EXT_V1()

   @param[in] *xx_msg_v4_const static constant constructed using 
   the different XX_MSG_V4_CONST macros
   
   @param[in] parameter                The version is hardcoded to 1
									   This uint32 value is the ID of the instance generating the msg.

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v4_send_ext_v1, msg_v4_send_2_ext_v1, msg_v4_send_3_ext_v1, msg_v4_send_4_ext_v1 ...
*/   
  void msg_v4_send_6_ext_v1 (const msg_v4_const_type * xx_msg_const_ptr, uint32 parameter, uint32 num_args, uint32 xx_arg1, uint32 xx_arg2, uint32 xx_arg3, uint32 xx_arg4, uint32 xx_arg5, uint32 xx_arg6);
/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 7 parameters. 
   This function is a shim API which calls msg_v4_send_7_ext_v1.  

   @warning
   Do not call directly; use macro MSG_7_EXT_V1()

   @param[in] *xx_msg_v4_const static constant constructed using 
   the different XX_MSG_V4_CONST macros
   
   @param[in] parameter                The version is hardcoded to 1
									   This uint32 value is the ID of the instance generating the msg.

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v4_send_ext_v1, msg_v4_send_2_ext_v1, msg_v4_send_3_ext_v1, msg_v4_send_4_ext_v1 ...
*/   
  void msg_v4_send_7_ext_v1 (const msg_v4_const_type * xx_msg_const_ptr, uint32 parameter, uint32 num_args, uint32 xx_arg1, uint32 xx_arg2, uint32 xx_arg3, uint32 xx_arg4, uint32 xx_arg5, uint32 xx_arg6, uint32 xx_arg7);
/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 8 parameters. 
   This function is a shim API which calls msg_v4_send_8_ext_v1.  

   @warning
   Do not call directly; use macro MSG_8_EXT_V1()

   @param[in] *xx_msg_v4_const static constant constructed using 
   the different XX_MSG_V4_CONST macros
   
   @param[in] parameter                The version is hardcoded to 1
									   This uint32 value is the ID of the instance generating the msg.

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v4_send_ext_v1, msg_v4_send_2_ext_v1, msg_v4_send_3_ext_v1, msg_v4_send_4_ext_v1 ...
*/   
  void msg_v4_send_8_ext_v1 (const msg_v4_const_type * xx_msg_const_ptr, uint32 parameter, uint32 num_args, uint32 xx_arg1, uint32 xx_arg2, uint32 xx_arg3, uint32 xx_arg4, uint32 xx_arg5, uint32 xx_arg6, uint32 xx_arg7, uint32 xx_arg8);
/*!
@ingroup diag_message_service
   @brief
   This will build a new style optimized diagnostic message with 9 parameters. 
   This function is a shim API which calls msg_v4_send_9_ext_v1.  

   @warning
   Do not call directly; use macro MSG_9_EXT_V1()

   @param[in] *xx_msg_v4_const static constant constructed using 
   the different XX_MSG_V4_CONST macros
   
   @param[in] parameter                The version is hardcoded to 1
									   This uint32 value is the ID of the instance generating the msg.

   @dependencies 
   msg_init() must have been called previously.  A free buffer must
   be available or the message will be ignored (never buffered).

   @sideeffects
   None

   @return
   None

   @sa
   msg_v4_send_ext_v1, msg_v4_send_2_ext_v1, msg_v4_send_3_ext_v1, msg_v4_send_4_ext_v1 ...
*/   
  void msg_v4_send_9_ext_v1 (const msg_v4_const_type * xx_msg_const_ptr, uint32 parameter, uint32 num_args, uint32 xx_arg1, uint32 xx_arg2, uint32 xx_arg3, uint32 xx_arg4, uint32 xx_arg5, uint32 xx_arg6, uint32 xx_arg7, uint32 xx_arg8, uint32 xx_arg9);

#ifdef __cplusplus
}
#endif

#endif	/* MSG_QSR_H */

