/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.6.8, Date: 30-Jul-2015.
 */
#ifndef TDSRRCASN1_CONST_H
#define TDSRRCASN1_CONST_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "tdsrtkey.h"
#include "rtpersrc/asn1per.h"

/**
 * Header file for ASN.1 module tdsrrcasn1_const
 */
/* Value definitions */

#ifdef __cplusplus
}
#endif

#endif
