/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.6.8, Date: 30-Jul-2015.
 */
#ifndef TDSRRCASN1ENC_H
#define TDSRRCASN1ENC_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "tdsrtkey.h"
#include "tdsrrcasn1.h"
#include "rtpersrc/asn1per.h"

EXTERN int asn1PE_tdsrrc_UL_DCCH_MessageType (OSCTXT* pctxt, tdsrrc_UL_DCCH_MessageType* pvalue);

EXTERN int asn1PE_tdsrrc_UL_DCCH_Message (OSCTXT* pctxt, tdsrrc_UL_DCCH_Message* pvalue);

EXTERN int asn1PE_tdsrrc_UL_CCCH_MessageType (OSCTXT* pctxt, tdsrrc_UL_CCCH_MessageType* pvalue);

EXTERN int asn1PE_tdsrrc_UL_CCCH_Message (OSCTXT* pctxt, tdsrrc_UL_CCCH_Message* pvalue);

#ifdef __cplusplus
}
#endif

#endif
