/**
 * This file was generated by the Objective Systems ASN1C Compiler
 * (http://www.obj-sys.com).  Version: 6.6.8, Date: 30-Jul-2015.
 */
#ifndef TDSRRCASN1DEC_H
#define TDSRRCASN1DEC_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <stdlib.h>
#include "tdsrtkey.h"
#include "tdsrrcasn1.h"
#include "rtpersrc/asn1per.h"

EXTERN int asn1PD_tdsrrc_DL_DCCH_MessageType (OSCTXT* pctxt, tdsrrc_DL_DCCH_MessageType* pvalue);

EXTERN int asn1PD_tdsrrc_DL_DCCH_Message (OSCTXT* pctxt, tdsrrc_DL_DCCH_Message* pvalue);

EXTERN int asn1PD_tdsrrc_DL_CCCH_MessageType (OSCTXT* pctxt, tdsrrc_DL_CCCH_MessageType* pvalue);

EXTERN int asn1PD_tdsrrc_DL_CCCH_Message (OSCTXT* pctxt, tdsrrc_DL_CCCH_Message* pvalue);

EXTERN int asn1PD_tdsrrc_PCCH_MessageType (OSCTXT* pctxt, tdsrrc_PCCH_MessageType* pvalue);

EXTERN int asn1PD_tdsrrc_PCCH_Message (OSCTXT* pctxt, tdsrrc_PCCH_Message* pvalue);

EXTERN int asn1PD_tdsrrc_BCCH_FACH_MessageType (OSCTXT* pctxt, tdsrrc_BCCH_FACH_MessageType* pvalue);

EXTERN int asn1PD_tdsrrc_BCCH_FACH_Message (OSCTXT* pctxt, tdsrrc_BCCH_FACH_Message* pvalue);

EXTERN int asn1PD_tdsrrc_BCCH_BCH_Message (OSCTXT* pctxt, tdsrrc_BCCH_BCH_Message* pvalue);

EXTERN int asn1PD_tdsrrc_MCCH_MessageType (OSCTXT* pctxt, tdsrrc_MCCH_MessageType* pvalue);

EXTERN int asn1PD_tdsrrc_MCCH_Message (OSCTXT* pctxt, tdsrrc_MCCH_Message* pvalue);

EXTERN int asn1PD_tdsrrc_MSCH_MessageType (OSCTXT* pctxt, tdsrrc_MSCH_MessageType* pvalue);

EXTERN int asn1PD_tdsrrc_MSCH_Message (OSCTXT* pctxt, tdsrrc_MSCH_Message* pvalue);

#ifdef __cplusplus
}
#endif

#endif
