#ifndef __HWKM_ERR_H__
#define __HWKM_ERR_H__

/*===========================================================================
  Copyright (c) 2019 Qualcomm Technologies, Inc.
  All Rights Reserved.
  Confidential and Proprietary - Qualcomm Technologies, Inc.
  ===========================================================================*/

#include <stdint.h>

/** SW HAL error codes */
#define HWKM_SUCCESS INT32_C(0)
#define HWKM_ERR_GENERIC INT32_C(1)
#define HWKM_NOT_SUPPORTED INT32_C(2)
#define HWKM_INVALID_ARG INT32_C(3)
#define HWKM_NO_MEMORY INT32_C(4)
#define HWKM_INVALID_DESTINATION INT32_C(5)
#define HWKM_CMD_FIFO_NOT_EMPTY INT32_C(6)
#define HWKM_CMD_FIFO_TIMEOUT INT32_C(7)
#define HWKM_RESPONSE_UNDERFLOW INT32_C(8)
#define HWKM_RESPONSE_OVERFLOW INT32_C(9)
#define HWKM_RSP_FIFO_TIMEOUT INT32_C(10)
#define HWKM_CLK_ERROR INT32_C(11)
#define HWKM_SET_TPKEY_FAILURE INT32_C(12)
#define HWKM_PROVISION_HW_KEY_FAILURE INT32_C(13)

/** Generates a mask with only this err bit */
#define HWKM_ERR_BIT(bit) (UINT32_C(1) << (bit))

/** Check if this err bit is set in the error status */
#define HWKM_IS_ERR_SET(status, err) (((status) & (err)) != 0)

/** SUCCESS code in status field of response packet */
#define HWKM_TRANSACTION_SUCCESS UINT32_C(0)

/** HWKM Error Codes common to all opcodes */
#define HWKM_COMMON_ERR_RESP_FIFO_UNDERFLOW HWKM_ERR_BIT(0)
#define HWKM_COMMON_ERR_CMD_FIFO_OVERFLOW HWKM_ERR_BIT(1)
#define HWKM_COMMON_ERR_OPCODE_NOT_SUPPORTED HWKM_ERR_BIT(2)
#define HWKM_COMMON_ERR_INVALID_OPCODE HWKM_ERR_BIT(3)
#define HWKM_COMMON_ERR_INCORRECT_CMD_LENGTH HWKM_ERR_BIT(4)
#define HWKM_COMMON_ERR_CMD_CRC_CHECK HWKM_ERR_BIT(5)
#define HWKM_COMMON_ERR_BBAC_ACCESS HWKM_ERR_BIT(6)
#define HWKM_COMMON_ERR_RESERVED HWKM_ERR_BIT(7)

/** NIST_KEYGEN errors */
#define HWKM_KEYGEN_ERR_KEYSLOT_ID_OUT_OF_RANGE HWKM_ERR_BIT(8)
#define HWKM_KEYGEN_ERR_UNSUPPORTED_KEY_SIZE HWKM_ERR_BIT(9)
#define HWKM_KEYGEN_ERR_KT_PARITY HWKM_ERR_BIT(10)
#define HWKM_KEYGEN_ERR_INVALID_KEY_TYPE HWKM_ERR_BIT(11)
#define HWKM_KEYGEN_ERR_INVALID_ALG_ALLOWED HWKM_ERR_BIT(12)
#define HWKM_KEYGEN_ERR_CONSISTENCY_CHECK_FAILED HWKM_ERR_BIT(13)
#define HWKM_KEYGEN_ERR_INVALID_TPKEY_ATTRIB HWKM_ERR_BIT(14)
#define HWKM_KEYGEN_ERR_INVALID_KSK_ATTRIB HWKM_ERR_BIT(15)
#define HWKM_KEYGEN_ERR_INVALID_KWK_ATTRIB HWKM_ERR_BIT(16)
#define HWKM_KEYGEN_ERR_INVALID_KDF_DEPTH HWKM_ERR_BIT(17)
#define HWKM_KEYGEN_ERR_INVALID_SECURITY_LEVEL HWKM_ERR_BIT(18)
#define HWKM_KEYGEN_ERR_DKS_SLOT_NOT_EMPTY HWKM_ERR_BIT(19)
#define HWKM_KEYGEN_ERR_ACCESS_VIOLATION HWKM_ERR_BIT(20)

/** KEYSLOT_RDWR errors */
#define HWKM_RDWR_ERR_KEYSLOT_ID_OUT_OF_RANGE HWKM_ERR_BIT(8)
#define HWKM_RDWR_ERR_UNSUPPORTED_KEY_SIZE HWKM_ERR_BIT(9)
#define HWKM_RDWR_ERR_KT_PARITY HWKM_ERR_BIT(10)
#define HWKM_RDWR_ERR_INVALID_SECURITY_LEVEL HWKM_ERR_BIT(11)
#define HWKM_RDWR_ERR_INVALID_KEY_TYPE HWKM_ERR_BIT(12)
#define HWKM_RDWR_ERR_INVALID_ALG_ALLOWED HWKM_ERR_BIT(13)
#define HWKM_RDWR_ERR_CONSISTENCY_CHECK_FAILED HWKM_ERR_BIT(14)
#define HWKM_RDWR_ERR_INVALID_TPKEY_ATTRIB HWKM_ERR_BIT(15)
#define HWKM_RDWR_ERR_INVALID_KSK_ATTRIB HWKM_ERR_BIT(16)
#define HWKM_RDWR_ERR_INVALID_KWK_ATTRIB HWKM_ERR_BIT(17)
#define HWKM_RDWR_ERR_INVALID_KDF_DEPTH HWKM_ERR_BIT(18)
#define HWKM_RDWR_ERR_SECURITY_LEVEL_VIOLATION HWKM_ERR_BIT(19)
#define HWKM_RDWR_ERR_SKS_SLOT_EMPTY HWKM_ERR_BIT(20)
#define HWKM_RDWR_ERR_DKS_SLOT_NOT_EMPTY HWKM_ERR_BIT(21)
#define HWKM_RDWR_ERR_ACCESS_VIOLATION HWKM_ERR_BIT(22)

/** SYSTEM_KDF errors */
#define HWKM_KDF_ERR_FR_RD_ERR_ON_SLAVE HWKM_ERR_BIT(8)
#define HWKM_KDF_ERR_MKS_L1L2_NOT_ALLOWED HWKM_ERR_BIT(9)
#define HWKM_KDF_ERR_SEC_CTRL_ACCESS HWKM_ERR_BIT(10)
#define HWKM_KDF_ERR_KT_PARITY HWKM_ERR_BIT(11)
#define HWKM_KDF_ERR_BSVE_BIT_NOT_SUPPORTED HWKM_ERR_BIT(12)
#define HWKM_KDF_ERR_INVALID_SECURITY_LEVEL HWKM_ERR_BIT(13)
#define HWKM_KDF_ERR_INVALID_KEY_TYPE HWKM_ERR_BIT(14)
#define HWKM_KDF_ERR_INVALID_ALG_ALLOWED HWKM_ERR_BIT(15)
#define HWKM_KDF_ERR_SWAP_EXPORT_NOT_ALLOWED HWKM_ERR_BIT(16)
#define HWKM_KDF_ERR_KEYPOLICY_CONSISTENCY HWKM_ERR_BIT(17)
#define HWKM_KDF_ERR_ENCRYPT_NOT_ALLOWED HWKM_ERR_BIT(18)
#define HWKM_KDF_ERR_UNEXPECTED_ALG_ALLOWED HWKM_ERR_BIT(19)
#define HWKM_KDF_ERR_UNEXPECTED_KEY_TYPE HWKM_ERR_BIT(20)
#define HWKM_KDF_ERR_KDF_DEPTH_ERROR HWKM_ERR_BIT(21)
#define HWKM_KDF_ERR_KDK_TYPE HWKM_ERR_BIT(22)
#define HWKM_KDF_ERR_KEY_SIZE HWKM_ERR_BIT(23)
#define HWKM_KDF_ERR_KEYSLOT_SLOT HWKM_ERR_BIT(24)
#define HWKM_KDF_ERR_KEYSLOT_OUT_OF_RANGE HWKM_ERR_BIT(25)
#define HWKM_KDF_ERR_DOUBLE_KEY_SLOT_NOT_EVEN HWKM_ERR_BIT(26)
#define HWKM_KDF_ERR_ACCESS_VIOLATION HWKM_ERR_BIT(27)
#define HWKM_KDF_ERR_SECURITY_LEVEL_VIOLATION HWKM_ERR_BIT(28)

/** KEY_WRAP_EXPORT errors */
#define HWKM_EXPORT_ERR_KWK_DOUBLE_KEY_ODD_SLOT HWKM_ERR_BIT(8)
#define HWKM_EXPORT_ERR_ENCRYPT_NOT_ALLOWED HWKM_ERR_BIT(9)
#define HWKM_EXPORT_ERR_SKS_SIZE_ERROR HWKM_ERR_BIT(10)
#define HWKM_EXPORT_ERR_SKS_SLOT_OUT_OF_RANGE HWKM_ERR_BIT(11)
#define HWKM_EXPORT_ERR_KWK_SIZE_ERROR HWKM_ERR_BIT(12)
#define HWKM_EXPORT_ERR_KWK_SLOT_OUT_OF_RANGE HWKM_ERR_BIT(13)
#define HWKM_EXPORT_ERR_KT_PARITY HWKM_ERR_BIT(14)
#define HWKM_EXPORT_ERR_WRAP_WITH_TPKEY_NOT_ALLOWED HWKM_ERR_BIT(15)
#define HWKM_EXPORT_ERR_SWAP_EXPORT_NOT_ALLOWED HWKM_ERR_BIT(16)
#define HWKM_EXPORT_ERR_WRAP_EXPORT_NOT_ALLOWED HWKM_ERR_BIT(17)
#define HWKM_EXPORT_ERR_UNEXPECTED_ALG_ALLOWED HWKM_ERR_BIT(18)
#define HWKM_EXPORT_ERR_SECURITY_LEVEL_ERROR HWKM_ERR_BIT(19)
#define HWKM_EXPORT_ERR_UNEXPECTED_KEY_TYPE HWKM_ERR_BIT(20)
#define HWKM_EXPORT_ERR_KWK_SLOT_EMPTY HWKM_ERR_BIT(21)
#define HWKM_EXPORT_ERR_SKS_SLOT_EMPTY HWKM_ERR_BIT(22)
#define HWKM_EXPORT_ERR_SKS_ACCESS_VIOLATION HWKM_ERR_BIT(23)
#define HWKM_EXPORT_ERR_KWK_ACCESS_VIOLATION HWKM_ERR_BIT(24)

/** KEY_UNWRAP_IMPORT errors */
#define HWKM_IMPORT_ERR_UNWRAP_FAILED HWKM_ERR_BIT(8)
#define HWKM_IMPORT_ERR_KWK_DOUBLE_KEY_ODD_SLOT HWKM_ERR_BIT(9)
#define HWKM_IMPORT_ERR_KWK_SIZE_ERROR HWKM_ERR_BIT(10)
#define HWKM_IMPORT_ERR_DKS_SIZE_ERROR HWKM_ERR_BIT(11)
#define HWKM_IMPORT_ERR_DKS_OUT_OF_RANGE HWKM_ERR_BIT(12)
#define HWKM_IMPORT_ERR_KWK_SLOT_OUT_OF_RANGE HWKM_ERR_BIT(13)
#define HWKM_IMPORT_ERR_KT_PARITY HWKM_ERR_BIT(14)
#define HWKM_IMPORT_ERR_SECURITY_LEVEL_ERROR HWKM_ERR_BIT(15)
#define HWKM_IMPORT_ERR_INVALID_SECURITY_LEVEL HWKM_ERR_BIT(16)
#define HWKM_IMPORT_ERR_INVALID_KEY_TYPE HWKM_ERR_BIT(17)
#define HWKM_IMPORT_ERR_INVALID_ALG_ALLOWED HWKM_ERR_BIT(18)
#define HWKM_IMPORT_ERR_CONSISTENCY_CHECK_FAILED HWKM_ERR_BIT(19)
#define HWKM_IMPORT_ERR_INVALID_TPKEY_ATTRIB HWKM_ERR_BIT(20)
#define HWKM_IMPORT_ERR_INVALID_KSK_ATTRIB HWKM_ERR_BIT(21)
#define HWKM_IMPORT_ERR_INVALID_KWK_ATTRIB HWKM_ERR_BIT(22)
#define HWKM_IMPORT_ERR_INVALID_KDF_DEPTH HWKM_ERR_BIT(23)
#define HWKM_IMPORT_ERR_DECRYPT_NOT_ALLOWED HWKM_ERR_BIT(24)
#define HWKM_IMPORT_ERR_UNEXPECTED_ALG_ALLOWED HWKM_ERR_BIT(25)
#define HWKM_IMPORT_ERR_UNEXPECTED_KEY_TYPE HWKM_ERR_BIT(26)
#define HWKM_IMPORT_ERR_KWK_SLOT_EMPTY HWKM_ERR_BIT(27)
#define HWKM_IMPORT_ERR_DKS_SLOT_NOT_EMPTY HWKM_ERR_BIT(28)

/**
 * Note: this error bit is documented in the HPG as ERR_DKS_ACCESS_VIOLATION,
 * but it can be set when the WKB is incorrect.
 */
#define HWKM_IMPORT_ERR_WKB_CORRUPTED HWKM_ERR_BIT(29)
#define HWKM_IMPORT_ERR_DKS_ACCESS_VIOLATION HWKM_ERR_BIT(29)

#define HWKM_IMPORT_ERR_KWK_ACCESS_VIOLATION HWKM_ERR_BIT(30)

/** SET_TPKEY errors */
#define HWKM_TPKEY_ERR_KT_PARITY HWKM_ERR_BIT(8)
#define HWKM_TPKEY_ERR_DOUBLE_KEY_SLOT_NOT_EVEN HWKM_ERR_BIT(9)
#define HWKM_TPKEY_ERR_WRONG_KEY_SIZE HWKM_ERR_BIT(10)
#define HWKM_TPKEY_ERR_KEYSLOT_ID_OUT_OF_RANGE HWKM_ERR_BIT(11)
#define HWKM_TPKEY_ERR_UNEXPECTED_KEY_TYPE HWKM_ERR_BIT(12)
#define HWKM_TPKEY_ERR_SKS_SLOT_EMPTY HWKM_ERR_BIT(13)
#define HWKM_TPKEY_ERR_ACCESS_VIOLATION HWKM_ERR_BIT(14)

/** KEYSLOT_CLEAR errors */
#define HWKM_CLEAR_ERR_KEYSLOT_ID_NOT_ACCESSIBLE HWKM_ERR_BIT(8)
#define HWKM_CLEAR_ERR_KEYSLOT_ID_OUT_OF_RANGE HWKM_ERR_BIT(9)
#define HWKM_CLEAR_ERR_KEY_SIZE HWKM_ERR_BIT(10)
#define HWKM_CLEAR_ERR_DOUBLE_KEY_DKS_SLOT_NOT_EVEN HWKM_ERR_BIT(11)
#define HWKM_CLEAR_ERR_DKS_SLOT_EMPTY HWKM_ERR_BIT(12)
#define HWKM_CLEAR_ERR_ACCESS_VIOLATION HWKM_ERR_BIT(13)

#endif
