#ifndef WCSS_DBG_CSR_HWIO_H
#define WCSS_DBG_CSR_HWIO_H

/*  ===========================================================================

  Copyright (c) 2015 Qualcomm Technologies Incorporated.
  All Rights Reserved.
  Qualcomm Confidential and Proprietary

  Export of this technology or software is regulated by the U.S. Government.
  Diversion contrary to U.S. law prohibited.

  All ideas, data and information contained in or disclosed by
  this document are confidential and proprietary information of
  Qualcomm Technologies Incorporated and all rights therein are expressly reserved.
  By accepting this material the recipient agrees that this material
  and the information contained therein are held in confidence and in
  trust and will not be used, copied, reproduced in whole or in part,
  nor its contents revealed in any manner to others without the express
  written permission of Qualcomm Technologies Incorporated.

  ===========================================================================
*/

#include "HALhwio.h"

/*----------------------------------------------------------------------------
 * MODULE: WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR
 *--------------------------------------------------------------------------*/

extern uint32 WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE;                        

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_PRESERVEETF_ADDR                                (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000000)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_PRESERVEETF_RMSK                                0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_PRESERVEETF_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_PRESERVEETF_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_PRESERVEETF_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_PRESERVEETF_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_PRESERVEETF_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_PRESERVEETF_RFU_BMSK                            0xff800000
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_PRESERVEETF_RFU_SHFT                                  0x17
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_PRESERVEETF_STS_MEMERR_BMSK                       0x400000
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_PRESERVEETF_STS_MEMERR_SHFT                           0x16
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_PRESERVEETF_AFVALIDS_BMSK                         0x200000
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_PRESERVEETF_AFVALIDS_SHFT                             0x15
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_PRESERVEETF_STS_EMPTY_BMSK                        0x100000
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_PRESERVEETF_STS_EMPTY_SHFT                            0x14
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_PRESERVEETF_ACQCOMP_BMSK                           0x80000
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_PRESERVEETF_ACQCOMP_SHFT                              0x13
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_PRESERVEETF_STS_TMCREADY_BMSK                      0x40000
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_PRESERVEETF_STS_TMCREADY_SHFT                         0x12
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_PRESERVEETF_STS_TRIGGERED_BMSK                     0x20000
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_PRESERVEETF_STS_TRIGGERED_SHFT                        0x11
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_PRESERVEETF_FULL_BMSK                              0x10000
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_PRESERVEETF_FULL_SHFT                                 0x10
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_PRESERVEETF_RWP_PRESERVE_BMSK                       0xffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_PRESERVEETF_RWP_PRESERVE_SHFT                          0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TRC_CFG_ADDR                                    (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000004)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TRC_CFG_RMSK                                          0x7f
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TRC_CFG_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TRC_CFG_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TRC_CFG_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TRC_CFG_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TRC_CFG_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TRC_CFG_OUT(v)      \
        out_dword(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TRC_CFG_ADDR,v)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TRC_CFG_OUTM(m,v) \
        out_dword_masked_ns(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TRC_CFG_ADDR,m,v,HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TRC_CFG_IN)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TRC_CFG_AFV_ALLOW_EXT_EN_BMSK                         0x40
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TRC_CFG_AFV_ALLOW_EXT_EN_SHFT                          0x6
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TRC_CFG_AFV_SW_EN_BMSK                                0x20
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TRC_CFG_AFV_SW_EN_SHFT                                 0x5
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TRC_CFG_CMB_OWNER_BMSK                                0x18
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TRC_CFG_CMB_OWNER_SHFT                                 0x3
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TRC_CFG_MEM_LAYOUT_BMSK                                0x4
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TRC_CFG_MEM_LAYOUT_SHFT                                0x2
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TRC_CFG_MEM_OWNER_BMSK                                 0x3
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TRC_CFG_MEM_OWNER_SHFT                                 0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TSTMP_CFG_ADDR                                  (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000008)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TSTMP_CFG_RMSK                                         0xf
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TSTMP_CFG_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TSTMP_CFG_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TSTMP_CFG_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TSTMP_CFG_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TSTMP_CFG_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TSTMP_CFG_OUT(v)      \
        out_dword(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TSTMP_CFG_ADDR,v)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TSTMP_CFG_OUTM(m,v) \
        out_dword_masked_ns(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TSTMP_CFG_ADDR,m,v,HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TSTMP_CFG_IN)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TSTMP_CFG_TPDA_FREQREQ_EN_BMSK                         0x8
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TSTMP_CFG_TPDA_FREQREQ_EN_SHFT                         0x3
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TSTMP_CFG_SLP_CORR_EN_BMSK                             0x4
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TSTMP_CFG_SLP_CORR_EN_SHFT                             0x2
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TSTMP_CFG_SOURCE_BMSK                                  0x3
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_TSTMP_CFG_SOURCE_SHFT                                  0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_QDSS_TSTMP_VAL_LO_ADDR                          (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x0000000c)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_QDSS_TSTMP_VAL_LO_RMSK                          0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_QDSS_TSTMP_VAL_LO_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_QDSS_TSTMP_VAL_LO_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_QDSS_TSTMP_VAL_LO_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_QDSS_TSTMP_VAL_LO_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_QDSS_TSTMP_VAL_LO_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_QDSS_TSTMP_VAL_LO_TSTMP_VAL_31_0_BMSK           0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_QDSS_TSTMP_VAL_LO_TSTMP_VAL_31_0_SHFT                  0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_QDSS_TSTMP_VAL_HI_ADDR                          (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000010)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_QDSS_TSTMP_VAL_HI_RMSK                          0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_QDSS_TSTMP_VAL_HI_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_QDSS_TSTMP_VAL_HI_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_QDSS_TSTMP_VAL_HI_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_QDSS_TSTMP_VAL_HI_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_QDSS_TSTMP_VAL_HI_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_QDSS_TSTMP_VAL_HI_TSTMP_VAL_63_32_BMSK          0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_QDSS_TSTMP_VAL_HI_TSTMP_VAL_63_32_SHFT                 0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_INT_TSTMP_VAL_LO_ADDR                           (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000014)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_INT_TSTMP_VAL_LO_RMSK                           0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_INT_TSTMP_VAL_LO_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_INT_TSTMP_VAL_LO_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_INT_TSTMP_VAL_LO_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_INT_TSTMP_VAL_LO_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_INT_TSTMP_VAL_LO_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_INT_TSTMP_VAL_LO_TSTMP_VAL_31_0_BMSK            0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_INT_TSTMP_VAL_LO_TSTMP_VAL_31_0_SHFT                   0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_INT_TSTMP_VAL_HI_ADDR                           (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000018)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_INT_TSTMP_VAL_HI_RMSK                           0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_INT_TSTMP_VAL_HI_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_INT_TSTMP_VAL_HI_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_INT_TSTMP_VAL_HI_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_INT_TSTMP_VAL_HI_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_INT_TSTMP_VAL_HI_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_INT_TSTMP_VAL_HI_TSTMP_VAL_63_32_BMSK           0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_INT_TSTMP_VAL_HI_TSTMP_VAL_63_32_SHFT                  0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SWGEN_DSB_ADDR                                  (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x0000001c)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SWGEN_DSB_RMSK                                        0xff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SWGEN_DSB_OUT(v)      \
        out_dword(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SWGEN_DSB_ADDR,v)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SWGEN_DSB_EVENT7_BMSK                                 0x80
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SWGEN_DSB_EVENT7_SHFT                                  0x7
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SWGEN_DSB_EVENT6_BMSK                                 0x40
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SWGEN_DSB_EVENT6_SHFT                                  0x6
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SWGEN_DSB_EVENT5_BMSK                                 0x20
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SWGEN_DSB_EVENT5_SHFT                                  0x5
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SWGEN_DSB_EVENT4_BMSK                                 0x10
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SWGEN_DSB_EVENT4_SHFT                                  0x4
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SWGEN_DSB_EVENT3_BMSK                                  0x8
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SWGEN_DSB_EVENT3_SHFT                                  0x3
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SWGEN_DSB_EVENT2_BMSK                                  0x4
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SWGEN_DSB_EVENT2_SHFT                                  0x2
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SWGEN_DSB_EVENT1_BMSK                                  0x2
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SWGEN_DSB_EVENT1_SHFT                                  0x1
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SWGEN_DSB_EVENT0_BMSK                                  0x1
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SWGEN_DSB_EVENT0_SHFT                                  0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CLK_INFO_ADDR                                   (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000020)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CLK_INFO_RMSK                                      0x331f1
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CLK_INFO_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CLK_INFO_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CLK_INFO_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CLK_INFO_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CLK_INFO_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CLK_INFO_TSTMP_DIV_BMSK                            0x30000
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CLK_INFO_TSTMP_DIV_SHFT                               0x10
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CLK_INFO_APB_DIV_BMSK                               0x3000
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CLK_INFO_APB_DIV_SHFT                                  0xc
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CLK_INFO_ATB_DIV_BMSK                                0x1f0
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CLK_INFO_ATB_DIV_SHFT                                  0x4
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CLK_INFO_SRC_BMSK                                      0x1
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CLK_INFO_SRC_SHFT                                      0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_ADDR                                   (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000024)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_RMSK                                    0x3ffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_OUT(v)      \
        out_dword(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_ADDR,v)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_OUTM(m,v) \
        out_dword_masked_ns(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_ADDR,m,v,HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_IN)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_FREQ_BMSK                               0x3ffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_FREQ_SHFT                                     0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_IN_KHZ_ADDR                            (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000028)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_IN_KHZ_RMSK                                0xffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_IN_KHZ_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_IN_KHZ_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_IN_KHZ_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_IN_KHZ_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_IN_KHZ_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_IN_KHZ_OUT(v)      \
        out_dword(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_IN_KHZ_ADDR,v)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_IN_KHZ_OUTM(m,v) \
        out_dword_masked_ns(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_IN_KHZ_ADDR,m,v,HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_IN_KHZ_IN)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_IN_KHZ_FREQ_BMSK                           0xffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_CXO_FREQ_IN_KHZ_FREQ_SHFT                              0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SPARE_ADDR                                      (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x0000002c)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SPARE_RMSK                                      0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SPARE_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SPARE_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SPARE_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SPARE_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SPARE_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SPARE_OUT(v)      \
        out_dword(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SPARE_ADDR,v)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SPARE_OUTM(m,v) \
        out_dword_masked_ns(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SPARE_ADDR,m,v,HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SPARE_IN)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SPARE_SPARE_BMSK                                0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_SPARE_SPARE_SHFT                                       0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_IPCAT_ADDR                                      (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000030)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_IPCAT_RMSK                                      0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_IPCAT_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_IPCAT_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_IPCAT_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_IPCAT_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_IPCAT_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_IPCAT_MAJ_BMSK                                  0xf0000000
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_IPCAT_MAJ_SHFT                                        0x1c
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_IPCAT_MIN_BMSK                                   0xfff0000
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_IPCAT_MIN_SHFT                                        0x10
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_IPCAT_STEP_BMSK                                     0xffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_WCSSDBGCSR_IPCAT_STEP_SHFT                                        0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_CTRL_ADDR                                     (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000400)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_CTRL_RMSK                                           0x3f
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_CTRL_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_CTRL_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_CTRL_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_CTRL_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_CTRL_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_CTRL_OUT(v)      \
        out_dword(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_CTRL_ADDR,v)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_CTRL_OUTM(m,v) \
        out_dword_masked_ns(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_CTRL_ADDR,m,v,HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_CTRL_IN)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_CTRL_LATENCY_EN_BMSK                                0x20
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_CTRL_LATENCY_EN_SHFT                                 0x5
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_CTRL_RESP_TYPE_EN_BMSK                              0x10
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_CTRL_RESP_TYPE_EN_SHFT                               0x4
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_CTRL_XFER_TYPE_EN_BMSK                               0x8
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_CTRL_XFER_TYPE_EN_SHFT                               0x3
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_CTRL_PSEL_EN_BMSK                                    0x4
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_CTRL_PSEL_EN_SHFT                                    0x2
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_CTRL_ADDR_EN_BMSK                                    0x2
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_CTRL_ADDR_EN_SHFT                                    0x1
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_CTRL_ENABLE_BMSK                                     0x1
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_CTRL_ENABLE_SHFT                                     0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_LO_ADDR                                 (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000404)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_LO_RMSK                                   0x7fffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_LO_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_LO_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_LO_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_LO_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_LO_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_LO_OUT(v)      \
        out_dword(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_LO_ADDR,v)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_LO_OUTM(m,v) \
        out_dword_masked_ns(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_LO_ADDR,m,v,HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_LO_IN)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_LO_ADDR_BMSK                              0x7fffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_LO_ADDR_SHFT                                   0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_HI_ADDR                                 (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000408)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_HI_RMSK                                   0x7fffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_HI_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_HI_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_HI_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_HI_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_HI_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_HI_OUT(v)      \
        out_dword(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_HI_ADDR,v)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_HI_OUTM(m,v) \
        out_dword_masked_ns(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_HI_ADDR,m,v,HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_HI_IN)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_HI_ADDR_BMSK                              0x7fffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_PADDR_HI_ADDR_SHFT                                   0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_ADDR                                  (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x0000040c)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_RMSK                                     0x3ffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_OUT(v)      \
        out_dword(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_ADDR,v)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_OUTM(m,v) \
        out_dword_masked_ns(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_ADDR,m,v,HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_IN)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_RESP_TYPE_BMSK                           0x20000
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_RESP_TYPE_SHFT                              0x11
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_XFER_TYPE_BMSK                           0x10000
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_XFER_TYPE_SHFT                              0x10
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL15_RSVD_BMSK                          0x8000
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL15_RSVD_SHFT                             0xf
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL14_RSVD_BMSK                          0x4000
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL14_RSVD_SHFT                             0xe
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL13_RSVD_BMSK                          0x2000
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL13_RSVD_SHFT                             0xd
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL12_RSVD_BMSK                          0x1000
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL12_RSVD_SHFT                             0xc
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL11_RSVD_BMSK                           0x800
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL11_RSVD_SHFT                             0xb
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL_TSLV_BMSK                             0x400
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL_TSLV_SHFT                               0xa
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL_PHY2FD_BMSK                           0x200
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL_PHY2FD_SHFT                             0x9
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL_PHY2TD_BMSK                           0x100
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL_PHY2TD_SHFT                             0x8
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL_PHY1FD_BMSK                            0x80
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL_PHY1FD_SHFT                             0x7
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL_PHY1TD_BMSK                            0x40
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL_PHY1TD_SHFT                             0x6
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL_WCMN_BMSK                              0x20
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL_WCMN_SHFT                               0x5
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL_DBG_BMSK                               0x10
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL_DBG_SHFT                                0x4
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL_RFACTRL_BMSK                            0x8
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL_RFACTRL_SHFT                            0x3
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL_CSS_BMSK                                0x4
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL_CSS_SHFT                                0x2
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL_WMAC2_BMSK                              0x2
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL_WMAC2_SHFT                              0x1
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL_WMAC1_BMSK                              0x1
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MATCH_DETAILS_PSEL_WMAC1_SHFT                              0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MAX_LATENCY_ADDR                                    (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000410)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MAX_LATENCY_RMSK                                       0x1ffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MAX_LATENCY_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MAX_LATENCY_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MAX_LATENCY_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MAX_LATENCY_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MAX_LATENCY_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MAX_LATENCY_OUT(v)      \
        out_dword(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MAX_LATENCY_ADDR,v)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MAX_LATENCY_OUTM(m,v) \
        out_dword_masked_ns(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MAX_LATENCY_ADDR,m,v,HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MAX_LATENCY_IN)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MAX_LATENCY_LATENCY_BMSK                               0x1ffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_MAX_LATENCY_LATENCY_SHFT                                   0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_CMB_CFG_ADDR                                        (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000414)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_CMB_CFG_RMSK                                               0x3
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_CMB_CFG_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_CMB_CFG_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_CMB_CFG_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_CMB_CFG_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_CMB_CFG_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_CMB_CFG_OUT(v)      \
        out_dword(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_CMB_CFG_ADDR,v)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_CMB_CFG_OUTM(m,v) \
        out_dword_masked_ns(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_CMB_CFG_ADDR,m,v,HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_CMB_CFG_IN)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_CMB_CFG_DATA_EN_BMSK                                       0x2
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_CMB_CFG_DATA_EN_SHFT                                       0x1
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_CMB_CFG_ENABLE_BMSK                                        0x1
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_CMB_CFG_ENABLE_SHFT                                        0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_ADDR_ADDR                                  (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000418)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_ADDR_RMSK                                    0x7fffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_ADDR_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_ADDR_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_ADDR_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_ADDR_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_ADDR_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_ADDR_ADDR_BMSK                               0x7fffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_ADDR_ADDR_SHFT                                    0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_DETAILS_ADDR                               (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x0000041c)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_DETAILS_RMSK                                0x1ffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_DETAILS_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_DETAILS_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_DETAILS_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_DETAILS_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_DETAILS_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_DETAILS_LATENCY_BMSK                        0x1ffffc0
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_DETAILS_LATENCY_SHFT                              0x6
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_DETAILS_RESP_TYPE_BMSK                           0x20
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_DETAILS_RESP_TYPE_SHFT                            0x5
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_DETAILS_XFER_TYPE_BMSK                           0x10
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_DETAILS_XFER_TYPE_SHFT                            0x4
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_DETAILS_PSEL_BMSK                                 0xf
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_DETAILS_PSEL_SHFT                                 0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_DATA_ADDR                                  (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000420)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_DATA_RMSK                                  0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_DATA_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_DATA_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_DATA_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_DATA_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_DATA_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_DATA_DATA_BMSK                             0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_DATA_DATA_SHFT                                    0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_TSTMP_LO_ADDR                              (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000424)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_TSTMP_LO_RMSK                              0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_TSTMP_LO_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_TSTMP_LO_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_TSTMP_LO_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_TSTMP_LO_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_TSTMP_LO_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_TSTMP_LO_TSTMP_31_0_BMSK                   0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_TSTMP_LO_TSTMP_31_0_SHFT                          0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_TSTMP_HI_ADDR                              (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000428)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_TSTMP_HI_RMSK                              0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_TSTMP_HI_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_TSTMP_HI_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_TSTMP_HI_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_TSTMP_HI_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_TSTMP_HI_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_TSTMP_HI_TSTMP_63_32_BMSK                  0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_APBMON_LST_XFER_TSTMP_HI_TSTMP_63_32_SHFT                         0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_ITCTL_ADDR                                   (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000f00)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_ITCTL_RMSK                                   0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_ITCTL_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_ITCTL_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_ITCTL_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_ITCTL_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_ITCTL_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_ITCTL_RFU_BMSK                               0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_ITCTL_RFU_SHFT                                      0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_CLAIMSET_ADDR                                (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000fa0)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_CLAIMSET_RMSK                                0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_CLAIMSET_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_CLAIMSET_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_CLAIMSET_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_CLAIMSET_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_CLAIMSET_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_CLAIMSET_RFU_BMSK                            0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_CLAIMSET_RFU_SHFT                                   0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_CLAIMCLR_ADDR                                (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000fa4)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_CLAIMCLR_RMSK                                0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_CLAIMCLR_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_CLAIMCLR_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_CLAIMCLR_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_CLAIMCLR_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_CLAIMCLR_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_CLAIMCLR_RFU_BMSK                            0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_CLAIMCLR_RFU_SHFT                                   0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_AUTHSTATUS_ADDR                              (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000fb8)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_AUTHSTATUS_RMSK                                    0xff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_AUTHSTATUS_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_AUTHSTATUS_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_AUTHSTATUS_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_AUTHSTATUS_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_AUTHSTATUS_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_AUTHSTATUS_SI_BMSK                                 0xc0
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_AUTHSTATUS_SI_SHFT                                  0x6
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_AUTHSTATUS_NSI_BMSK                                0x30
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_AUTHSTATUS_NSI_SHFT                                 0x4
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_AUTHSTATUS_SNI_BMSK                                 0xc
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_AUTHSTATUS_SNI_SHFT                                 0x2
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_AUTHSTATUS_NSNI_BMSK                                0x3
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_AUTHSTATUS_NSNI_SHFT                                0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_DEVICEID_ADDR                                (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000fc8)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_DEVICEID_RMSK                                0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_DEVICEID_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_DEVICEID_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_DEVICEID_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_DEVICEID_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_DEVICEID_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_DEVICEID_RFU_BMSK                            0xffffff00
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_DEVICEID_RFU_SHFT                                   0x8
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_DEVICEID_DEVID_BMSK                                0xff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_DEVICEID_DEVID_SHFT                                 0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_DEVICETYPE_ADDR                              (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000fcc)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_DEVICETYPE_RMSK                              0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_DEVICETYPE_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_DEVICETYPE_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_DEVICETYPE_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_DEVICETYPE_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_DEVICETYPE_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_DEVICETYPE_RFU_BMSK                          0xffffff00
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_DEVICETYPE_RFU_SHFT                                 0x8
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_DEVICETYPE_SUBTYPE_BMSK                            0xf0
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_DEVICETYPE_SUBTYPE_SHFT                             0x4
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_DEVICETYPE_MAJTYPE_BMSK                             0xf
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_DEVICETYPE_MAJTYPE_SHFT                             0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID4_ADDR                               (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000fd0)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID4_RMSK                               0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID4_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID4_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID4_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID4_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID4_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID4_RFU_BMSK                           0xffffff00
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID4_RFU_SHFT                                  0x8
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID4_FIELD_4KB_COUNT_BMSK                     0xf0
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID4_FIELD_4KB_COUNT_SHFT                      0x4
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID4_JEP106_CONTINUATION_BMSK                  0xf
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID4_JEP106_CONTINUATION_SHFT                  0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID5_ADDR                               (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000fd4)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID5_RMSK                               0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID5_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID5_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID5_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID5_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID5_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID5_RFU_BMSK                           0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID5_RFU_SHFT                                  0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID6_ADDR                               (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000fd8)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID6_RMSK                               0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID6_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID6_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID6_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID6_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID6_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID6_RFU_BMSK                           0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID6_RFU_SHFT                                  0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID7_ADDR                               (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000fdc)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID7_RMSK                               0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID7_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID7_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID7_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID7_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID7_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID7_RFU_BMSK                           0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID7_RFU_SHFT                                  0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID0_ADDR                               (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000fe0)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID0_RMSK                               0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID0_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID0_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID0_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID0_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID0_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID0_RFU_BMSK                           0xffffff00
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID0_RFU_SHFT                                  0x8
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID0_PARTNUM_BMSK                             0xff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID0_PARTNUM_SHFT                              0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID1_ADDR                               (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000fe4)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID1_RMSK                               0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID1_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID1_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID1_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID1_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID1_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID1_RFU_BMSK                           0xffffff00
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID1_RFU_SHFT                                  0x8
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID1_JEP106_IDENTITY_3_0_BMSK                 0xf0
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID1_JEP106_IDENTITY_3_0_SHFT                  0x4
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID1_PARTNUM_BMSK                              0xf
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID1_PARTNUM_SHFT                              0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID2_ADDR                               (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000fe8)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID2_RMSK                               0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID2_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID2_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID2_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID2_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID2_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID2_RFU_BMSK                           0xffffff00
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID2_RFU_SHFT                                  0x8
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID2_MAJREV_BMSK                              0xf0
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID2_MAJREV_SHFT                               0x4
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID2_JEDEC_BMSK                                0x8
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID2_JEDEC_SHFT                                0x3
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID2_JEP106_IDENTITY_6_4_BMSK                  0x7
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID2_JEP106_IDENTITY_6_4_SHFT                  0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID3_ADDR                               (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000fec)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID3_RMSK                               0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID3_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID3_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID3_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID3_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID3_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID3_RFU_BMSK                           0xffffff00
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID3_RFU_SHFT                                  0x8
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID3_REV_AND_BMSK                             0xf0
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID3_REV_AND_SHFT                              0x4
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID3_CUSTOMER_MODIFIED_BMSK                    0xf
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_PERIPHID3_CUSTOMER_MODIFIED_SHFT                    0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID0_ADDR                                 (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000ff0)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID0_RMSK                                 0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID0_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID0_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID0_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID0_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID0_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID0_RFU_BMSK                             0xffffff00
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID0_RFU_SHFT                                    0x8
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID0_PREAMBLE_7_0_BMSK                          0xff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID0_PREAMBLE_7_0_SHFT                           0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID1_ADDR                                 (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000ff4)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID1_RMSK                                 0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID1_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID1_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID1_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID1_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID1_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID1_RFU_BMSK                             0xffffff00
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID1_RFU_SHFT                                    0x8
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID1_PREAMBLE_15_12_BMSK                        0xf0
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID1_PREAMBLE_15_12_SHFT                         0x4
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID1_PREAMBLE_11_8_BMSK                          0xf
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID1_PREAMBLE_11_8_SHFT                          0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID2_ADDR                                 (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000ff8)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID2_RMSK                                 0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID2_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID2_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID2_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID2_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID2_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID2_RFU_BMSK                             0xffffff00
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID2_RFU_SHFT                                    0x8
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID2_PREAMBLE_23_16_BMSK                        0xff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID2_PREAMBLE_23_16_SHFT                         0x0

#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID3_ADDR                                 (WCSS_HM_A_WCSS_DBG_CSR_CSR_WCSS_DBG_CSR_REG_BASE      + 0x00000ffc)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID3_RMSK                                 0xffffffff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID3_IN          \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID3_ADDR, HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID3_RMSK)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID3_INM(m)      \
        in_dword_masked(HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID3_ADDR, m)
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID3_RFU_BMSK                             0xffffff00
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID3_RFU_SHFT                                    0x8
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID3_PREAMBLE_31_24_BMSK                        0xff
#define HWIO_WCSS_HM_A_WCSS_DBG_CSR_CS_WCSSDBGCSR_COMPID3_PREAMBLE_31_24_SHFT                         0x0



#endif //WCSS_DBG_CSR_HWIO_H
