/*!
  @file
  ftm_rf_test_rx_measure.c

  @brief
  Common framework to perform radio test in FTM mode
*/

/*======================================================================================================================

  Copyright (c) 2015 Qualcomm Technologies Incorporated. All Rights Reserved

  Qualcomm Proprietary

  Export of this technology or software is regulated by the U.S. Government.
  Diversion contrary to U.S. law prohibited.

  All ideas, data and information contained in or disclosed by this document are confidential 
  and proprietary information of Qualcomm Technologies Incorporated and all rights therein are 
  expressly reserved. By accepting this material the recipient agrees that this material and the 
  information contained therein are held in confidence and in trust and will not be used, copied, 
  reproduced in whole or in part, nor its contents revealed in any manner to others without the 
  express written permission of Qualcomm Technologies Incorporated.

======================================================================================================================*/

/*======================================================================================================================

                        EDIT HISTORY FOR MODULE

  This section contains comments describing changes made to the module.
  Notice that changes are listed in reverse chronological order.

  $Header: //components/rel/rfa.mpss/4.11/rf/common/ftm/src/ftm_rf_test_rx_measure.c#1 $

when       who     what, where, why
--------   ---     -----------------------------------------------------------------------------------------------------
09/10/15   zhw     Updated default response allocate helper API for Rx Measure
08/11/15   zhw     Added support for Tx Control Command
08/04/15   zhw     Added Tech Override support for Rx Measure Command
08/03/15   zhw     Added support for tech bypass dispatch
07/31/15   zhw     Kw fix
07/30/15   zhw     Updated support for Rx Measure Command. Fixed memory overflow
07/17/15   zhw     Initial Release

======================================================================================================================*/
#include "comdef.h"
#include "ftm_rf_test_interface.h"
#include "ftm_rf_test_rx_measure.h"
#include "ftm_msg.h"
#include "ftm_common_control.h"
#include "modem_mem.h"
#include "stringl.h"
#include "rfcommon_math.h"

/*====================================================================================================================*/
/*!
  @addtogroup FTM_TEST_TOOLS_RX_MEASURE
  @{
*/

/*====================================================================================================================*/
/*!
  @name Unpack

  @brief
  Functions to manage Rx Measure command unpack
*/
/*! @{ */

/*--------------------------------------------------------------------------------------------------------------------*/
/*!
  @brief
  Unpack Rx Measure command packet to default format
 
  @details
  This function unpacks the Rx Measure command. The unpack process will result on two structure - one containing
  the list of devices which needs to be dropped by the tech; and other containining the list of devices and
  configuration data to be added and reconfigured. Some rules assumed during unpacking are as follows
  #- List of properties are grouped into different groups which is delimited by Rx or Tx carrier property
  #- Each group cannot have more than one entries of "same" property
  #- The devices not present in the new command config data as compared to previous command config data will be
     assumed to the devices to be dropped.
 
  @param num_of_props
  Number of properties in teh property list
 
  @param property_list
  Pointer to the property list
 
  @param unpack_data
  Structrue where the unpack data will be stored
 
  @param last_unpack_data
  Pointer last unpack data used to diff with the new command config to generate the drop list
 
  @param subscriber
  Subscriber number
 
  @param debug_mode
  Flag indicating the debug mode
 
  @return
  Error code generated by this function. The unpack data is valid only if the error code is 0.
*/
static ftm_rf_test_field_error_code_mask_type
rx_measure_req_default_unpack_cb(uint32 num_of_props,
                           ftm_rf_test_property_data_type * property_list,
                           void* command_data,
                           boolean debug_mode )
{
  ftm_rf_test_field_error_code_mask_type error_code = 0;
  ftm_rf_test_property_data_type *prop_ptr = NULL;
  uint32 prop_index = 0;
  rfm_device_enum_type device = RFM_INVALID_DEVICE;

  /*------------------------------------------------------------------------------------------------------------------*/
  /* Variables used to temporarily store the unpacked data; until they are pushed to the unpack structure. */
  /* These variables must be reset to default value before starting to unpack a property group. */
  /*------------------------------------------------------------------------------------------------------------------*/
  ftm_rf_test_rx_measure_unpacked_data_t* curr_unpacked_data= NULL;
  ftm_rf_test_rx_measure_mode_data_t* rx_measure_data = (ftm_rf_test_rx_measure_mode_data_t*)command_data;

  if ( property_list == NULL || rx_measure_data == NULL )
  {
    FTM_MSG( FTM_HIGH, "[FTM.RFTEST][RX_MEASURE]rx_measure_unpack: Null param " );
    error_code |= (1<<FTM_RF_TEST_RX_EC_ERROR);
    return error_code;
  } /* if ( ( property_list == NULL ) || ( rx_measure_data == NULL ) ) */

  rx_measure_data->unpacked_data = modem_mem_realloc(
                     rx_measure_data->unpacked_data,
                     (rx_measure_data->unpacked_data_num+1)* sizeof(ftm_rf_test_rx_measure_unpacked_data_t),
                     MODEM_MEM_CLIENT_RFA );

  if ( rx_measure_data->unpacked_data == NULL )
  {
    FTM_MSG( FTM_ERROR, "[FTM.RFTEST][RX_MEASURE]rx_measure_unpack: failed to grow unpacked_data " );
    error_code |= (1<<FTM_RF_TEST_RX_EC_ERROR);
    return error_code;
  }

  curr_unpacked_data = &(rx_measure_data->unpacked_data[rx_measure_data->unpacked_data_num]);

  memset( curr_unpacked_data , 0 , sizeof(ftm_rf_test_rx_measure_unpacked_data_t) );
 
  rx_measure_data->unpacked_data_num++;

  if ( debug_mode == TRUE )
  {
    FTM_MSG_3(FTM_MED,"ftm_rf_test_rx_measure_process_action: EXTRACT Measurement [%d][@0x%08x]FROM[0x%08x]",
                      rx_measure_data->unpacked_data_num,
                      rx_measure_data->unpacked_data,
                      curr_unpacked_data );
  }

  /*------------------------------------------------------------------------------------------------------------------*/
  /* Reset the local variables to store the unpackes data for each property group */  
  /*------------------------------------------------------------------------------------------------------------------*/
  /*------------------------------------------------------------------------------------------------------------------*/

  /* Initialize Propert pointer */
  prop_ptr = property_list;

  /*------------------------------------------------------------------------------------------------------------------*/
  /* Populate the Device to Measure list */
  /*------------------------------------------------------------------------------------------------------------------*/
  /* Continue, if the number if properties is not 0 */
  if ( num_of_props != 0 )
  {
    /* Loop thrrough the number of properties. Loop is allowed to till num_of_props; to latch the last propert group */
    for ( prop_index = 0; prop_index < num_of_props; prop_index++ )
    {
      /* If the debug mode is enabled, then print property information */
      if ( debug_mode == TRUE )
      {
        FTM_MSG_3( FTM_HIGH, "[FTM.RFTEST][RX_MEASURE][UNPACK]: [%2d][Property %3d][Value %8d]", 
                   prop_index, prop_ptr->property_type, prop_ptr->property_val );
      } /* if ( debug_mode == TRUE ) */

      switch ( prop_ptr->property_type )
      {
      case FTM_RX_MEASURE_PROP_RFM_DEVICE:           
        device = prop_ptr->property_val;
        if ( device < RFM_MAX_WAN_DEVICES )
        {
          curr_unpacked_data->input.device = device;
          curr_unpacked_data->response_prop_mask[FTM_RX_MEASURE_PROP_RFM_DEVICE] = TRUE;

        } /* if (  rfm_device_pri < RFM_MAX_WAN_DEVICES  ) */
        else
        {
          FTM_MSG(FTM_ERROR,"ftm_rf_test_rx_measure_unpack_callback: invalid device");
        }
        break;

      case FTM_RX_MEASURE_PROP_RX_CARRIER:
        curr_unpacked_data->input.carrier = prop_ptr->property_val;
        curr_unpacked_data->response_prop_mask[FTM_RX_MEASURE_PROP_RX_CARRIER] = TRUE;
        break;

      case FTM_RX_MEASURE_PROP_EXPECTED_AGC:
        curr_unpacked_data->input.expected_agc = prop_ptr->property_val;
        break;

      case FTM_RX_MEASURE_PROP_AGC:
        curr_unpacked_data->response_prop_mask[FTM_RX_MEASURE_PROP_AGC] = TRUE;
        break;

      case FTM_RX_MEASURE_PROP_LNA_GAIN_STATE:
        curr_unpacked_data->response_prop_mask[FTM_RX_MEASURE_PROP_LNA_GAIN_STATE] = TRUE;
        break;

      default:
        FTM_MSG_1(FTM_ERROR,"[FTM.RFTEST][RX_MEASURE][UNPACK]: Unrecongnized Property Type %d",  
                  prop_ptr->property_type );
        break;
      } /* switch ( prop_ptr->property_type ) */
    
      /* Increment the poperty pointer */
      prop_ptr++;
    } /* for ( prop_index = 0; prop_index < num_of_props; prop_index++ ) */
  } /* if ( num_of_props != 0 ) */
 
  /*------------------------------------------------------------------------------------------------------------------*/
  /* Error handling */
  /*------------------------------------------------------------------------------------------------------------------*/

  /* If error code is not zero, then clear the unpack data */
  if ( error_code != 0 )
  {
    /* Clear memory for unpack data */
    FTM_MSG_1( FTM_ERROR, "[FTM.RFTEST][RX_MEASURE]: [ErrorCode 0x%x] Clearing unpack data",
               error_code );
  } /* if ( error_code != 0 ) */

  return error_code;

} /* ftm_rf_test_rx_measure_process_action */

/*--------------------------------------------------------------------------------------------------------------------*/
/*!
  @brief
  Call back API to allow common unpacker to identify delimter from property list 
*/
static boolean
rx_measure_req_default_delimiter_cb
(
   uint32 property_type
)
{
  boolean is_delimiter = FALSE;

  if ( property_type == FTM_RX_MEASURE_PROP_RX_CARRIER )
  {
    is_delimiter = TRUE;
  }
  else
  {
    is_delimiter = FALSE;
  }
  
  return is_delimiter;
}


/*--------------------------------------------------------------------------------------------------------------------*/
/*!
  @brief
  Utility API to repack measurement result to property list using default format.
  Future variations can be based on this API.
*/
static boolean
rx_measure_rsp_default_repack_helper
(
  uint32 unpacked_measurement_num,
  ftm_rf_test_rx_measure_unpacked_data_t* unpacked_measurement_list,
  ftm_rf_test_rx_measure_rsp_payload_type* repacked_payload,
  uint32* repacked_payload_size,
  boolean debug_mode
)
{
  uint32 meas_idx;
  boolean ret_val = TRUE;
  
  /* Populate Payload */
  for ( meas_idx = 0; meas_idx < unpacked_measurement_num; meas_idx ++ )
  {
    ftm_rf_test_rx_measure_property_type prop_type;

    for ( prop_type = FTM_RF_MEASURE_PROP_UNASSIGNED; 
          prop_type < FTM_RX_MEASURE_PROP_NUM; prop_type++ )
    {
      if ( unpacked_measurement_list[meas_idx].response_prop_mask[prop_type] == TRUE ) 
      {
        uint32 curr_property_index = repacked_payload->number_of_properties;

        /* Increment number of total properties */
        repacked_payload->number_of_properties++;

        /* Grow memory for number of total properties */
        repacked_payload->result_prop_list = modem_mem_realloc( 
           repacked_payload->result_prop_list, 
           repacked_payload->number_of_properties*sizeof(ftm_rf_test_property_data_type), 
           MODEM_MEM_CLIENT_RFA);      

        if ( repacked_payload->result_prop_list == NULL )
        {
          ERR_FATAL("[FTM.RFTEST][RX_MEASURE] NULL REALLOC POINTER!",0,0,0);        
        }

        memset(&(repacked_payload->result_prop_list[curr_property_index]), 
               0, sizeof(ftm_rf_test_property_data_type)); 

        repacked_payload->result_prop_list[curr_property_index].property_type = prop_type;

        switch ( prop_type )
        {
        case FTM_RX_MEASURE_PROP_RX_CARRIER:
          repacked_payload->result_prop_list[curr_property_index].property_val = 
            unpacked_measurement_list[meas_idx].input.carrier;     
          break;

        case FTM_RX_MEASURE_PROP_RFM_DEVICE:       
          repacked_payload->result_prop_list[curr_property_index].property_val = 
            unpacked_measurement_list[meas_idx].input.device;     
          break;

        case FTM_RX_MEASURE_PROP_AGC:
          repacked_payload->result_prop_list[curr_property_index].property_val = 
            unpacked_measurement_list[meas_idx].output.rxagc;     
          break;

        case FTM_RX_MEASURE_PROP_LNA_GAIN_STATE:
          repacked_payload->result_prop_list[curr_property_index].property_val = 
            unpacked_measurement_list[meas_idx].output.lna_gain_state; 
          break;

        default:
          FTM_MSG_1(FTM_ERROR,"[FTM.RFTEST][RX_MEASURE][REPACK]: Unexpected REPACK Property %d"
                              "NO Value populated %d",  prop_type );
          break;        
        }

        if ( debug_mode == TRUE )
        {
          FTM_MSG_4(FTM_MED, "[FTM.RFTEST][RX_MEASURE][REPACK]: "
                               "[%3d][PROP Type %2d][PROP Value %5d][PROP Value 0x%8x]", 
                     repacked_payload->number_of_properties,
                     repacked_payload->result_prop_list[curr_property_index].property_type,
                     repacked_payload->result_prop_list[curr_property_index].property_val,
                     repacked_payload->result_prop_list[curr_property_index].property_val );
        }
      }/* if ( unpacked_measurement_list[meas_idx].rsp_property_list[prop_idx] == TRUE )  */
      else
      {
        /* Skip packing for non marked property */
        if ( debug_mode == TRUE )
        { 
          FTM_MSG_1(FTM_MED, "[FTM.RFTEST][RX_MEASURE][REPACK]: [PROP TYPE %d] NOT PACKED", prop_type );
        }
      }
    }/* for ( prop_idx = 0; prop_idx < FTM_RX_MEASURE_PROP_NUM; prop_idx++ ) */
  }/* for ( meas_idx = 0; meas_idx < unpacked_measurement_num; meas_idx ++ ) */

  /* Calculate Payload size: Error Code + Num_of_properties + Measurement Data */
  *repacked_payload_size = 
    repacked_payload->number_of_properties*sizeof(ftm_rf_test_property_data_type) ;     

  if ( debug_mode == TRUE ) 
  {
    FTM_MSG_2(FTM_MED,"[FTM.RFTEST][RX_MEASURE][REPACK][TOTAL PAYLOAD SIZE %d][FOR %d PROPS]",
              *repacked_payload_size, repacked_payload->number_of_properties);
  }

  return ret_val;

}/* rx_measure_rsp_default_repack_cb */



/*====================================================================================================================*/
/*!
  @name Repack Rx Measure Data from Default format to payload property format.
  Future development for other formats can be based on this API.

  @brief
  Functions to handle Rx Measure command
*/
/*! @{ */

boolean
rx_measure_rsp_default_response_helper
(
  ftm_rf_test_reponse_data_type* response_allocator_data,
  ftm_rf_test_rx_measure_rsp_payload_type* repacked_payload,
  uint32 repacked_payload_size
)
{
  boolean ret_val = TRUE;
  ftm_rf_test_rx_measure_rsp_payload_type* allocated_rsp;

  if ( repacked_payload == NULL || response_allocator_data == NULL )
  {
    FTM_MSG(FTM_ERROR,"[FTM.RFTEST][RSP][REPACK]: NULL POINTER!");
    ret_val = FALSE;
  }
  else
  {
    /* Create Response packet */
    allocated_rsp = (ftm_rf_test_rx_measure_rsp_payload_type*)response_allocator_data->
             alloc_response_fp( response_allocator_data, 
                                repacked_payload_size+sizeof(repacked_payload->error_code)+sizeof(repacked_payload->number_of_properties));

    /* NULL pointer check */
    if ( allocated_rsp != NULL )
    {
      /* Populate response packet */
      allocated_rsp->error_code = repacked_payload->error_code;
      allocated_rsp->number_of_properties = repacked_payload->number_of_properties;
      /* Mem copy the property list to right after num_of_properties */      
      memscpy( &(allocated_rsp->result_prop_list), repacked_payload_size, repacked_payload->result_prop_list, repacked_payload_size );
    } /* if ( rsp_payload != NULL ) */
    else
    {
      ret_val = FALSE;
      FTM_MSG( FTM_ERROR, "[FTM.RFTEST][RSP][REPACK]: Response malloc failure" );
    } /* if !( rsp_payload != NULL ) */
  }

  return ret_val; 
}/* rx_measure_rsp_default_response_helper */

/*! @} */

/*--------------------------------------------------------------------------------------------------------------------*/
/*!
  @brief
  Measures Rx parameters
 
  @details
  This function is the handler function to configure Radio to given mode of operation. When a Rx Measure command is
  received, it is broken into two parts
  #- RF devices that are no longer used/removed
  #- RF devices that are currently used and being re-tuned /  RF devices that are newly used and must be woken up
 
  Each technology is expected to reconfigure their driver/devices in this order. Devices which are no longer used after
  a RX_MEASURE are returned to the system for other subscriptions to use in the future. A RX_MEASURE command 
  received for a subscription+tech which is currently configured and contains no carriers means to release all resources
 
  @param command_data
  Pointer to the structure containing command specific dispatch command
 
  @return
  Response Packet for Rx Measure command
*/
static boolean
rx_measure_handler
(
  struct ftm_rf_test_command_data_t *command
)
{
  boolean ret_val = TRUE;
  ftm_rf_test_rx_measure_command_data_t *command_data;
  ftm_rf_test_req_type *req_data;
  ftm_rf_test_rx_measure_rsp_payload_type *rsp_payload;
  ftm_rf_test_field_error_code_mask_type error_code = 0;
  ftm_rf_test_field_error_code_mask_type ec_unpack = 0;
  ftm_rf_test_field_error_code_mask_type ec_tech_cb = 0;
  ftm_rf_test_rx_measure_mode_data_t* rx_measure_data;
  uint32 meas_idx = 0;
  uint32 payload_size = 0;
  uint32 measurement_results_size = 0;
  boolean tech_override = FALSE;

  /* Param validation */
  if ( ( command == NULL ) || ( command->dispatch_data == NULL ) ||
       ( command->diag_request_data == NULL ) )
  {
    FTM_MSG( FTM_ERROR, "[FTM.RFTEST][RX_MEASURE]radio_config_handler: Null param" );
    ret_val = FALSE;
  } /* if ( ( command_instance == NULL ) || ( command_instance->sw_command == NULL ) ||
       ( command_instance->diag_request_data == NULL ) ) */

  if ( ret_val == TRUE )
  {
    /* Param validation */
    if ( command->technology >= RFM_NUM_MODES )
    {
      FTM_MSG_1( FTM_ERROR, "[FTM.RFTEST][RX_MEASURE]radio_config_handler: Bad Tech %d",
                 command->technology);
      ret_val = FALSE;
    } /* if ( command_instance->technology >= RFM_NUM_MODES ) */
  }

  if ( ret_val == TRUE )
  {  
    /* Get RX Measure Data */
    command_data = (ftm_rf_test_rx_measure_command_data_t*)(command->dispatch_data->command_data);

    /* Get Diag Request Data */
    req_data = command->diag_request_data;

    /* Make sure that the Radio config Data and diag request data is not NULL, before proceeding */
    if ( ( command_data == NULL ) || ( req_data == NULL) )
    { 
      FTM_MSG( FTM_ERROR, "[FTM.RFTEST][RX_MEASURE]rx_measure_handler: Null RC / REQ Data" );
      error_code |= (1<<FTM_RF_TEST_RX_EC_ERROR);
      ret_val = FALSE;
    } /* if !( ( radio_config_data != NULL ) && ( req_data != NULL ) ) */
  }

  if ( ret_val == TRUE ) 
  {
    rx_measure_data = &(command_data->mode_data[command->technology]); 

    /* reset all data structs before populating unpacked data and payload */

    if ( rx_measure_data->rsp_payload_data.result_prop_list != NULL )
    {
      modem_mem_free( rx_measure_data->rsp_payload_data.result_prop_list, MODEM_MEM_CLIENT_RFA );
    }

    if ( rx_measure_data->unpacked_data != NULL )
    {
      modem_mem_free( rx_measure_data->unpacked_data, MODEM_MEM_CLIENT_RFA );
    }

    rx_measure_data->unpacked_data_num = 0;
    rx_measure_data->unpacked_data = NULL;
    rx_measure_data->rsp_payload_data.error_code = 0;
    rx_measure_data->rsp_payload_data.number_of_properties = 0;
    rx_measure_data->rsp_payload_data.result_prop_list = NULL;
  
    /* Tech has the option to override the common unpack & dispatch. Tech has to allocate the response using the
    rsp_alloc_cb provided */        
    if ( rx_measure_data->override_callback_fp != NULL )
    {
      ftm_rf_test_rx_measure_tech_override_data_type tech_override_data;

      memset(&tech_override_data, 0, sizeof(ftm_rf_test_rx_measure_tech_override_data_type) );

      tech_override_data.req_prop_num = req_data->payload.num_of_properties;
      tech_override_data.req_prop_list = &(req_data->payload.property_data);
      tech_override_data.rsp_allocator_cb_data = &(command->response_data);
      tech_override_data.rsp_alloc_cb = rx_measure_rsp_default_response_helper;
      
      ec_tech_cb = rx_measure_data->override_callback_fp( &tech_override_data );

      tech_override = TRUE;
    }
    else /* if ( rx_measure_data->override_callback_fp == NULL )*/
    {
      /* Unpack data */
      ec_unpack = ftm_rf_test_unpack_property_list( 
                                        req_data->payload.num_of_properties, 
                                        &(req_data->payload.property_data),
                                        rx_measure_data,
                                        TRUE,
                                        rx_measure_req_default_unpack_cb,
                                        rx_measure_req_default_delimiter_cb);
      
      /* Continue if the UNPACK error code is 0 */
      if ( ec_unpack == 0 )
      {
        /* Call Tech callback */
        if ( rx_measure_data->callback_fp != NULL )
        {
          ec_tech_cb = rx_measure_data->callback_fp( rx_measure_data->unpacked_data, 
                                                     rx_measure_data->unpacked_data_num );

        } /* if ( rx_measure_data->mode_data[command_instance->technology].callback_fp != NULL ) */
        else
        {
          ec_tech_cb = (1<<FTM_RF_TEST_RX_EC_SUCCESS);
        } /* if ! ( rx_measure_data->mode_data[command_instance->technology].callback_fp != NULL ) */
        
      } /* if ( ec_unpack == 0 ) */
      else
      {
        FTM_MSG( FTM_ERROR, "[FTM.RFTEST][RX_MEASURE]rx_measure_handler: Unpack failure" );
      }

    }/* if ( rx_measure_data->override_callback_fp == NULL ) */

    /* Accumulate error code */
    error_code |= ec_unpack;
    error_code |= ec_tech_cb;

    if ( error_code != 0 )
    {
      ret_val = FALSE;
    } /* if ( error_code != 0 ) */

    FTM_MSG_1( FTM_ERROR, "[FTM.RFTEST][RX_MEASURE][DISPATCH]: [ErrorCode 0x%x]", error_code );
  }

  /* Populate respoonse payload, if tech did not override common unpack & dispatch */
  if ( ret_val == TRUE && tech_override == FALSE )
  {
    uint32 payload_size = 0;

    ret_val &= rx_measure_rsp_default_repack_helper( rx_measure_data->unpacked_data_num,
                                                 rx_measure_data->unpacked_data,
                                                 &(rx_measure_data->rsp_payload_data),
                                                 &payload_size,                                                
                                                 TRUE);

    rx_measure_data->rsp_payload_data.error_code = error_code;

    ret_val = rx_measure_rsp_default_response_helper( &(command->response_data),
                                                &(rx_measure_data->rsp_payload_data),
                                                payload_size );

  }/* if ( ret_val == TRUE && tech_overriden == FALSE )*/
  
  return ret_val; 

} /* radio_config_handler */

/*! @} */

/*====================================================================================================================*/
/*!
  @name Init

  @brief
  Functions to handle Rx Measure command initialization for registration
*/
/*! @{ */

/*--------------------------------------------------------------------------------------------------------------------*/
/*!
  @brief
  Initialize Rx Measure Command handler module
 
  @details
  This function initializes the Rx Measureure command module. Initialization includes, allocating the memory for
  house keeping data for Rx Measure command and populating the command handler function
 
  @param dispatch_data
  Poitner to dispatch data specific to Rx Measure command
 
  @return
  Flag indicating the status of Rx Measure initialization
*/
boolean
ftm_rf_test_rx_measure_init
(
  ftm_rf_test_command_dispatch_data_t *dispatch_data
)
{
  boolean ret_val = TRUE;

  /* Param Validation */
  if ( dispatch_data == NULL )
  {
    FTM_MSG( FTM_ERROR, "[FTM.RFTEST][RX_MEASURE]ftm_rf_test_rx_measure_init: Null param" );
    return FALSE;
  } /* if ( dispatch_data == NULL ) */

  /* Allocate memory for Rx Measure command handler */ 

  if ( dispatch_data->command_data == NULL )
  {
    dispatch_data->command_data = 
      (void*)modem_mem_alloc( sizeof(ftm_rf_test_rx_measure_command_data_t), MODEM_MEM_CLIENT_RFA );
  } /* if ( dispatch_data->command_data == NULL ) */

  if ( dispatch_data->command_data != NULL )
  {
    memset( dispatch_data->command_data, 0, sizeof(ftm_rf_test_rx_measure_command_data_t) );
    dispatch_data->command_handler = rx_measure_handler;
  } /* if ( dispatch_data->command_data != NULL ) */
  else
  {
    FTM_MSG( FTM_ERROR, "[FTM.RFTEST][RX_MEASURE]ftm_rf_test_rx_measure_init: Malloc failure" );
    ret_val = FALSE;
  } /* if !( dispatch_data->command_data != NULL ) */

  return ret_val;

} /* ftm_rf_test_rx_measure_init */

/*--------------------------------------------------------------------------------------------------------------------*/
/*!
  @brief
  DeInitialize Rx Measure Command handler module
 
  @details
  This function deinitializes the Rx Measureure command module. DeInitialization includes, deallocating the memory for
  house keeping data for Rx Measure command
 
  @param dispatch_data
  Poitner to dispatch data specific to Rx Measure command
 
  @return
  Flag indicating the status of Rx Measure deinitialization
*/
boolean
ftm_rf_test_rx_measure_deinit
(
  ftm_rf_test_command_dispatch_data_t *dispatch_data
)
{
  boolean ret_val = TRUE;

  /* Param Validation */
  if ( dispatch_data == NULL )
  {
    FTM_MSG( FTM_ERROR, "[FTM.RFTEST][RADIO_CONFIG]ftm_rf_test_radio_config_deinit: Null param" );
    return FALSE;
  } /* if ( dispatch_data == NULL ) */

  ftm_rf_test_rx_measure_command_data_t * rx_measure_data = 
    (ftm_rf_test_rx_measure_command_data_t *)dispatch_data->command_data;

  /* Free memory allocated for Radio Config command handler */ 
  if ( rx_measure_data != NULL )
  {
    uint8 mode_idx = 0;
    for ( mode_idx = 0; mode_idx < RFM_NUM_MODES; mode_idx ++ )
    {
      if( rx_measure_data->mode_data[mode_idx].unpacked_data != NULL )
      {
        modem_mem_free( rx_measure_data->mode_data[mode_idx].unpacked_data, MODEM_MEM_CLIENT_RFA );
      }

      if ( rx_measure_data->mode_data[mode_idx].rsp_payload_data.result_prop_list != NULL )
      {
        modem_mem_free( rx_measure_data->mode_data[mode_idx].rsp_payload_data.result_prop_list, MODEM_MEM_CLIENT_RFA );
      }
    }

    modem_mem_free( rx_measure_data , MODEM_MEM_CLIENT_RFA );

    dispatch_data->command_data = NULL;
  } /* if ( dispatch_data->command_data != NULL ) */

  dispatch_data->command_handler = NULL;

  return ret_val;

} /* ftm_rf_test_rx_measure_deinit */

/*! @} */

/*====================================================================================================================*/
/*!
  @name Tech Registration

  @brief
  Interface for technologies to perform callback registration with the FTM RF Test module for Rx Measure command
*/
/*! @{ */


/*--------------------------------------------------------------------------------------------------------------------*/
/*!
  @brief
  Register Tech callback
 
  @details
  This function is used to register a tech callback function for Rx Measure command
 
  @param technology
  Technology for which the callback is to be registered
 
  @param callback_fp
  Callback funtion pointer to be registered
 
  @return
  Flag indicating the status of callback registration
*/
boolean
ftm_rf_test_rx_measure_register_tech_cb
(
  rfm_mode_enum_type technology,
  ftm_rf_test_rx_measure_tech_callback_fp callback_fp
)
{
  ftm_rf_test_command_dispatch_data_t *dispatch_data;
  ftm_rf_test_rx_measure_command_data_t *rx_measure_data;

  dispatch_data = ftm_rf_test_get_dispatch_data( FTM_RF_TEST_CMD_RX_MEASURE );

  /* Param validation */
  if ( dispatch_data == NULL )
  {
    FTM_MSG( FTM_ERROR, "[FTM.RFTEST][RX_MEASURE]ftm_rf_test_rx_measure_register_tech_cb: Null param" );
    return FALSE;
  } /* if ( dispatch_data == NULL ) ) */

  /* Param validation */
  if ( technology >= RFM_NUM_MODES )
  {
    FTM_MSG_1( FTM_ERROR, "[FTM.RFTEST][RX_MEASURE]ftm_rf_test_rx_measure_register_tech_cb: Bad Tech %d",
               technology);
    return FALSE;
  } /* if ( technology >= RFM_NUM_MODES ) */

  rx_measure_data = (ftm_rf_test_rx_measure_command_data_t*)dispatch_data->command_data;

  if ( rx_measure_data == NULL) 
  {
    FTM_MSG( FTM_ERROR, "[FTM.RFTEST][RX_MEASURE]ftm_rf_test_rx_measure_register_tech_cb: NULL rx_measure data %d" );
    return FALSE;
  }
  /* Save callback function */
  rx_measure_data->mode_data[technology].callback_fp = callback_fp;

  FTM_MSG_1( FTM_HIGH, "[FTM.RFTEST][RX_MEASURE]ftm_rf_test_rx_measure_register_tech_cb: Registered for Tech %d",
             technology);

  return TRUE;

} /* ftm_rf_test_rx_measure_register_tech_cb */


/*--------------------------------------------------------------------------------------------------------------------*/
/*!
  @brief
  Register Tech Override callback
 
  @details
  This function is used to register a tech callback function for Rx Measure command
 
  @param technology
  Technology for which the callback is to be registered
 
  @param callback_fp
  Callback funtion pointer to be registered
 
  @return
  Flag indicating the status of callback registration
*/
boolean
ftm_rf_test_rx_measure_register_tech_override_cb
(
  rfm_mode_enum_type technology,
  ftm_rf_test_rx_measure_tech_override_callback_fp override_callback_fp
)
{
  ftm_rf_test_command_dispatch_data_t *dispatch_data;
  ftm_rf_test_rx_measure_command_data_t *rx_measure_data;

  dispatch_data = ftm_rf_test_get_dispatch_data( FTM_RF_TEST_CMD_RX_MEASURE );

  /* Param validation */
  if ( dispatch_data == NULL )
  {
    FTM_MSG( FTM_ERROR, "[FTM.RFTEST][RX_MEASURE]ftm_rf_test_rx_measure_register_tech_override_cb: Null param" );
    return FALSE;
  } /* if ( dispatch_data == NULL ) ) */

  /* Param validation */
  if ( technology >= RFM_NUM_MODES )
  {
    FTM_MSG_1( FTM_ERROR, "[FTM.RFTEST][RX_MEASURE]ftm_rf_test_rx_measure_register_tech_override_cb: Bad Tech %d",
               technology);
    return FALSE;
  } /* if ( technology >= RFM_NUM_MODES ) */

  rx_measure_data = (ftm_rf_test_rx_measure_command_data_t*)dispatch_data->command_data;

  if ( rx_measure_data == NULL) 
  {
    FTM_MSG( FTM_ERROR, "[FTM.RFTEST][RX_MEASURE]ftm_rf_test_rx_measure_register_tech_override_cb: NULL rx_measure data %d" );
    return FALSE;
  }
  /* Save callback function */
  rx_measure_data->mode_data[technology].override_callback_fp = override_callback_fp;

  FTM_MSG_1( FTM_HIGH, "[FTM.RFTEST][RX_MEASURE]ftm_rf_test_rx_measure_register_tech_override_cb: Registered for Tech %d",
             technology);

  return TRUE;

} /* ftm_rf_test_rx_measure_register_tech_cb */

/*! @} */

/*====================================================================================================================*/
/*!
  @name Query

  @brief
  Functions to handle Rx Measure command
*/
/*! @{ */

/*! @} */

/*! @} */ /* FTM_TEST_TOOLS_CMD_RX_MEASURE */


