/*!
  @file
  ftm_rf_test_tx_control.c

  @brief
  Common framework to perform radio test in FTM mode
*/

/*======================================================================================================================

  Copyright (c) 2015 Qualcomm Technologies Incorporated. All Rights Reserved

  Qualcomm Proprietary

  Export of this technology or software is regulated by the U.S. Government.
  Diversion contrary to U.S. law prohibited.

  All ideas, data and information contained in or disclosed by this document are confidential 
  and proprietary information of Qualcomm Technologies Incorporated and all rights therein are 
  expressly reserved. By accepting this material the recipient agrees that this material and the 
  information contained therein are held in confidence and in trust and will not be used, copied, 
  reproduced in whole or in part, nor its contents revealed in any manner to others without the 
  express written permission of Qualcomm Technologies Incorporated.

======================================================================================================================*/

/*======================================================================================================================

                        EDIT HISTORY FOR MODULE

  This section contains comments describing changes made to the module.
  Notice that changes are listed in reverse chronological order.

  $Header: //components/rel/rfa.mpss/4.11/rf/common/ftm/src/ftm_rf_test_tx_control.c#1 $

when       who     what, where, why
--------   ---     -----------------------------------------------------------------------------------------------------
08/10/15   zhw     Initial Release

======================================================================================================================*/
#include "comdef.h"
#include "ftm_rf_test_interface.h"
#include "ftm_rf_test_tx_control.h"
#include "ftm_msg.h"
#include "ftm_common_control.h"
#include "modem_mem.h"
#include "stringl.h"
#include "rfcommon_math.h"

/*====================================================================================================================*/
/*!
  @addtogroup FTM_TEST_TOOLS_TX_CONTROL
  @{
*/

/*====================================================================================================================*/
/*!
  @name Unpack

  @brief
  Functions to manage TX CONTROL command unpack
*/
/*! @{ */

/*--------------------------------------------------------------------------------------------------------------------*/
/*!
  @brief
  Unpack TX CONTROL command packet to default format
 
  @details
  This function unpacks the TX CONTROL command. The unpack process will result on two structure - one containing
  the list of devices which needs to be dropped by the tech; and other containining the list of devices and
  configuration data to be added and reconfigured. Some rules assumed during unpacking are as follows
  #- List of properties are grouped into different groups which is delimited by Rx or Tx carrier property
  #- Each group cannot have more than one entries of "same" property
  #- The devices not present in the new command config data as compared to previous command config data will be
     assumed to the devices to be dropped.
 
  @param num_of_props
  Number of properties in teh property list
 
  @param property_list
  Pointer to the property list
 
  @param unpack_data
  Structrue where the unpack data will be stored
 
  @param last_unpack_data
  Pointer last unpack data used to diff with the new command config to generate the drop list
 
  @param subscriber
  Subscriber number
 
  @param debug_mode
  Flag indicating the debug mode
 
  @return
  Error code generated by this function. The unpack data is valid only if the error code is 0.
*/
static ftm_rf_test_field_error_code_mask_type
tx_control_req_default_unpack_cb(uint32 num_of_props,
                                 ftm_rf_test_property_data_type * property_list,
                                 void* command_data,
                                 boolean debug_mode )
{
  ftm_rf_test_field_error_code_mask_type error_code = 0;
  ftm_rf_test_property_data_type *prop_ptr = NULL;
  uint32 prop_index = 0;
  rfm_device_enum_type device = RFM_INVALID_DEVICE;

  /*------------------------------------------------------------------------------------------------------------------*/
  /* Variables used to temporarily store the unpacked data; until they are pushed to the unpack structure. */
  /* These variables must be reset to default value before starting to unpack a property group. */
  /*------------------------------------------------------------------------------------------------------------------*/
  ftm_rf_test_tx_control_unpacked_data_t* curr_unpacked_data= NULL;
  ftm_rf_test_tx_control_mode_data_t* tx_control_data = (ftm_rf_test_tx_control_mode_data_t*)command_data;

  if ( property_list == NULL || tx_control_data == NULL )
  {
    FTM_MSG( FTM_HIGH, "[FTM.RFTEST][TX_CONTROL]tx_control_unpack: Null param " );
    error_code |= (1<<FTM_RF_TEST_TX_EC_ERROR);
    return error_code;
  } /* if ( ( property_list == NULL ) || ( tx_control_data == NULL ) ) */

  tx_control_data->unpacked_data = modem_mem_realloc(
                     tx_control_data->unpacked_data,
                     (tx_control_data->unpacked_data_num+1)* sizeof(ftm_rf_test_tx_control_unpacked_data_t),
                     MODEM_MEM_CLIENT_RFA );

  if ( tx_control_data->unpacked_data == NULL )
  {
    FTM_MSG( FTM_ERROR, "[FTM.RFTEST][TX_CONTROL]tx_control_unpack: failed to grow unpacked_data " );
    error_code |= (1<<FTM_RF_TEST_TX_EC_ERROR);
    return error_code;
  }

  curr_unpacked_data = &(tx_control_data->unpacked_data[tx_control_data->unpacked_data_num]);

  memset( curr_unpacked_data , 0 , sizeof(ftm_rf_test_tx_control_unpacked_data_t) );
 
  tx_control_data->unpacked_data_num++;

  if ( debug_mode == TRUE )
  {
    FTM_MSG_3(FTM_MED,"ftm_rf_test_tx_control_process_action: EXTRACT ACTION [%d][@0x%08x]FROM[0x%08x]",
                      tx_control_data->unpacked_data_num,
                      tx_control_data->unpacked_data,
                      curr_unpacked_data );
  }

  /*------------------------------------------------------------------------------------------------------------------*/
  /* Reset the local variables to store the unpackes data for each property group */  
  /*------------------------------------------------------------------------------------------------------------------*/
  /*------------------------------------------------------------------------------------------------------------------*/

  /* Initialize Propert pointer */
  prop_ptr = property_list;

  /*------------------------------------------------------------------------------------------------------------------*/
  /* Populate the Device to Measure list */
  /*------------------------------------------------------------------------------------------------------------------*/
  /* Continue, if the number if properties is not 0 */
  if ( num_of_props != 0 )
  {
    /* Loop thrrough the number of properties. Loop is allowed to till num_of_props; to latch the last propert group */
    for ( prop_index = 0; prop_index < num_of_props; prop_index++ )
    {
      /* If the debug mode is enabled, then print property information */
      if ( debug_mode == TRUE )
      {
        FTM_MSG_3( FTM_HIGH, "[FTM.RFTEST][TX_CONTROL][UNPACK]: [%2d][Property %3d][Value %8d]", 
                   prop_index, prop_ptr->property_type, prop_ptr->property_val );
      } /* if ( debug_mode == TRUE ) */

      switch ( prop_ptr->property_type )
      {
      case FTM_TX_CONTROL_PROP_RFM_DEVICE:           
        device = prop_ptr->property_val;
        if ( device < RFM_MAX_WAN_DEVICES )
        {
          curr_unpacked_data->input.device = device;          
        } /* if (  rfm_device_pri < RFM_MAX_WAN_DEVICES  ) */
        else
        {
          FTM_MSG(FTM_ERROR,"ftm_rf_test_tx_control_unpack_callback: invalid device");
        }
        break;

      case FTM_TX_CONTROL_PROP_TX_CARRIER:
        curr_unpacked_data->input.carrier = prop_ptr->property_val;        
        break;

      case FTM_TX_CONTROL_PROP_TX_ACTION:
        curr_unpacked_data->input.tx_action = prop_ptr->property_val;
        break;

      case FTM_TX_CONTROL_PROP_TX_POWER:
        curr_unpacked_data->input.tx_power = prop_ptr->property_val;        
        break;

      case FTM_TX_CONTROL_PROP_RB_CONFIG:
        curr_unpacked_data->input.rb_config = prop_ptr->property_val;        
        break;

      default:
        FTM_MSG_1(FTM_ERROR,"[FTM.RFTEST][TX_CONTROL][UNPACK]: Unrecongnized Property Type %d",  
                  prop_ptr->property_type );
        break;
      } /* switch ( prop_ptr->property_type ) */
    
      /* Increment the poperty pointer */
      prop_ptr++;
    } /* for ( prop_index = 0; prop_index < num_of_props; prop_index++ ) */
  } /* if ( num_of_props != 0 ) */
 
  /*------------------------------------------------------------------------------------------------------------------*/
  /* Error handling */
  /*------------------------------------------------------------------------------------------------------------------*/

  /* If error code is not zero, then clear the unpack data */
  if ( error_code != 0 )
  {
    /* Clear memory for unpack data */
    FTM_MSG_1( FTM_ERROR, "[FTM.RFTEST][TX_CONTROL]: [ErrorCode 0x%x] Clearing unpack data",
               error_code );
  } /* if ( error_code != 0 ) */

  return error_code;

} /* tx_control_req_default_unpack_cb */

/*--------------------------------------------------------------------------------------------------------------------*/
/*!
  @brief
  Call back API to allow common unpacker to identify delimter from property list 
*/
static boolean
tx_control_req_default_delimiter_cb
(
   uint32 property_type
)
{
  boolean is_delimiter = FALSE;

  if ( property_type == FTM_TX_CONTROL_PROP_TX_CARRIER )
  {
    is_delimiter = TRUE;
  }
  else
  {
    is_delimiter = FALSE;
  }
  
  return is_delimiter;
}

/*! @} */

/*--------------------------------------------------------------------------------------------------------------------*/
/*!
  @brief
  Measures Rx parameters
 
  @details
  This function is the handler function to configure Radio to given mode of operation. When a TX CONTROL command is
  received, it is broken into two parts
  #- RF devices that are no longer used/removed
  #- RF devices that are currently used and being re-tuned /  RF devices that are newly used and must be woken up
 
  Each technology is expected to reconfigure their driver/devices in this order. Devices which are no longer used after
  a TX_CONTROL are returned to the system for other subscriptions to use in the future. A TX_CONTROL command 
  received for a subscription+tech which is currently configured and contains no carriers means to release all resources
 
  @param command_data
  Pointer to the structure containing command specific dispatch command
 
  @return
  Response Packet for TX CONTROL command
*/
static boolean
tx_control_handler
(
  struct ftm_rf_test_command_data_t *command
)
{
  boolean ret_val = TRUE;
  ftm_rf_test_tx_control_command_data_t *command_data;
  ftm_rf_test_req_type *req_data;
  ftm_rf_test_tx_control_rsp_payload_type *rsp_payload;
  ftm_rf_test_field_error_code_mask_type error_code = 0;
  ftm_rf_test_field_error_code_mask_type ec_unpack = 0;
  ftm_rf_test_field_error_code_mask_type ec_tech_cb = 0;
  ftm_rf_test_tx_control_mode_data_t* tx_control_data;
  uint32 meas_idx = 0;
  uint32 payload_size = 0;
  uint32 measurement_results_size = 0;
  boolean tech_override = FALSE;

  /* Param validation */
  if ( ( command == NULL ) || ( command->dispatch_data == NULL ) ||
       ( command->diag_request_data == NULL ) )
  {
    FTM_MSG( FTM_ERROR, "[FTM.RFTEST][TX_CONTROL]radio_config_handler: Null param" );
    ret_val = FALSE;
  } /* if ( ( command_instance == NULL ) || ( command_instance->sw_command == NULL ) ||
       ( command_instance->diag_request_data == NULL ) ) */

  if ( ret_val == TRUE )
  {
    /* Param validation */
    if ( command->technology >= RFM_NUM_MODES )
    {
      FTM_MSG_1( FTM_ERROR, "[FTM.RFTEST][TX_CONTROL]radio_config_handler: Bad Tech %d",
                 command->technology);
      ret_val = FALSE;
    } /* if ( command_instance->technology >= RFM_NUM_MODES ) */
  }

  if ( ret_val == TRUE )
  {  
    /* Get TX CONTROL Data */
    command_data = (ftm_rf_test_tx_control_command_data_t*)(command->dispatch_data->command_data);

    /* Get Diag Request Data */
    req_data = command->diag_request_data;

    /* Make sure that the Radio config Data and diag request data is not NULL, before proceeding */
    if ( ( command_data == NULL ) || ( req_data == NULL) )
    { 
      FTM_MSG( FTM_ERROR, "[FTM.RFTEST][TX_CONTROL]tx_control_handler: Null RC / REQ Data" );
      error_code |= (1<<FTM_RF_TEST_TX_EC_ERROR);
      ret_val = FALSE;
    } /* if !( ( radio_config_data != NULL ) && ( req_data != NULL ) ) */
  }

  if ( ret_val == TRUE ) 
  {
    tx_control_data = &(command_data->mode_data[command->technology]); 

    /* reset all data structs before populating unpacked data and payload */

    if ( tx_control_data->unpacked_data != NULL )
    {
      modem_mem_free( tx_control_data->unpacked_data, MODEM_MEM_CLIENT_RFA );
    }

    tx_control_data->unpacked_data_num = 0;
    tx_control_data->unpacked_data = NULL;
  
    /* Tech has the option to override the common unpack & dispatch. Tech has to allocate the response using the
    rsp_alloc_cb provided */        
    if ( tx_control_data->advanced_tech_callback_fp != NULL )
    {
      ftm_rf_test_tx_control_advanced_dispatch_data_type tech_override_data;

      memset(&tech_override_data, 0, sizeof(ftm_rf_test_tx_control_advanced_dispatch_data_type) );

      tech_override_data.req_prop_num = req_data->payload.num_of_properties;
      tech_override_data.req_prop_list = &(req_data->payload.property_data);
      
      ec_tech_cb = tx_control_data->advanced_tech_callback_fp( &tech_override_data );
      
    }
    else /* if ( tx_control_data->override_callback_fp == NULL )*/
    {
      /* Unpack data */
      ec_unpack = ftm_rf_test_unpack_property_list( 
                                        req_data->payload.num_of_properties, 
                                        &(req_data->payload.property_data),
                                        tx_control_data,
                                        TRUE,
                                        tx_control_req_default_unpack_cb,
                                        tx_control_req_default_delimiter_cb);
      
      /* Continue if the UNPACK error code is 0 */
      if ( ec_unpack == 0 )
      {
        /* Call Tech callback */
        if ( tx_control_data->default_callback_fp != NULL )
        {
          ec_tech_cb = tx_control_data->default_callback_fp( tx_control_data->unpacked_data, 
                                                             tx_control_data->unpacked_data_num );

        } /* if ( tx_control_data->mode_data[command_instance->technology].callback_fp != NULL ) */
        else
        {
          ec_tech_cb = (1<<FTM_RF_TEST_TX_EC_SUCCESS);
        } /* if ! ( tx_control_data->mode_data[command_instance->technology].callback_fp != NULL ) */
        
      } /* if ( ec_unpack == 0 ) */
      else
      {
        FTM_MSG( FTM_ERROR, "[FTM.RFTEST][TX_CONTROL]tx_control_handler: Unpack failure" );
      }

    }/* if ( tx_control_data->override_callback_fp == NULL ) */

    /* Accumulate error code */
    error_code |= ec_unpack;
    error_code |= ec_tech_cb;

    if ( error_code != 0 )
    {
      ret_val = FALSE;
    } /* if ( error_code != 0 ) */

    FTM_MSG_1( FTM_ERROR, "[FTM.RFTEST][TX_CONTROL][DISPATCH]: [ErrorCode 0x%x]", error_code );
  }

  /* Populate respoonse payload, if tech did not override common unpack & dispatch */
  if ( ret_val == TRUE )
  {
    uint32 payload_size = sizeof(tx_control_data->rsp_payload_data);

    tx_control_data->rsp_payload_data.error_code = error_code;

    ret_val = ftm_rf_test_alloc_response_helper( &(command->response_data),
                                                 &(tx_control_data->rsp_payload_data),
                                                 payload_size );
  }/* if ( ret_val == TRUE && tech_overriden == FALSE )*/
  
  return ret_val; 

} /* radio_config_handler */

/*! @} */

/*====================================================================================================================*/
/*!
  @name Init

  @brief
  Functions to handle TX CONTROL command initialization for registration
*/
/*! @{ */

/*--------------------------------------------------------------------------------------------------------------------*/
/*!
  @brief
  Initialize TX CONTROL Command handler module
 
  @details
  This function initializes the TX CONTROLure command module. Initialization includes, allocating the memory for
  house keeping data for TX CONTROL command and populating the command handler function
 
  @param dispatch_data
  Poitner to dispatch data specific to TX CONTROL command
 
  @return
  Flag indicating the status of TX CONTROL initialization
*/
boolean
ftm_rf_test_tx_control_init
(
  ftm_rf_test_command_dispatch_data_t *dispatch_data
)
{
  boolean ret_val = TRUE;

  /* Param Validation */
  if ( dispatch_data == NULL )
  {
    FTM_MSG( FTM_ERROR, "[FTM.RFTEST][TX_CONTROL]ftm_rf_test_tx_control_init: Null param" );
    return FALSE;
  } /* if ( dispatch_data == NULL ) */

  /* Allocate memory for TX CONTROL command handler */ 

  if ( dispatch_data->command_data == NULL )
  {
    dispatch_data->command_data = 
      (void*)modem_mem_alloc( sizeof(ftm_rf_test_tx_control_command_data_t), MODEM_MEM_CLIENT_RFA );
  } /* if ( dispatch_data->command_data == NULL ) */

  if ( dispatch_data->command_data != NULL )
  {
    memset( dispatch_data->command_data, 0, sizeof(ftm_rf_test_tx_control_command_data_t) );
    dispatch_data->command_handler = tx_control_handler;
  } /* if ( dispatch_data->command_data != NULL ) */
  else
  {
    FTM_MSG( FTM_ERROR, "[FTM.RFTEST][TX_CONTROL]ftm_rf_test_tx_control_init: Malloc failure" );
    ret_val = FALSE;
  } /* if !( dispatch_data->command_data != NULL ) */

  return ret_val;

} /* ftm_rf_test_tx_control_init */

/*--------------------------------------------------------------------------------------------------------------------*/
/*!
  @brief
  DeInitialize TX CONTROL Command handler module
 
  @details
  This function deinitializes the TX CONTROLure command module. DeInitialization includes, deallocating the memory for
  house keeping data for TX CONTROL command
 
  @param dispatch_data
  Poitner to dispatch data specific to TX CONTROL command
 
  @return
  Flag indicating the status of TX CONTROL deinitialization
*/
boolean
ftm_rf_test_tx_control_deinit
(
  ftm_rf_test_command_dispatch_data_t *dispatch_data
)
{
  boolean ret_val = TRUE;

  /* Param Validation */
  if ( dispatch_data == NULL )
  {
    FTM_MSG( FTM_ERROR, "[FTM.RFTEST][RADIO_CONFIG]ftm_rf_test_radio_config_deinit: Null param" );
    return FALSE;
  } /* if ( dispatch_data == NULL ) */

  ftm_rf_test_tx_control_command_data_t * tx_control_data = 
    (ftm_rf_test_tx_control_command_data_t *)dispatch_data->command_data;

  /* Free memory allocated for Radio Config command handler */ 
  if ( tx_control_data != NULL )
  {
    uint8 mode_idx = 0;
    for ( mode_idx = 0; mode_idx < RFM_NUM_MODES; mode_idx ++ )
    {
      if( tx_control_data->mode_data[mode_idx].unpacked_data != NULL )
      {
        modem_mem_free( tx_control_data->mode_data[mode_idx].unpacked_data, MODEM_MEM_CLIENT_RFA );
      }
    }

    modem_mem_free( tx_control_data , MODEM_MEM_CLIENT_RFA );

    dispatch_data->command_data = NULL;
  } /* if ( dispatch_data->command_data != NULL ) */

  dispatch_data->command_handler = NULL;

  return ret_val;

} /* ftm_rf_test_tx_control_deinit */

/*! @} */

/*====================================================================================================================*/
/*!
  @name Tech Registration

  @brief
  Interface for technologies to perform callback registration with the FTM RF Test module for TX CONTROL command
*/
/*! @{ */


/*--------------------------------------------------------------------------------------------------------------------*/
/*!
  @brief
  Register Tech callback
 
  @details
  This function is used to register a tech callback function for TX CONTROL command
 
  @param technology
  Technology for which the callback is to be registered
 
  @param callback_fp
  Callback funtion pointer to be registered
 
  @return
  Flag indicating the status of callback registration
*/
boolean
ftm_rf_test_tx_control_register_default_tech_cb
(
  rfm_mode_enum_type technology,
  ftm_rf_test_tx_control_tech_callback_fp callback_fp
)
{
  ftm_rf_test_command_dispatch_data_t *dispatch_data;
  ftm_rf_test_tx_control_command_data_t *tx_control_data;

  dispatch_data = ftm_rf_test_get_dispatch_data( FTM_RF_TEST_CMD_TX_CONTROL );

  /* Param validation */
  if ( dispatch_data == NULL )
  {
    FTM_MSG( FTM_ERROR, "[FTM.RFTEST][TX_CONTROL]ftm_rf_test_tx_control_register_tech_cb: Null param" );
    return FALSE;
  } /* if ( dispatch_data == NULL ) ) */

  /* Param validation */
  if ( technology >= RFM_NUM_MODES )
  {
    FTM_MSG_1( FTM_ERROR, "[FTM.RFTEST][TX_CONTROL]ftm_rf_test_tx_control_register_tech_cb: Bad Tech %d",
               technology);
    return FALSE;
  } /* if ( technology >= RFM_NUM_MODES ) */

  tx_control_data = (ftm_rf_test_tx_control_command_data_t*)dispatch_data->command_data;

  if ( tx_control_data == NULL) 
  {
    FTM_MSG( FTM_ERROR, "[FTM.RFTEST][TX_CONTROL]ftm_rf_test_tx_control_register_tech_cb: NULL tx_control data %d" );
    return FALSE;
  }
  /* Save callback function */
  tx_control_data->mode_data[technology].default_callback_fp = callback_fp;

  FTM_MSG_1( FTM_HIGH, "[FTM.RFTEST][TX_CONTROL]ftm_rf_test_tx_control_register_tech_cb: Registered for Tech %d",
             technology);

  return TRUE;

} /* ftm_rf_test_tx_control_register_tech_cb */


/*--------------------------------------------------------------------------------------------------------------------*/
/*!
  @brief
  Register Tech Override callback
 
  @details
  This function is used to register a tech callback function for TX CONTROL command
 
  @param technology
  Technology for which the callback is to be registered
 
  @param callback_fp
  Callback funtion pointer to be registered
 
  @return
  Flag indicating the status of callback registration
*/
boolean
ftm_rf_test_tx_control_register_advanced_tech_cb
(
  rfm_mode_enum_type technology,
  ftm_rf_test_tx_control_advanced_tech_dispatch_callback_fp advanced_callback_fp
)
{
  ftm_rf_test_command_dispatch_data_t *dispatch_data;
  ftm_rf_test_tx_control_command_data_t *tx_control_data;

  dispatch_data = ftm_rf_test_get_dispatch_data( FTM_RF_TEST_CMD_TX_CONTROL );

  /* Param validation */
  if ( dispatch_data == NULL )
  {
    FTM_MSG( FTM_ERROR, "[FTM.RFTEST][TX_CONTROL]ftm_rf_test_tx_control_register_tech_override_cb: Null param" );
    return FALSE;
  } /* if ( dispatch_data == NULL ) ) */

  /* Param validation */
  if ( technology >= RFM_NUM_MODES )
  {
    FTM_MSG_1( FTM_ERROR, "[FTM.RFTEST][TX_CONTROL]ftm_rf_test_tx_control_register_tech_override_cb: Bad Tech %d",
               technology);
    return FALSE;
  } /* if ( technology >= RFM_NUM_MODES ) */

  tx_control_data = (ftm_rf_test_tx_control_command_data_t*)dispatch_data->command_data;

  if ( tx_control_data == NULL) 
  {
    FTM_MSG( FTM_ERROR, "[FTM.RFTEST][TX_CONTROL]ftm_rf_test_tx_control_register_tech_override_cb: NULL tx_control data %d" );
    return FALSE;
  }
  /* Save callback function */
  tx_control_data->mode_data[technology].advanced_tech_callback_fp = advanced_callback_fp;

  FTM_MSG_1( FTM_HIGH, "[FTM.RFTEST][TX_CONTROL]ftm_rf_test_tx_control_register_tech_override_cb: Registered for Tech %d",
             technology);

  return TRUE;

} /* ftm_rf_test_tx_control_register_tech_cb */

/*! @} */

/*====================================================================================================================*/
/*!
  @name Query

  @brief
  Functions to handle TX CONTROL command
*/
/*! @{ */

/*! @} */

/*! @} */ /* FTM_RF_TEST_TX_CONTROL_H */


