#ifndef SRCHCRGSM_H
#define SRCHCRGSM_H
/*===========================================================================
             S R C H   C E L L   R E S E L E C T I O N   G S M
                     D E C L A R A T I O N S

DESCRIPTION
  This header file contains the constant definitions and function
  declarations that are necessary for performing GSM measurements
  on neighboring GSM cells during Cell Reselection.

EXTERNALIZED FUNCTIONS

INTERNALIZED FUNCTIONS

INITIALIZATION AND SEQUENCING REQUIREMENTS

Copyright (c) 2002-2012 by Qualcomm Technologies, Inc.
All Rights Reserved.
===========================================================================*/


/*===========================================================================

                        EDIT HISTORY FOR MODULE

  This section contains comments describing changes made to the module.
  Notice that changes are listed in reverse chronological order.

$Header: //components/rel/wcdma.mpss/8.4.0/l1/offline/inc/srchcrgsm.h#3 $DateTime: $ $Author: pwbldsvc $

when       who     what, where, why
--------   ---     ----------------------------------------------------------
01/10/20   ac      Mini dump framework checkin
12/09/15    gn      Added new W2G log packets 0x41DC, 0x41DD
10/07/15   vs      BSIC Id Reconf optimizations for X+W QTA scenarios
08/24/15   gsk     Skip lock request for the first search in a measurement only gap
08/07/15   gsk     Double instantiating srchfach and wsrchlte dB
07/20/15   nga     Reschedule EDRX FMO scheduler if GSM search is ongoing
06/08/15   db      Parallel FCCH+SCH support for W2G idle mode
04/10/15   ks      New RFM meas interface changes
01/19/15   psr     Global re-org for W+W
01/08/15   db      Fix for compilation error generated by FR 24926 checkin
01/07/15   db      Unification of W<->G IRAT driver for WCDMA PCH, DCH and FACH states
06/19/14   cc      IRAT DR-DSDS check in
04/07/14   cc      Protecting shared global variables
03/10/14   ks      Bolt FED API checkin
01/29/14   mm      W2G cleanup done function prototype changed
10/28/13   ar      Moving GSM module cleanup to L1M
10/14/13   cc      Fix wrong cell into RECONF list issue
10/03/13   cc      Fix the cleanup decision for RSSI in SCH
08/08/13   cc      Fixed compilation errors
08/01/13   cc      Add new cb system to avoid FACH cleanup race condition
12/17/12   mm      Interface changes for passing AS ID from RRC into GL1 functions
08/28/12   cc      Maintain a list of cmd seq to a handler for dealing with the critical sec in sending a cmd to FW  
08/17/12   cc      Support the possibility of the negative FCCH tone time offset in idle
07/24/12   geg     Upmerge WCDMA.MPSS.1.0 to WCDMA.MPSS.2.0
07/02/12   cc      Fix a typo on the function prototype
04/02/12   cc      Increased the number of array buffer in the rssi result struct from 6 to 10
                   Prototype changed on some functions to reduce unnecessary parameters 
02/03/12   dp      Get RSSI Threshold from common external #define
01/30/12   vs      Feature cleanup.
01/20/12   zr      Mainlined FEATURE_WCDMA_GENESIS_SW 
12/27/12   uk      Chk for GFW suspend before proceeding with state cleanup
05/26/11   dp      Added code so W2X_IDLE_CFG gets cleanup buf idx
04/28/11   yh      Added RxLM support for FMO
1/7/11     mm      Setting macro SRCHCRGSM_FACH_MAX_PWR_MEAS_BURST_PER_GSM_FR 
12/08/10   yh      Added GSM cleanup done callback
06/15/09   uk      Support for sending START_FACH_MEAS cmd to fw before 
                   starting a FMO gap for GSM meas
05/08/09   sup      Changing the includes for the renaming of header files  dec.h, enci.h, l1m.h, srch.h, srchi.h, 
                    srchlog.h to wdec.h, wenci.h, wl1m.h, wsrch.h, wsrchi.h, wsrchlog.h
04/24/09   stk     Compiler warning fixes
12/09/08   uk      Mainlining FEATURE_ENHANCED_CELL_RESELECTION
10/26/07   sk      Checking in MBMS branch code into mainline with MBMS feature disabled
08/03/06   sk      Changes for forbidden tones and correction of delta frame offset.
05/02/05   gs      Corrected array size of tags in struct
                   srchcrgsm_fach_rssi_cmd_result_type
04/28/05   bbd     Added support for passing GL1 HW tags parameters during
                   sending of GSM commands and retrieval of results.
12/03/04   yiz     Add FACH meas oksn info and inter-RAT meas log packets.
                   Save T_identify_GSM and T_reconfirm_GSM to FACH GSM globals.
05/25/04   sh      Added function proto srchcrgsm_cell_in_nbr_list() and
                   srchcrgsm_update_gsm_info_to_cell().
02/27/04   yiz/src Brought over field changes for FACH-GSM cleanup.
02/18/04   yiz     Add srchcrgsm_fach_cleanup_pending_cmds() to cleanup FACH
                   GSM meas cmds already sent to GL1 by CM driver.
                   Change FACH GSM meas cmds to return FALSE if oksn skipped.
01/21/04   yiz     Increase SRCHCRGSM_FACH_MAX_PWR_MEAS_BURST_PER_GSM_FR per
                   gl1_hw.h constants.
12/10/03   yiz     Add FEATURE_INTER_RAT_CELL_FACH_RE_SELECTION
12/01/03   jc      Increase num of gsm rssi measured per gsm frame.
09/20/03   sh      Changed number of cells to be reconfirmed to 1 to save
                   awake time in drx, under feature flag
                   FEATURE_MINI_BSIC_RECONF_IN_DRX.
08/15/03   gs      Added lna_state to srchcrgsm_rssi_meas_result_struct_type
07/24/03   sh      Changed SRCHCRGSM_PWR_SCAN_CMD_MAX to be calculated based
                   on SRCHCRGSM_MAX_PWR_MEAS_BURST_PER_GSM_FR (number
                   of power scans per GSM frame) and max GSM cells (32).
                   Modified srchcrgsm_rssi_meas_result_struct_type to use
                   SRCHCRGSM_MAX_PWR_MEAS_BURST_PER_GSM_FR.
11/13/02   sh      Featurized entire file on FEATURE_CELL_RESELECT_INTER_S
08/17/02   sh      Created File.
===========================================================================*/


/* ==========================================================================
** Includes and Public Data Declarations
** ========================================================================*/

/* -----------------------------------------------------------------------
** Include Files
** ----------------------------------------------------------------------- */
#include "comdef.h"
#include "customer.h"
#include "l1def.h"
#include "l1rrcif.h"
#include "srchset.h"
#include "srchgsmdrv.h"
#include "srchcmmeas.h"

#include "wsrchlog.h"

/* -----------------------------------------------------------------------
** Constant / Define Declarations
** ----------------------------------------------------------------------- */

/* Number of cells for which BSIC identification must be done */
#define SRCHCRGSM_BSIC_IDENTIFY_NUM_CELL_MAX    1

#define FACH_GSM_OKSN_CYCLE   TRUE
#define FACH_GSM_ONE_OKSN     FALSE

/* Initial rssi of samples */
#define SRCHCRGSM_INIT_RSSI_DB  SRCHGSM_MIN_ACCEPTABLE_RX_LVL_dBm_x16

/* Repetition rate of BSIC within a 51-frame multiframe.*/
#define SRCH_BSIC_REPEAT_FRAME 10

/* -----------------------------------------------------------------------
** Type Declarations
** ----------------------------------------------------------------------- */

/* Commands during GSM NSET search */
typedef enum
{
  /* sort GSM nset based on measured RSSI */
  SRCHCRGSM_RSSI_MEAS_DONE,
  /* Find BSIC Id of a cell */
  SRCHCRGSM_BSIC_IDENTIFY_DONE,
  /* Verify BSIC Id of a cell */
  SRCHCRGSM_BSIC_VERIFY_DONE,
  /* Done with GSM searching */
  SRCHCRGSM_SRCH_DONE
} srchcrgsm_cmd_enum_type;

/* Local command to advance to next state of GSM NSET search */
typedef struct
{
  /* local command header */
  l1_local_cmd_hdr_type hdr;

  /* status of command */
  boolean status;

  /* reason for command */
  srchcrgsm_cmd_enum_type reason;

} srchcrgsm_local_cmd_type;

/* GSM idle mode/FACH measurement scheduling info structure */
typedef struct
{
  /* current GFN */
  uint8 gsm_frame_num;

  /* Index to the current RSSI in the rssi_db_samples circular buffer.
   * Wraps every SRCHGSM_NUM_RSSI_SAMPLES_MAX samples.
   */
  uint8 cur_rssi_sample_idx;

  /* flag to indicate that a cleanup command for acquisition is pending */
  boolean acq_result_cleanup_pending;

  /* flag to indicate that a cleanup command for sch decode is pending */
  boolean sch_decode_result_cleanup_pending;

  /* MEAS purpose of this FMO gap */
  srchgsm_meas_purpose_enum_type fach_meas_purpose;

  /* flag for FACH GSM meas Cleanup cmd sent to GL1 
   * Set to TRUE only in CB when Startup is issued to GL1
   * Reset to FALSE only when Cleanup is issued to GL1 */
  boolean fach_cleanup_pending;
} srchcrgsm_meas_sched_info_struct_type;



/*===========================================================================

                        GLOBAL DECLARATIONS

===========================================================================*/

/* SRCHCRGSM external control parameters */

typedef struct
{
  /* Index of the next cell in the list of 4 strongest GSM cells
   * for BSIC Identification/Verification.
   */
  uint8 cell_idx_bsic_verify;

  /* flag to indicate BSIC verification timer has expired */
  boolean bsic_verif_tmr_expired;

  /* flag for FACH GSM meas results reading 
   * set to be TRUE only in CB when startup is issued to GL1 
   * reset to FALSE when results reading are done */
  boolean fach_results_pending;

  /* RSSI burst is getting triggered inside SCH gap */
  boolean rssi_in_sch_trigger_status;

  /* Whether need to wait for FACH GSM meas cleanup to finish */
  boolean gsm_meas_cleanup_pending; 

  uint8 fach_bsic_rc_cell_idx;

  /* Log structures */
  SRCH_FACH_INTER_RAT_MEAS_LOG_PKT_type fach_meas_log_pkt;
  srch_fach_gsm_rssi_log_struct_type  fach_rssi_meas_in_sch_log_pkt;
} srchcrgsm_ext_cntrl_params_type;


/* SRCHCRGSM external control parameters */
extern srchcrgsm_ext_cntrl_params_type srchcrgsm_ext_cntrl_params[WCDMA_NUM_SUBS];

void srchcrgsm_ext_cntrl_params_init(void);

void srchcrgsm_int_cntrl_params_init(void);


/* =======================================================================
**                          Macro Definitions
** ======================================================================= */



/* =======================================================================
**                        Function Declarations
** ======================================================================= */

/*===========================================================================

FUNCTION      SRCHCR_GSM_INIT

DESCRIPTION
  This function initializes the srchgsm driver, initializes variables
  related to cell reselection gsm measurements, and registers
  callback functions for RSSI, ACQ, and SCH decode measurements.

DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  Callbacks for GSM measurements are registered and srchgsm driver
  initialized.
===========================================================================*/
extern void srchcrgsm_init( wsub_id_e_type wsub_id);

/*===========================================================================

FUNCTION      SRCHCRGSM_MEAS_CMD

DESCRIPTION
  This function will send the CM Startup command to the mDSP and
  depending on the gsm_meas_cmd, formulates the corresponding GSM
  measurement command to be called at the appropriate GSM frame number
  and then sends the command to scheduler. The scheduler will then send
  the command to the GSM L1 drivers at the appropriate frame.
  This function can be called in the task context.

DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/
extern void srchcrgsm_gsm_do_meas
(
  srchgsm_meas_purpose_enum_type meas_cmd
, wsub_id_e_type wsub_id);

/*===========================================================================

FUNCTION      SRCHCRGSM_VERIFY_BSIC_ID

DESCRIPTION
  Perform BSIC verification on the 4 strongest GSM cells.
  - Perform BSIC verification on cells that have valid timing info
  - Perform BSIC identification on cells that have no timing info

DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/
extern void srchcrgsm_verify_bsic_id( uint8 cell_idx );

/*===========================================================================
FUNCTION      SRCHCR_GSM_PROCESS_RSSI_MEAS_RESULT

DESCRIPTION
  This function will update the RSSI results for all the GSM Cells for
  which the RSSI measurements were made.

DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/
extern void srchcr_gsm_process_rssi_meas_result( boolean cm_meas , wsub_id_e_type wsub_id);

/*===========================================================================

FUNCTION      SRCHCRGSM_CLEANUP

DESCRIPTION
  This function reinitializes variables related to cell reselection
  GSM measurements and also de-registers callbacks functions for
  RSSI, ACQ, and SCH decode measurements.

DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  Callbacks for GSM measurements are registered and srchgsm driver
  initialized.
===========================================================================*/
extern void srchcrgsm_cleanup( wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION      SRCHCRGSM_CLEANUP_CMD_DONE

DESCRIPTION
  This function is a call back function to check whether GSM mDSP is done 
  with suspend command. 

DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/
extern void srchcrgsm_cleanup_cmd_done( uint8 num_cmds_left , wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION      SRCHCRGSM_CLEANUP_CMD_DONE

DESCRIPTION
  This function is a call back function to check whether GSM mDSP is done 
  with suspend command so state cleanup can proceed. Awake means it is still not suspended

DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/
extern void srchcrgsm_state_cleanup_cmd_done(uint8 num_cmds_left, wsub_id_e_type wsub_id);

/*===========================================================================

FUNCTION      SRCHCRGSM_UPDATE_GSM_INFO_TO_CELL

DESCRIPTION
  This function updates the cell and timing info found during acquisition
  to the cell structure that is passed in.

DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/
void srchcrgsm_update_gsm_info_to_cell
(
  uint8 cur_gfn,
  int32 time_offset,
  srch_gsm_cell_struct_type* cell_ptr,
  uint8 *nbr_cell_gfn
, wsub_id_e_type wsub_id);

/*===========================================================================

FUNCTION      SRCHCRGSM_CELL_IN_NBR_LIST

DESCRIPTION
  This function searches the neighbor list to check if the
  <BSIC, ARFCN> pair is present.

DEPENDENCIES
  None

RETURN VALUE
  Pointer to cell, if cell with <BSIC, ARFCN> exists,
  NULL otherwise

SIDE EFFECTS
  srchcrgsm_cell_idx_bsic_verify is updated to point to new cell.
  If a best cell had been found, update ext_srchcr_cntrl->srchcr_ext_cntrl_params_mdump.srchcr_gsm_cell_ptr to this cell.
===========================================================================*/
srch_gsm_cell_struct_type* srchcrgsm_cell_in_nbr_list
(
  uint8 bsic_id,
  W_ARFCN_T arfcn
, wsub_id_e_type wsub_id);

/*===========================================================================

FUNCTION      SRCHCRGSM_FACH_RSSI_CMD

DESCRIPTION   This function issues FACH GSM RSSI measurement command to
              scheduler.

DEPENDENCIES  Must be called at a FACH GSM oksn to do RSSI MEAS

RETURN VALUE  None

SIDE EFFECTS  None

===========================================================================*/
boolean srchcrgsm_fach_rssi_cmd( wsub_id_e_type wsub_id);

/*===========================================================================

FUNCTION      SRCHCRGSM_FACH_RSSI_IN_SCH_CMD

DESCRIPTION   This function issues FACH GSM RSSI measurement in SCH command to
              scheduler.

DEPENDENCIES  This function is called at a FACH GSM SCH or BSIC Reconf oksn to do RSSI MEAS 
              if there is still space available inside the gap.

RETURN VALUE  None

SIDE EFFECTS  None

===========================================================================*/
boolean srchcrgsm_fach_rssi_in_sch_cmd(
  /* Total num bursts inside the gap */
  uint8 *num_total_bursts, wsub_id_e_type wsub_id);

/*===========================================================================

FUNCTION      SRCHCRGSM_FACH_BSIC_ID_CMD

DESCRIPTION
  

DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/
boolean srchcrgsm_fach_bsic_id_cmd( wsub_id_e_type wsub_id);

/*===========================================================================

FUNCTION      SRCHCRGSM_FACH_BSIC_RECF_CMD

DESCRIPTION   This function issues FACH GSM BSIC reconfirmation command to
              scheduler.

DEPENDENCIES  Must be called at a FACH GSM oksn to do BSIC reconfirmation

RETURN VALUE  None

SIDE EFFECTS  None

===========================================================================*/
boolean srchcrgsm_fach_bsic_recf_cmd( wsub_id_e_type wsub_id);

/*===========================================================================

FUNCTION      SRCHCRGSM_FACH_FIND_RECF_OKSN_AND_CELL

DESCRIPTION   This function finds suitable GSM cell and GSM oksn for BSIC
              reconfirmation in next 8 GSM oksn cycle, OR the suitable GSM
              cell only for next GSM occasion if cycle_oksn_sel is
              FACH_GSM_ONE_OKSN   

DEPENDENCIES  Must be called at the first GSM occasion in the next 8 GSM
              occasion cycle, or at a GSM BSIC ID occasion when no cell for
              BSIC ID.
              Must have obtained srchfach_n_intra_meas_parms.n_tti
              cycle_oksn_sel = FACH_GSM_OKSN_CYCLE, or FACH_GSM_ONE_OKSN

RETURN VALUE  FALSE if no suitable cell/oksn for BSIC reconf

SIDE EFFECTS  Update recf_suit_cell_idx and recf_suit_oksn_idx

===========================================================================*/
boolean srchcrgsm_fach_find_recf_oksn_and_cell( boolean cycle_oksn_sel , wsub_id_e_type wsub_id);

/*===========================================================================

FUNCTION      SRCHCRGSM_FACH_RECONF_TIMER_EXPIRED

DESCRIPTION   This function looks up the T_re_confirm_GSM table to check if 
              timer expired.  

DEPENDENCIES  In FACH GSM measurements

RETURN VALUE  FALSE if OK, which is not expired

SIDE EFFECTS  None

===========================================================================*/
boolean srchcrgsm_fach_reconf_timer_expired( uint32 timer , wsub_id_e_type wsub_id);

/*===========================================================================

FUNCTION      SRCHCRGSM_FACH_T_RECONFIRM_CALC

DESCRIPTION   This function calc T_reconfirm_GSM.  

DEPENDENCIES  FACH measurement occassion info available

RETURN VALUE  FALSE if FACH meas oksn invalid

SIDE EFFECTS  Update T_reconfirm_GSM

===========================================================================*/
boolean srchcrgsm_fach_t_reconfirm_calc( wsub_id_e_type wsub_id);

/*===========================================================================

FUNCTION      SRCHCRGSM_FACH_BSIC_ID_TIMER_EXPIRED

DESCRIPTION   This function looks up the T_identify_GSM table to check if 
              timer expired.  

DEPENDENCIES  In FACH GSM measurements

RETURN VALUE  FALSE if OK, which is not expired

SIDE EFFECTS  None

===========================================================================*/
boolean srchcrgsm_fach_bsic_id_timer_expired( uint32 timer , wsub_id_e_type wsub_id);

/*===========================================================================

FUNCTION      SRCHCRGSM_FACH_T_IDENTIFY_CALC

DESCRIPTION   This function calculates T_identify_GSM.  

DEPENDENCIES  FACH measurement occasion info available

RETURN VALUE  FALSE means invalid FACH meas oksn info

SIDE EFFECTS  Update T_identify_GSM

===========================================================================*/
boolean srchcrgsm_fach_t_identify_calc( wsub_id_e_type wsub_id);

/*===========================================================================

FUNCTION      SRCHCR_SORT_GSM_NSET

DESCRIPTION
  Sort GSM neighbor cells based on the measured RSSI.
  srch_gsm_nset_ptr has the cells with the updated measurements.

DEPENDENCIES
  None.

RETURN VALUE
  None.

SIDE EFFECTS
  None.
===========================================================================*/
void srchcr_sort_gsm_nset( wsub_id_e_type wsub_id);


/*===========================================================================

FUNCTION      SRCHCRGSM_FACH_CLEANUP_PENDING_CMDS

DESCRIPTION
  Cleanup for GSM meas cmds already sent to GL1

DEPENDENCIES
  None.

RETURN VALUE
  TRUE if done

SIDE EFFECTS
  None.
===========================================================================*/
boolean srchcrgsm_fach_cleanup_pending_cmds( wsub_id_e_type wsub_id);

/*===========================================================================

FUNCTION        SRCHCRGSM_FACH_LOG_MEAS

DESCRIPTION     This function is to log CELL_FACH inter-RAT measurements.

DEPENDENCIES    None

RETURN VALUE    None
  
SIDE EFFECTS    logging.
                
===========================================================================*/
void srchcrgsm_fach_log_meas( wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION      SRCHCRGSM_FACH_QUERY_KNOWN_CELL_QS_OFFSET

DESCRIPTION
  This function finds and adds known cell offsets in the same arfcn to the forbidden list..

DEPENDENCIES
  None.

RETURN VALUE
  Number of forbidden offsets which are added.

SIDE EFFECTS
  None.
===========================================================================*/
uint8 srchcrgsm_fach_query_known_cell_qs_offset(
  W_ARFCN_T arfcn,
  uint8 *frame_offset,
  uint16 *qs_offset,
  wsub_id_e_type wsub_id);

boolean srchcrgsm_fach_bsic_id_tone_result_poll_func(uint8 cur_gfn, boolean *rslt_detected, wsub_id_e_type wsub_id);
boolean srchcrgsm_fach_bsic_id_result_poll_func(uint8 cur_gfn, boolean *rslt_detected, wsub_id_e_type wsub_id);
boolean srchcrgsm_fach_bsic_recf_result_poll_func(uint8 cur_gfn, boolean *rslt_detected, uint8 srch_type, wsub_id_e_type wsub_id);
void srchcrgsm_fach_decrement_bsic_id_tmr(wsub_id_e_type wsub_id);

/*===========================================================================

FUNCTION      SRCHCRGSM_FACH_RSSI_BURSTS_POPULATE_IN_SCH

DESCRIPTION   This function populates bursts for FACH GSM RSSI commands if there is a space in SCH gap.

DEPENDENCIES  

RETURN VALUE  
uint8 - Total num bursts inside the gap

SIDE EFFECTS  Populate cmd buffer and result buffer, and update
              srchfach_gsm_rssi_parms

===========================================================================*/
uint8 srchcrgsm_fach_rssi_bursts_populate_in_sch
(
  uint8   first_gsm_cell_idx,
  wsub_id_e_type wsub_id
);

boolean srchcrgsm_fach_bsic_id_sch_dec_result_poll_func(uint8 cur_gfn, boolean *rslt_detected, uint8 srch_type, wsub_id_e_type wsub_id);
boolean srchcrgsm_fach_bsic_id_sch_dec_cmd ( wsub_id_e_type wsub_id);

void srchcrgsm_rssi_meas_result_poll_func(uint8 cur_gfn, wsub_id_e_type wsub_id);
void srchcrgsm_acq_result_poll_func( uint8 cur_gfn , wsub_id_e_type wsub_id);
void srchcrgsm_sch_decode_poll_func( uint8 cur_gfn , wsub_id_e_type wsub_id);

extern void srchcrgsm_get_previous_forbidden_offset 
(
  uint8 *frame_offset, 
  uint16 *qs_offset, 
  uint8 idx
                                  , wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION      SRCHCRGSM_GET_BSIC_ID_ACQ_RESULT

DESCRIPTION
  This function is called from the call back poll function registered with 
  the GSM frame tick handler to get the BSIC ID ACQ measurement result. 
  While triggering the ACQ measurement, the GFN of the current command to poll 
  indicates the GFN when the results would be available.

  Once the GFN matches the GFN for which the command is to be read, it calls 
  the GL1 API function to read the ACQ result for that command. 

DEPENDENCIES
  None

RETURN VALUE
  TRUE if ACQ passes i.e BSIC is decoded.
  FALSE in any other case

SIDE EFFECTS
  None
===========================================================================*/

extern boolean srchcrgsm_get_bsic_id_acq_result 
(
  uint8 cur_gfn,
  W_ARFCN_T arfcn,
  int32 *time_offset,
  uint16 *fine_freq,
  uint16 *snr
  , wsub_id_e_type wsub_id
);

/*===========================================================================
FUNCTION  srchcrgsm_fach_send_gsm_meas_cmd

DESCRIPTION
  This function will prepare the cmd sequence and send it to the srchgsmdrv cmd handler

DEPENDENCIES
  None.

RETURN VALUE
  None.

SIDE EFFECTS
  None.
===========================================================================*/
extern void srchcrgsm_fach_send_gsm_meas_cmd(
  /* Type of measurement purpose for GSM search */
  srchgsm_meas_purpose_enum_type meas_type, wsub_id_e_type wsub_id);

/*===========================================================================

FUNCTION      SRCHCRGSM_GET_GSM_MEAS_BAND_INFO

DESCRIPTION
  This function will call mcal function to allocate W2G RF buffer and send 
  WRM start meas request. This is used for idle W2G search.

DEPENDENCIES
  None

RETURN VALUE
  None
SIDE EFFECTS
  None
===========================================================================*/
void srchcrgsm_get_gsm_meas_band_info(
  wrm_freq_input_type *band_info,
  wsub_id_e_type wsub_id);

/*===========================================================================

FUNCTION      SRCHCRGSM_ALLOCATE_RF_BUF_AND_SEND_WRM_START_MEAS

DESCRIPTION
  This function will call mcal function to allocate W2G RF buffer and send 
  WRM start meas request. This is used for idle W2G search.

DEPENDENCIES
  None

RETURN VALUE
  TRUE - TRM request was granted
  FALSE - TRM request was denied

SIDE EFFECTS
  None
===========================================================================*/
boolean srchcrgsm_allocate_rf_buf_and_send_wrm_start_meas(
  uint32 dirat, rfm_meas_common_param_type* source_rf_info,
  mcalwcdma_rf_tune_type tune_type, boolean skip_wrm, wsub_id_e_type wsub_id);
/*===========================================================================
FUNCTION      SRCHCRGSM_FACH_QUERY_SRCH_IN_PROGRESS

DESCRIPTION
  This API returns the status of ongoing W2G search results in FACH state.

DEPENDENCIES
  None.

RETURN VALUE
  TRUE is W2G FMO search results are pending

SIDE EFFECTS
  None.
===========================================================================*/
extern boolean srchcrgsm_fach_query_srch_in_progress(wsub_id_e_type wsub_id);

void srchcrgsm_allocate_w2g_rf_bufs(void);

/*===========================================================================

FUNCTION      SRCHCRGSM_FACH_PREPARE_CMD

DESCRIPTION   This function issues FACH GSM measurement command to scheduler.

DEPENDENCIES  Must be called at a FACH GSM oksn to do GSM measurement

RETURN VALUE  None

SIDE EFFECTS  None

===========================================================================*/
extern boolean srchcrgsm_fach_trigger_gsm_meas(
  srchgsm_meas_purpose_enum_type meas_purpose
  , wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchcrgsm_fach_get_meas_purpose

DESCRIPTION
  This is a utility function to return the FMO measurement purpose.

DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/
extern srchgsm_meas_purpose_enum_type srchcrgsm_fach_get_meas_purpose( wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchcrgsm_get_w2g_reconf_pos

DESCRIPTION
  Find the time in ms after the QTA start when the W2G SCH burst will happen.

DEPENDENCIES
  None

RETURN VALUE
  ms past the time passed in when SCH burst will occur

SIDE EFFECTS
  None
===========================================================================*/
uint8 srchcrgsm_get_w2g_reconf_pos(
  tlm_cfn_struct_type* qta_start_time,  
  wsub_id_e_type wsub_id);


#ifdef FEATURE_WCDMA_QSH_DUMP
/*===========================================================================
FUNCTION  srchcrgsm_get_idle_fmo_gsm_meas_info

DESCRIPTION
  This function is to collect the idle/fmo w2g meas info for debugging. 

DEPENDENCIES
  None.

RETURN VALUE
  None.

SIDE EFFECTS
  None.
===========================================================================*/
extern void srchcrgsm_get_idle_fmo_gsm_meas_info(void *debug_buf, boolean idle_meas, wsub_id_e_type wsub_id);
#endif /* FEATURE_WCDMA_QSH_DUMP*/

extern boolean srchcrgsm_is_srch_reconf(wsub_id_e_type wsub_id);


#ifdef FEATURE_QSH_MDUMP 
/*===========================================================================
FUNCTION WL1_QSH_MDUMP_COLLECT_SRCHCRGSM_INT_PARAMS

DESCRIPTION
  This is a minidump function for dumping to QSH the selected srchcrgsm int global variables for minidump

DEPENDENCIES
  NONE

RETURN VALUE
  None
  
SIDE EFFECTS
  None
===========================================================================*/

extern QSH_MDUMP_FN_ATTR void wl1_qsh_mdump_collect_srchcrgsm_int_params(wsub_id_e_type wsub_id);
#endif

#endif /* SRCHCRGSM_H */
