#ifndef SRCHGSMDRV_H
#define SRCHGSMDRV_H

/*============================================================================
                            S R C H C M D R V . H
DESCRIPTION

Copyright (c) 2000 Qualcomm Technologies, Inc.  All Rights Reserved.
QUALCOMM Proprietary.  Export of this technology or software is regulated
by the U.S. Government. Diversion contrary to U.S. law prohibited.
============================================================================*/

/*===========================================================================

                      EDIT HISTORY FOR FILE

This section contains comments describing changes made to this file.
Notice that changes are listed in reverse chronological order.

$Header: //components/rel/wcdma.mpss/8.4.0/l1/offline/inc/srchgsmdrv.h#6 $ $DateTime: 2021/11/18 04:03:37 $ $Author: pwbldsvc $

when        who     what, where, why
--------    ---     --------------------------------------------------------
01/10/20   ac      Mini dump framework checkin
03/12/19    rs      Clock Plan 2.1 changes.
11/22/19    rs      FR51554: Recovery mechanism for RF scripting delays in X2Y IRAT scenarios
02/13/18    sk      Wait for AGC tune done at the end of FMO gap to handle MEAS REQ
12/16/15    db      Pend MEAS_REQ if another intraf/GSM MEAS_REQ is already being processed
12/09/15    gn      Added new W2G log packets 0x41DC, 0x41DD
12/10/15    db      Post SRCHFACH_RESUME_FMO_CLIENT_OPS local command only 
                    after tune done is completed at the end of FMO gap
12/03/15    nga     GSM Init needs only 2 W frames
10/20/15    ks      Skip W2G gap if there is not enough time to prebuild RF scripts and send X2G startup
10/20/15    mk      Passing correct signal strength and Tag pointer in case of FACH reconf
10/07/15     db      Reverting the prev CR fix, since it causes most GSM FMO's to be skipped in EDRX
09/11/15    db      Skip the W2G FMO if the time to next oksn QS is less than 10625
07/28/15    db      Prebuild RF scripts 1 GFN before issuing W2G commands
07/21/15    ks      Only call meas_complete for FMO gaps when both AGC tune done and gap are done
07/13/15    wz/ar   Add prototype to query if W2G CM/FMO search is in progress
06/18/15    gn      UT compilation fix for wcdma.mpss.7.2.0
06/08/15    db      Parallel FCCH+SCH support for W2G idle mode
06/02/15    gsk     NULL2G changes
02/27/15    ap      Initial check-in for WL1 QSH framework 
04/10/15    ks      New RFM meas interface changes
04/10/15    cc      Add CM gap end handler
03/18/15    db      Fix to schedule W2G Idle reconfirmation searches correctly.
02/02/15    ks/mk   W2G Parallel FCCH+SCH Support
02/02/15    db      Removed obsolete ACQ cleanup variables
01/13/15    db      Fix for Klockwork errors
01/08/15    db      Fix for compilation error generated by FR 24926 checkin
01/07/15    db      Unification of W<->G IRAT driver for WCDMA PCH, DCH and FACH states
08/23/14    gv      Featurization to support W compiled out
06/10/14    ar      Change prototype for init pending cb since all func's registered takes param
05/29/14    mm      Update IRAT/CM driver initialization and RxLM buffer allocation call flow
05/21/14    db      Remove race condition between WL1 reading MDSP status and GL1 updating it during FACH cleanup
04/02/14    mm      3C IRAT/CM support
02/21/14    jkb     Reverting changes for the Unified GERAN APIs
01/29/14    mm      Cleanup function callback prototype changed
12/18/13    jkb     Changes for the Unified GERAN APIs
12/11/13    mm      3C CM/IRAT support
11/20/13    gsk     DSDS:Account for time taken for GSM initializations when triggering GSM search in W.
10/24/13    cc      Remove RxD_is_active API from driver layer
09/30/13    cc      DBDC IRAT support check in
09/29/13    as      Continuing port of Dual Sim from Triton to Dime.
08/01/13    cc      Add new cb system to avoid FACH cleanup race condition
01/11/13    mm      Compiler error fixes for Triton DSDA
12/17/12    mm      Interface changes for AS ID passed to GL1 functions for DSDS
11/16/12    cc      IRAT feature for Dime
10/15/12    dp      Cleaned up code relating to unit test
08/28/12    cc      Add a function to handle the critical sec in sending a cmd to FW  
07/24/12    geg     Upmerge WCDMA.MPSS.1.0 to WCDMA.MPSS.2.0
07/10/12    dp      Made it so we don't hold mutex lock across gl1_hw_cm_gsm_init()
05/23/12    dp      Parallelized the gl1 init process when wl1 boots up
04/12/12    yh      Add support for resetting edge_core
02/03/12    dp      Get RSSI Threshold from common external #define
01/26/12    zr      Mainlined FEATURE_WCDMA_GENESIS_SW, removed FEATURE_WCDMA_TAXIS_SW
09/12/11    yh      Increase number of pwr meas to 10 per GSM frame
07/08/11    mk      Fixed compilation error.
04/28/11    mr      Added support for unit test framework under FEATURE_CM_UNIT_TEST
1/17/11     mm      Featurized srchgsm_drv_check_validity()
1/7/11      mm      Prototype for API srchgsm_drv_check_validity
12/21/10    dm      Moved mutex initializations to wl1m while doing 
                    task initialization.
12/08/10    yh      Add cleanup done status and API to check if GSM mDSP is awake
08/30/10    yh      Externed srchgsm_gfn_update_in_odd_frame
08/23/10    ks      Removed inclusion of mdsp header for Genesis (featurized)
06/03/10    yh      Deleted dependency on mcalwcdma_cm.h
05/07/10    yh      Add support for IRAT RF buffer control
07/31/09    yh      Remove references to FEATURE_WCDMA_OFFLINE_MODEM_IRAT_INITIAL_DEV
06/17/09    uk      Prevent aset/nset meas during a FMO GSM gap
06/15/09    uk      Support for sending START_FACH_MEAS cmd to fw before 
                    starting a FMO gap for GSM meas
05/01/09    yh      Put GSM pending commands cleanup inside GSTMR context
04/17/09    yh/uk   Add W2G mutex into W2G drivers code
03/12/09    uk      Externed srchgsm_clks_set_to_gsm flag
01/27/09    stk/yh  Added IRAT bring-up code under FEATURE_WCDMA_OFFLINE_MODEM_IRAT_INITIAL_DEV
01/22/08    yh      Added debug code to catch cmds being scheduled too soon in G-timeline.
04/05/06    sk/bbd  Added frequency offset to SCH dec struct and ACQ start struct.
02/07/06    bbd     Moved GSM clock variables to l1utils and added support for
                    GSM clock shutdown voting mechanism.
04/28/05    bbd     Fixes for passing GL1 HW tags parameters during sending of GSM commands
                    and retrieval of results.
04/20/05    bbd     Changed FEATURE_TWO_PARAM_ASYNC_RX_METRICS to
                    FEATURE_USE_LATEST_GL1_HW_API.
                    Added support for GL1 HW abstraction to pass parameters needed
                    for RF driver. These parameters are encapsulated in the "tags" field.
08/23/08    sh      Increased SRCH_GSM_MAX_FR_NUM_DIFF to 18.
03/11/04    gs      Externalized variable srchcm_gsm_clock_enable_state
                    Externalized function srchcm_gsm_query_gsm_clock_state
12/17/03    yiz     Moved srchgsmdrv.h out to srchset.h
12/16/03    gs      Support for GSM Quadband
12/10/03    yiz     Add FEATURE_INTER_RAT_CELL_FACH_RE_SELECTION
11/04/03    gs      Externalized function srchgsm_drv_init_on_resume
08/15/03    gs      Added element do_cleanup in strcuture
                    srchcm_gsm_stop_acq_cmd_param_struct_type.
                    Updated declaration of function srchgsm_read_pwr_meas_result
                    as per changes in source file.
                    Externalized function srchgsm_send_acq_cleanup_req
07/11/03    gs      Created macro SRCHCM_GSM_FRAME_NUM_INVALID
                    Externalized function srchcm_gsm_update_gsm_clock_state
01/30/03    gs      Defined function type SRCHGSM_CMD_RESULT_POLL_CB_FUNC_TYPE
                    Defined function type SRCH_GSM_CMD_SENT_POST_CB_FUNC_TYPE
                    Added member cmd_sent_post_cb_func to structure
                    srchgsm_mdsp_cmd_struct_type
                    Updated function prototype as per changes in srchgsmdrv.c
                    and externalized new functions.
10/21/02    gs      Changed the uncertainty window type to uint16 (same as
                    GSM gl1 and mdsp driver)
                    Externalized the function to set SCH decode search width
08/09/02    gs      Created this file
===========================================================================*/

/* ==========================================================================
** Includes and Public Data Declarations
** ========================================================================*/

/* -----------------------------------------------------------------------
** Include Files
** ----------------------------------------------------------------------- */

#include "wcdma_variation.h"
#include "comdef.h"
#include "gl1_hw.h"
#include "l1rrcif.h"

#include "wl1rfmif.h"
#include "wl1api.h"
#include "mcalwcdma_cm.h"
#include "mcalwcdma_srch.h"

/* -----------------------------------------------------------------------
** Constant / Define Declarations
** ----------------------------------------------------------------------- */

/* GSM IRQ config field related macro */
#define GSTMR_MICRO_IRQ_MSB_IGNORE_EVEN_ODD_BIT 0x0002

/* GSM 51 multiframe number */
#define SRCH_GSM_MULTI_FRAME_COUNT 51
/* GSM Quater symbols per GSM frame */
#define SRCH_GSM_NUM_QS_PER_FRAME 5000

#define SRCH_GSM_MAX_MDSP_CMD_BUF_SIZE 20

/* The number of GSM frame by which cmd frame number can lead the
   GSM frame number. Other wise it is treated as missed cmd */
#define SRCH_GSM_MAX_FR_NUM_DIFF       18

/* GSM mDSP command related macros */
#define SRCHCM_MAX_PWR_MEAS_BURST_PER_GSM_FR 10

/* invalid GSM frame number for WCDMA gap */
#define SRCHCM_GSM_FRAME_NUM_INVALID 0xFF

/* Number of GSM RSSI Samples per GSM carrier */
#define SRCHFACH_NUM_GSM_RSSI_PER_CARRIER  3

#define SRCHGSM_MIN_ACCEPTABLE_RX_LVL_dBm_x16 GL1_HW_MIN_ACCEPTABLE_RX_LVL_dBm_x16

/* RSSI in SCH: Allow only 6 cells to be measured in SCH gap */
#define SRCHCM_MAX_NUM_RSSI_BURSTS_IN_SCH_GAP 6

/* RSSI in SCH: Num of remaining rssi bursts can be used */
#define SRCHCM_NUM_REM_RSSI_BURSTS_IN_SCH_GAP (SRCHCM_MAX_PWR_MEAS_BURST_PER_GSM_FR) - \
                                              (SRCHCM_MAX_NUM_RSSI_BURSTS_IN_SCH_GAP)

#define SRCHGSM_CHIPX_2048_INTO_MS 0.53

#define SRCHGSM_DRV_CHECK_RANGE(cm_gap_const)\
((cm_gap_const > 0) && (cm_gap_const <= SRCH_GSM_NUM_QS_PER_FRAME))

/* Floor RSSI for a GSM cell */
#define SRCHGSM_GSM_FLOOR_RSSI_DBMX16 (-110 * 16)

/* Maximum number of power bursts that can be measured per
 * GSM frame during cell reselection.
 */
#define SRCHCRGSM_MAX_PWR_MEAS_BURST_PER_GSM_FR 6 

/* Maximum number of frames for power scans */
#define SRCHCRGSM_PWR_SCAN_CMD_MAX             18 /* up to 80ms for FACH */

/* Maximum number of bytes of SCH data */
#define SRCHCRGSM_MAX_SCH_OCTETS                4

/* Max number of forbidden tone positions */
#define SRCH_GSM_NUM_MAX_FORBIDDEN_OFFSET 3

/* Index to the GSM measurement related structures for non-DCH mode */
#define SRCHGSM_NON_DCH_MEAS_INDEX 0

/* Inter RAT measurement related macro */
/* ----------------------------------- */
#define SRCHCM_GSM_MDSP_CMD_FTSM_QS  FRAME_TICK_SETUP_MARGIN_QS
/* number of SCH decode cmd in a GAP */
#define SRCHCM_GSM_SCH_DEC_CMD_MAX_PER_GAP 2

/* Max BSIC Id and verify cells */
#define SRCHCM_SET_GSM_CELL_BSIC_IDENTIFY_MAX 8
#define SRCHCM_SET_GSM_CELL_BSIC_VERIFY_MAX   8

/* Invalid GSM meas info related index */
#define SRCHCM_GSM_MEAS_INFO_IDX_INVALID 0xFF
/* This is the number of frame offset in which the compressed
   mode GAP is there. 0 means that gap is in next WCDMA frame
   1 means GAP is after 1 frame after the next frame */
#define SRCHCM_GSM_ADV_INFO_COUNT 1
/* GSM advance info buffer count.
   Keep 1 extra buffer as the GSM mDSP command buffer pointers
   are held in this in the measurement info structure */
#define SRCHCM_GSM_ADV_INFO_BUF_COUNT (SRCHCM_GSM_ADV_INFO_COUNT + 1)

/* Total SCH result buffer size */
#define SRCHCM_GSM_NUM_SCH_RESULT_BUF_WORD16 \
  (SRCHCM_GSM_NUM_WORD16_SCH_RX_DATA_MDSP + SRCHCM_GSM_GL1_HW_MDSP_RX_HDR_DIFF)
/* Number of maximum SCH decode result.
   2 SCH decode can be programmed back to back for BSIC Id.
   1 extra that can possibly come immediate after these for BSIC re-conf */
#define SRCHCM_GSM_MAX_SCH_RESULT 3
/* SCH mDSP header length */
#define SRCHCM_GSM_NUM_WORD16_SCH_RX_HDR_MDSP  MDSP_RX_HDR_SIZE
/* SCH decoded data length in mDSP */
#define SRCHCM_GSM_SCH_PAYLOAD_SIZE_MDSP       2
/* SCH decode result buffer.
   5 header word16 + 2 word16 for SCH payload 25 bits */
#define SRCHCM_GSM_NUM_WORD16_SCH_RX_DATA_MDSP \
  (SRCHCM_GSM_NUM_WORD16_SCH_RX_HDR_MDSP + SRCHCM_GSM_SCH_PAYLOAD_SIZE_MDSP)
/* Difference between the mDSP and GL1 HW header size */
#define SRCHCM_GSM_GL1_HW_MDSP_RX_HDR_DIFF \
  ((sizeof(gl1_defs_rx_hdr_struct)/sizeof(uint16)) - \
    SRCHCM_GSM_NUM_WORD16_SCH_RX_HDR_MDSP)

/* Number of power scan commands possible per GAP */
#define SRCHCM_GSM_PWR_SCAN_CMD_MAX_PER_GAP 3

#define SRCHGSM_STARTUP_CLEANUP_CMDS 2

/* Number of SCH command possible per W2G CM GAP */
#define SRCHGSM_ASYNC_SCH_CMD_MAX_PER_GAP 1

#define SRCHGSM_SEQ_MAX_CMD SRCHCRGSM_PWR_SCAN_CMD_MAX \
                               + SRCHGSM_STARTUP_CLEANUP_CMDS \
                               + SRCHGSM_ASYNC_SCH_CMD_MAX_PER_GAP

#define WL1_W2G_LOG_CM_NOT_APPLICABLE 2
#define WL1_W2G_LOG_GAP_NOT_APPLICABLE 0

extern void srchgsm_edge_block_cb_sub1(void);
extern void srchgsm_edge_block_cb_sub2(void);

#ifdef FEATURE_DUAL_WCDMA
#define SRCHGSM_GET_EDGE_BLK_CB()         ((wsub_id == WCDMA_SUB_ID_0)? srchgsm_edge_block_cb_sub1 : srchgsm_edge_block_cb_sub2)
#else
#define SRCHGSM_GET_EDGE_BLK_CB()         (srchgsm_edge_block_cb_sub1)
#endif /* FEATURE_DUAL_WCDMA */
/* -----------------------------------------------------------------------
** Type Declarations
** ----------------------------------------------------------------------- */

/* GSM Measurement state enum type definition - used in DCH */
typedef enum
{
  SRCHCM_GSM_MEAS_STATE_IDLE,
  SRCHCM_GSM_MEAS_STATE_READY,
  SRCHCM_GSM_MEAS_STATE_MEAS,
  SRCHCM_GSM_MEAS_STATE_DONE,
  SRCHCM_GSM_MEAS_STATE_RES_PROC,
  SRCHCM_GSM_MEAS_STATE_READY_PENDING,
  SRCHCM_GSM_MEAS_STATE_MEAS_PENDING,
  SRCHCM_GSM_MEAS_STATE_DONE_PENDING,
  SRCHCM_GSM_MEAS_STATE_RES_PROC_PENDING
} srchcm_gsm_meas_state_enum_type;

/* GSM mDSP command enum type definiiton */
typedef enum
{
  SRCHGSM_CM_STARTUP_MDSP_CMD,
  SRCHGSM_CM_CLEANUP_MDSP_CMD,
  SRCHGSM_PWR_MEAS_MDSP_CMD,
  SRCHGSM_ACQ_START_MDSP_CMD,
  SRCHGSM_ACQ_STOP_MDSP_CMD,
  SRCHGSM_ASYNC_SCH_RECE_MDSP_CMD,
  SRCHGSM_NUM_MDSP_CMD
} srchgsm_cmd_type_enum_type;

/* GL1 initialization state enum type definiiton */
typedef enum
{
  SRCHGSM_GL1_ON_PENDING,
  SRCHGSM_GL1_ON,
  SRCHGSM_GL1_OFF
} srchgsm_gl1_init_state_enum_type;

/* Measurement purpose for GSM cells */
typedef enum
{
  /* RSSI scan  */
  SRCHGSM_RSSI_SCAN,
  /* BSIC identification */
  SRCHGSM_BSIC_IDENTIFY,
  /* BSIC identification - Tone detect done. SCH decode */
  SRCHGSM_BSIC_IDENTIFY_SCH,
  /* BSIC Reconfirmation  */
  SRCHGSM_BSIC_RECONF,
  /* RSSI scan with SCH decode in BSIC ID gap */
  SRCHGSM_BSIC_IDENTIFY_RSSI,
  /* RSSI scan with SCH decode in BSIC RECONF gap */
  SRCHGSM_BSIC_RECONF_RSSI,
  SRCHGSM_MEAS_PURPOSE_NUM
} srchgsm_meas_purpose_enum_type;

/* band list update action */
typedef enum
{
  SRCHGSMDRV_BANDLIST_RESET,
  SRCHGSMDRV_BANDLIST_ADD,
  SRCHGSMDRV_BANDLIST_RESET_AND_ADD,
  SRCHGSMDRV_BADNLIST_VALID
} srchgsmdrv_bandlist_update_action_enum_type;

/* CB function if GL1 initialization is pending */
typedef void SRCHGSM_GL1_INIT_PENDING_CB_FUNC_TYPE(uint8,wsub_id_e_type wsub_id);
/* GSM command result poll call back function type */
typedef void SRCHGSM_CMD_RESULT_POLL_CB_FUNC_TYPE(uint8, wsub_id_e_type wsub_id);
/* call back fucntion for command cleanup */
/* GSM command cleanup pre call back function type */
typedef void SRCHGSM_CMD_CLEANUP_PRE_CB_FUNC_TYPE(wsub_id_e_type wsub_id);
/* GSM command result poll call back function type */
typedef void SRCHGSM_CMD_CLEANUP_POLL_CB_FUNC_TYPE(uint8,wsub_id_e_type wsub_id);

typedef void SRCH_GSM_CMD_SENT_POST_CB_FUNC_TYPE(wsub_id_e_type wsub_id);

/* GAP parameters in GSM time unit structure definition */
typedef struct
{
  /* CM gap start frame number */
  uint8 frame_num;
  /* CM gap start QS offset */
  uint16 offset_qs;
  /* CM gap length in GSP QS */
  uint16 gap_len_qs;
} srchgsm_gap_param_gsm_struct_type;

/* Common minimum GSM command type structure definition */
typedef struct
{
  /* GSM copmmand frame number. This is always the first element in
     every GSM command structure */
  uint8 frame_num;
} srchcm_gsm_cmd_param_struct_type;

/* GSM CM startup command structure definition */
typedef struct
{
  /* Command send frame number */
  uint8 frame_num;
  /* CM startup QS offset */
  uint16 offset_qs_to_start;
  /* RF buffer info */
  void *rf_buf;
} srchgsm_startup_cmd_param_struct_type;

/* GSM CM cleanup command structure definition */
typedef struct
{
  /* Command send frame number */
  uint8 frame_num;
  /* CM cleanup QS offset */
  uint16 offset_qs_to_end;
} srchgsm_cleanup_cmd_param_struct_type;

/* GSM RSSI power meas command structure definition */
typedef struct
{
  /* Command send frame number */
  uint8 frame_num;
  /* number RSSI scan burst */
  uint8 num_bursts;
  /* ARFCN of the carrier for which RSSI scan to be done */
  W_ARFCN_T carrier_arfcn[SRCHCM_MAX_PWR_MEAS_BURST_PER_GSM_FR];
  /* starting offset of start of the burst */
  uint16 offset_to_start[SRCHCM_MAX_PWR_MEAS_BURST_PER_GSM_FR];
  /* expected RSSI strength fo rLNA range selection */
  int16 signal_strength_dbx16[SRCHCM_MAX_PWR_MEAS_BURST_PER_GSM_FR];
  /* Burst position in the GAP */
  gl1_hw_burst_position_type burst_position[SRCHCM_MAX_PWR_MEAS_BURST_PER_GSM_FR];
  /* GL1 HW abstraction to allow RF parameters to be passed back to GL1 HW driver
     This is transparent to WL1. */
  gl1_hw_rx_tags_type *tags;
} srchgsm_pwr_scan_cmd_param_struct_type;

/* GSM FCCH ACQ start command structure definition */
typedef struct
{
  /* Command send frame number */
  uint8 frame_num;
  /* GSM cell ARFCN */
  W_ARFCN_T arfcn;
  /* RSSI of the GSM cell */
  int16 signal_strength;
  /* ACQ start QS offset */
  uint16 start_offset;
  /* SCH to be decode if the tone is detected */
  /* Frequency offset for this GSM cell */
  int16 frequency_offset;
  boolean sch_decode;
  /* GL1 HW abstraction to allow RF parameters to be passed back to GL1 HW driver
     This is transparent to WL1. */
  gl1_hw_rx_tags_type tags;
} srchgsm_start_acq_cmd_param_struct_type;

/* GSM FCCH ACQ stop command structure definition */
typedef struct
{
  /* Command send frame number */
  uint8 frame_num;
  /* GSM cell ARFCN */
  W_ARFCN_T arfcn;
  /* ACQ stop QS offset */
  uint16 stop_offset;
} srchgsm_stop_acq_cmd_param_struct_type;

/* GSM SCH decode command structure definition */
typedef struct
{
  /* Command send frame number */
  uint8 frame_num;
  /* GSM cell ARFCN */
  W_ARFCN_T arfcn;
  /* RSSI of the GSM cell */
  int16 signal_strength;
  /* SCH decode uncertaintity window */
  uint16 uncertainty_win_size;
  /* Offset of SCH burst center from frame boundary */
  uint16 offset_to_center_of_burst;
  /* Frequency offset for this GSM cell */
  int16 frequency_offset;
  /* GL1 HW abstraction to allow RF parameters to be passed back to GL1 HW driver
     This is transparent to WL1. */
  gl1_hw_rx_tags_type *tags;
} srchgsm_sch_decode_cmd_param_struct_type;

/* GSM  RSSI power meas parameter structure definition */
typedef struct
{
  /* start frame number at which pwr scan can be started */
  uint8 start_frame_num;
  /* This is the starting offset in the start frame */
  uint16 start_offset_qs;
  /* window size in which the power scan can be done.
     Note that this can be more than 1 frame length */
  uint16 win_size_qs;
} srchgsm_pwr_scan_params_struct_type;

/* GSM  BSIC Identification parameter structure definition */
typedef struct
{
  /* cell channel frequency */
  W_ARFCN_T arfcn;
  /* timing valid. If valid then SCH decode otherwise FCCH detect */
  boolean timing_valid;
  /* first GSM frame number in which to start FCCH detect or SCH decode*/
  uint8 first_frame;
  /* offset in frame where to start SCH decode or FCCH detect*/
  uint16 offset_qs;
  /* for SCH decode */
  /* frequency offset for this cell from the fcch tone detect */
  int16 frequency_offset;
  /* for FCCH detect */
  /* window size for FCCH detect */
  uint16 fcch_win_size;
  /* for SCH decode */
  /* number of frame available for SCH decode */
  uint8 num_frames;
  /* Last measured signal strength of the cell */
  uint16 signal_strength;
} srchgsm_bsic_id_params_struct_type;

/* GSM  BSIC reconfirmation parameter structure definition */
typedef struct
{
  /* cell channel frequency */
  W_ARFCN_T arfcn;
  /* GSM frame number in which to do SCH decode*/
  uint8 sch_decode_fr_num;
  /* offset in frame where to start SCH decode */
  uint16 sch_decode_qs_offset;
  /* frequency offset for the SCH decode */
  int16 frequency_offset;
  /* Signal strength of the cell */
  int16 signal_strength;
} srchgsm_bsic_reconf_params_struct_type;

/* GSM command structure definition */
typedef struct
{
  /* command type */
  srchgsm_cmd_type_enum_type cmd_type;
  /* frame number at which the command to be sent */
  uint8 frame_num;
  /* command pointer */
  void* cmd_param_ptr;
  /* cmd sent post call back function */
  SRCH_GSM_CMD_SENT_POST_CB_FUNC_TYPE* cmd_sent_post_cb_func;
} srchgsm_mdsp_cmd_struct_type;

/* GSM command buffer structure definition */
typedef struct
{
  /* GSM command buffer management related variables */
  uint8 gsm_mdsp_cmd_buf_head;
  uint8 gsm_mdsp_cmd_buf_tail;
  uint8 gsm_mdsp_cmd_buf_used;

  /* GSM comand buffer */
  srchgsm_mdsp_cmd_struct_type gsm_mdsp_cmd_buf[SRCH_GSM_MAX_MDSP_CMD_BUF_SIZE];
}srchgsm_mdsp_cmd_buf_struct_type;

/* GSM Command List*/
typedef struct
{
  /* GSM Command type */
  srchgsm_cmd_type_enum_type cmd_type;
  /* GSM command pointer */
  void* gsm_mdsp_cmd_ptr;
  /* call back function after command has been sent */
  SRCH_GSM_CMD_SENT_POST_CB_FUNC_TYPE* cmd_sent_post_cb_func;
} srchgsm_send_cmd_seq_type;


/* GSM measurement info struct definition.
   This structure keeps the parameters for various type of measurement and
   the GSM command parameters. The meas info is the UNION of all types of
   possible measurement. The measurement type is indicated by GSM measurement
   type. */
typedef struct
{
  /* indicate if this measurement info is valid. The info is Invalid
     to start with. If gets updates with each GSM advance info update */
  boolean valid;

  /* indicate that this information is in use and shall not be over-written */
  boolean in_use;

  /* indicate the CFN at which this info is applicable */
  uint8 cfn;

  /* GSM measurement type. indicate the type of measurement info kept
     in the union below */
  srchgsm_meas_purpose_enum_type meas_purpose;

  /* indicate that gap is used with overridden or alternate purpose */
  boolean gap_purpose_is_oride;

  /* GSM GAP parameters. indicate GFN, QS offset etc. */
  srchgsm_gap_param_gsm_struct_type gsm_gap_params;

  /* W2G startup and cleaup command parameters. This is applicable to any type of
     GSM measurement */
  srchgsm_startup_cmd_param_struct_type startup_cmd_params;
  srchgsm_cleanup_cmd_param_struct_type cleanup_cmd_params;

  struct
  {
    /* RSSI scan info */
    /* ------------- */

    /* RSSI scan GSM measurement and command parameters */
    struct
    {
      /* RSSI scan measurement parameters */
      /* Max num of cells can be scheduled */
      uint8 num_max_cells;
      /* Real num of cells that we scheduled */
      uint8 num_cells_for_meas;
      srchgsm_pwr_scan_params_struct_type pwr_scan_params;

      /* RSSI scan GSM command parameters */
      uint8 num_pwr_scan_cmd;
      srchgsm_pwr_scan_cmd_param_struct_type cmd_params[SRCHCRGSM_PWR_SCAN_CMD_MAX];
    } pwr_meas;

    /* BSIC Id parameter */
    /* ----------------- */

    struct
    {
      /* trigger function set this value to save the cell index in the meas params array
         that is a candidate for this measurement */
      uint8 meas_cell_info_idx;
      /* number of cells in the candidate array */
      uint8 num_cell_info;
      struct
      {
        /* cell pointer for which the FCCH ACQ is being done */
        /* It can be typecasted to srch_gsm_cell_struct_type in non-DCH mode and 
                   srchcm_gsm_cell_struct_type in DCH mode
              */
        void *cell_ptr;

        /* BSIC Id measurement parameters */
        srchgsm_bsic_id_params_struct_type bsic_id_params;

        /* FCCH ACQ detect OR SCG decode command parameters */
        union
        {
          struct
          {
            srchgsm_start_acq_cmd_param_struct_type acq_start;
            srchgsm_stop_acq_cmd_param_struct_type acq_stop;
          } acq_cmd;

          srchgsm_sch_decode_cmd_param_struct_type sch_decode[SRCHCM_GSM_SCH_DEC_CMD_MAX_PER_GAP];
        } cmd_params;
      } bsic_id_info;
    } bsic_id;

    /* BSIC reconf parameter */
    /* --------------------- */

    struct
    {
      /* trigger function set this value to save the cell index in the meas params array
         that is a candidate for this measurement */
      uint8 meas_cell_info_idx;
      /* Number of cell in the candidate measurement parameter list */
      uint8 num_cell_info;
      struct
      {
        /* cell pointer for which the SCH Decode is being done */
        /* It can be typecasted to srch_gsm_cell_struct_type in non-DCH mode and 
                   srchcm_gsm_cell_struct_type in DCH mode
              */
        void *cell_ptr;

        /* SCH decode measurement parameters */
        srchgsm_bsic_reconf_params_struct_type bsic_reconf_params;

        /* SCH decode GSM command parameters */
        srchgsm_sch_decode_cmd_param_struct_type cmd_params;

      } bsic_reconf_info[SRCHCM_SET_GSM_CELL_BSIC_VERIFY_MAX];
    } bsic_reconf;

  } meas_info;
} srchgsm_meas_info_struct_type;

/* ----------------------------------*/
/*   GSM Measurement Result Structures     */
/* ----------------------------------*/

/* RSSI scan result poll info struct definition */

typedef struct
{
  /* Number of RSSI scan command in this GAP */
  uint8 num_cmds;
  /* Number of command result received */
  uint8 num_result_rece;
  /* number of commands sent to mDSP - used in DCH */
  uint8 num_cmds_sent;

  struct
  {
    /* timeout after number after commands are scheduled - used in DCH */
    uint8 result_fetch_timeout_unit_wframe;
  } dch_params;

  struct
  {
    /* Indicates if RSSI results got posted to measurement layer - used in FACH */
    boolean result_posted;
  } non_dch_params;
}srchgsm_rssi_meas_result_mdump_struct_type;


/* Each command result info */
typedef  struct
{
  /* GFN when the result of this command is expected */
  uint8 result_frame_num;
  /* Number of GSM bursts in this command */
  uint8 num_bursts;
  /* GSM cell array indicies for each bursts */
  uint8 cell_idx[SRCHCM_MAX_PWR_MEAS_BURST_PER_GSM_FR];
  /* measured RSSI for each burst */
  int16 rssi_dbmx16[SRCHCM_MAX_PWR_MEAS_BURST_PER_GSM_FR];
}cmd_result_mdump_struct_type;


typedef struct
{
	srchgsm_rssi_meas_result_mdump_struct_type srchgsm_rssi_meas_result_mdump;


  /* Each command result info */
  struct
  {
    cmd_result_mdump_struct_type cmd_result_mdump;
    /* LNA state of each burst */
    uint8 lna_state[SRCHCM_MAX_PWR_MEAS_BURST_PER_GSM_FR];

    gl1_hw_rx_tags_type tags[SRCHCM_MAX_PWR_MEAS_BURST_PER_GSM_FR];
    /*schedule error*/
    boolean schedule_error[SRCHCM_MAX_PWR_MEAS_BURST_PER_GSM_FR];    
  } cmd_result[SRCHCRGSM_PWR_SCAN_CMD_MAX];
} srchgsm_rssi_meas_result_struct_type;

/* FCCH ACQ poll info struct information */
typedef struct
{
  /* cell pointer for which the FCCH ACQ is being done */
  /* It can be typecasted to srch_gsm_cell_struct_type in non-DCH mode and 
        srchcm_gsm_cell_struct_type in DCH mode
    */
  void *cell_ptr;

  /* ACQ start number. Used to establish initial frame offset */
  uint8 acq_start_frame;
  /* ACQ start window offset. Used to establish QS offset */
  uint16 acq_win_start_offset;

  /* GFN at which the result is expected */
  uint8 result_frame_num;
  /* Number of frames for which the FCCH ACQ result need to be polled.
     This is based on the ACQ window length */
  uint8 num_results;

  /* Number of frames for which result has been polled */
  uint8 num_result_polled;
  /* indicate if tone is detected in polled frames */
  boolean tone_is_detected;
  /* SNR of last strongest tone detected */
  uint16 tone_snr;
  /* Tone offset w.r.t. ACQ window for last strongest tone detected */
  int16 tone_offset;
  /* Frequency offset for the tone */
  int16 tone_freq_offset;

  /* indicate that command for FCCH detect has been sent to mDSP */
  boolean acq_start_cmd_sent;
  boolean acq_stop_cmd_sent;

 /* Hyper frame number in current timeline at which FCCH burst start, 
    this is needed to calculate the SCH hyper frame offset in case of Parralel FCCH */
  uint32 decode_hyper_frame_num;

  struct
  {
    /* SCH data buffer - used in idle mode and FACH */
    uint8 sch_data[SRCHCRGSM_MAX_SCH_OCTETS];
  } non_dch_params;
} srchgsm_fcch_acq_result_struct_type;

/* SCH decode poll info structure definition */
typedef struct
{

/* Current timeline GFN at which SCH is being decoded. This is the 
   frame burst at which SCH burst starts */
  uint8 decode_frame_num;

  /* GFN at which to get the SCH decode burst matrix */
  uint8 burst_matric_frame_num;
  /* GFN at which result is expected */
  uint8 result_frame_num;

  /* Frame number where the SCH burst is expected to be */
  uint8 sch_burst_frame_num;

  /* SCH decode burst matric contents */
  boolean burst_matric_valid;

  /* SCH decode status. TRUE is burst is received and CRC passes */
  boolean sch_decode_status;
  /* SCH decode header and data buffer */

  /* Specific to Idle mode/FACH */
  /*----------------------------*/
  struct
  {
    /* Indicates if results got posted to measurement layer */
    boolean result_posted;
  }non_dch_params;

  /* Specific to DCH */
  /*-----------------*/
  struct
  {
    /* indicate that command for SCH decode has been sent to mDSP */
    boolean cmd_sent;
    /* indicate this result was meant for bsic Id */
    boolean purpose_bsic_id;
    /* Hyper frame number in current timeline at which SCH burst start */
    uint32 decode_hyper_frame_num;
  }dch_params;
  
  /* cell pointer for which the SCH decode is being done */
  /* It can be typecasted to srch_gsm_cell_struct_type in non-DCH mode and 
        srchcm_gsm_cell_struct_type in DCH mode
    */
  void *cell_ptr;

} srchgsm_sch_decode_result_mdump_struct_type;

/* SCH decode poll info structure definition */
typedef struct
{
  srchgsm_sch_decode_result_mdump_struct_type srchgsm_sch_decode_result_mdump;

  /* SCH decode burst matric contents */
  gl1_defs_metrics_rpt burst_matric_rpt;
  /* SCH decode header and data buffer */
  uint16 buffer[SRCHCM_GSM_NUM_SCH_RESULT_BUF_WORD16];  
  /* GL1 HW abstraction to allow RF parameters to be passed back to GL1 
     HW driver. This is transparent to WL1. */
  gl1_hw_rx_tags_type tags;
} srchgsm_sch_decode_result_struct_type;

/* W2G measurement result related variables */
typedef struct
{

  /* Common elements across all states */
  /*-----------------------------------*/
  /* RSSI measurement result info */
  srchgsm_rssi_meas_result_struct_type rssi_result;

  /* FCCH Acquisition result buffer - in case of idle mode and FACH */
  srchgsm_fcch_acq_result_struct_type fcch_acq_result;

  /* SCH decode result buffer */
  srchgsm_sch_decode_result_struct_type sch_decode_result[SRCHCM_GSM_MAX_SCH_RESULT];

  struct
  {
    /* Pending FCCH ACQ measurement result info. This is used when FCCH is going 
       to get triggered even though previous one hasn't been completed. */
    srchgsm_fcch_acq_result_struct_type fcch_detect_result_pending;

    /* SCH decode result info */
    uint8 sch_decode_result_head;
    uint8 sch_decode_result_tail;
    uint8 num_sch_decode_result_waiting;
    uint8 num_sch_decode_cmd_sent;
  } dch_params;

}  srchgsm_meas_result_struct_type;

/* GSM driver information structure definition */
typedef struct
{
  /* Request to de-init GL1 while init was pending */
  boolean deinit_gl1;

  /* Status of GSM RxFE */
  boolean gsm_error_detected;

  /* Pointer to keep the RF buffer that was sent for cm_startup */
  mcalwcdma_cm_irat_rf_buf_ctrl_struct_type *gsm_rf_buf_ptr;

/* GSM frame number that counts 51 multiframe modulo count */
  uint8 gsm_frame_num;

  /* GSM Inter-RAT search related variables */
  /* indicate the state of the GSM RSSI measurement */
  srchcm_gsm_meas_state_enum_type gsm_rssi_meas_state;
  /* indicate the state of the GSM BSIC identification */
  srchcm_gsm_meas_state_enum_type gsm_bsic_id_state;
  /* indicate the state of the GSM BSIC verification */
  srchcm_gsm_meas_state_enum_type gsm_bsic_reconf_state;

  /* GSM measuerement call back funtion */
  SRCHGSM_CMD_RESULT_POLL_CB_FUNC_TYPE *pwr_meas_poll_cb_func;
  SRCHGSM_CMD_RESULT_POLL_CB_FUNC_TYPE *acq_poll_cb_func;
  SRCHGSM_CMD_RESULT_POLL_CB_FUNC_TYPE *sch_decode_meas_poll_cb_func;
  SRCHGSM_CMD_RESULT_POLL_CB_FUNC_TYPE *meas_poll_cb_func;

  /* GL1 init pending call back function */
  SRCHGSM_GL1_INIT_PENDING_CB_FUNC_TYPE *gl1_init_pending_cb_func;

  /* Cmd cleanup pre call back function */
  SRCHGSM_CMD_CLEANUP_PRE_CB_FUNC_TYPE *cmd_cleanup_pre_cb_func;

  /* Cmd cleanup poll call back function */
  SRCHGSM_CMD_CLEANUP_POLL_CB_FUNC_TYPE *cmd_cleanup_poll_cb_func;

  /* GSM RSSI scan	result buffer */
  gl1_hw_measurement_T rssi_result_buf[SRCHCM_MAX_PWR_MEAS_BURST_PER_GSM_FR];

/* GAP parameters in GSM time units */
  srchgsm_gap_param_gsm_struct_type gap_gsm_params;

  /* GSM command buffer parameters. */
  srchgsm_mdsp_cmd_buf_struct_type mdsp_cmd_buf_params;
  uint8 srchgsmdrv_fach_events_received[MCALWCDMA_SRCH_CM_MAX_NUM_CMQ];
} srchgsmdrv_int_cntrl_params_type;

/* GSM measurement related parameters that are accessed external to SRCHGSMDRV */
typedef enum
{
  INVALID_IDX,
  BUFFER_0,
  BUFFER_1
}srchgsmdrv_meas_idx_mapping;

typedef struct
{
  /* keeps track of what state gl1 sw initialization is in, including whether it 
   is off completely.  (gl1 needs to be initialized for W2G searches) */
  srchgsm_gl1_init_state_enum_type gl1_init_state;

  /* GSM CM measurement related advanced processing */
  srchgsm_meas_info_struct_type srchgsm_gsm_meas_info[SRCHCM_GSM_ADV_INFO_BUF_COUNT];

/* GSM command queue to hold the cmds till they are sent to GL1 
    at the correct GFN in the GSTMR. context. */
  srchgsm_send_cmd_seq_type srchgsm_cmd_seq[SRCHGSM_SEQ_MAX_CMD];
}srchgsmdrv_ext_cntrl_params_mdump_struct_type;

typedef struct
{
  /* Create W2G critical section */
  rex_crit_sect_type w2g_crit_sect;
  /* this critical section will ensure mutual exclusion of calls for init and 
   de-init gl1 search drivers.  If locking both this and ext_srchgsmdrv_cntrl->w2g_crit_sect, always
   lock this one first (and unlock this one last when finished). */
  rex_crit_sect_type w2g_gl1_init_crit_sect;

  srchgsmdrv_ext_cntrl_params_mdump_struct_type srchgsmdrv_ext_cntrl_params_mdump;

/* W2G measurement result related information */
  srchgsm_meas_result_struct_type srchgsm_meas_result;
  srchgsmdrv_meas_idx_mapping  meas_result_idx[SRCHCM_GSM_ADV_INFO_BUF_COUNT];
} srchgsmdrv_ext_cntrl_params_type;

extern srchgsmdrv_ext_cntrl_params_type srchgsmdrv_ext_cntrl_params[WCDMA_NUM_SUBS];


#define W2G_INTLOCK()  REX_ISR_LOCK(&srchgsmdrv_ext_cntrl_params[wsub_id].w2g_crit_sect)
#define W2G_INTFREE()  REX_ISR_UNLOCK(&srchgsmdrv_ext_cntrl_params[wsub_id].w2g_crit_sect)


#define W2G_GSM_STATE_INTLOCK() rex_enter_crit_sect(&srchgsmdrv_ext_cntrl_params[wsub_id].w2g_gl1_init_crit_sect)
#define W2G_GSM_STATE_INTFREE() rex_leave_crit_sect(&srchgsmdrv_ext_cntrl_params[wsub_id].w2g_gl1_init_crit_sect)

/* GSM init is done every time before triggering GSM search for DSDS.
 * So account for time taken for GSM initializations when triggering GSM search.
 */

#define SRCHGSM_GSM_INIT_DELAY(val) \
  do {  \
    if((WL1_IN_DS_MODE()) && \
       (srchgsmdrv_ext_cntrl_params[wsub_id].srchgsmdrv_ext_cntrl_params_mdump.gl1_init_state != SRCHGSM_GL1_ON) \
      )	   \
    {  \
      val = 2; \
    } \
    else \
    {  \
      val = 0; \
    } \
  } while(0)
  

/* =======================================================================
**                        Function Declarations
** ======================================================================= */
extern void srchgsmdrv_int_cntrl_params_init();
extern void srchgsmdrv_ext_cntrl_params_init();
 
/* Initialize the GL1 init state */
extern void srchgsm_drv_init_gl1_state ( wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_drv_init
         srchgsm_drv_init_on_resume

DESCRIPTION
  This function initializes the variables related to this module.

DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/

extern void srchgsm_drv_init_on_resume( wsub_id_e_type wsub_id);
extern void srchgsm_drv_init( wsub_id_e_type wsub_id);

#ifndef FEATURE_CM_UNIT_TEST
/*===========================================================================
FUNCTION srchgsm_drv_check_validity 

DESCRIPTION
  This function checks the validity of the RF constants being passed for
  W2G timeline according to specs.

DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/

extern void srchgsm_drv_check_validity( wsub_id_e_type wsub_id);
#endif
/*===========================================================================
FUNCTION srhcm_gsm_frame_tick_handler

DESCRIPTION
  This function implements the GSM frame tick hanldler. This function must
  be register to GSM timer module to be called back every GSM frame. It do
  the following actions:
  - Get the GSM time QS and frame number
  - Sequence the command that can be sent in this frame
  - Call the result poll call back function.

DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/

extern void srhcm_gsm_frame_tick_handler(
   #ifdef FEATURE_DUAL_SIM
   sys_modem_as_id_e_type as_id
   #endif
   );

/*===========================================================================
FUNCTION srchgsm_update_gsm_frame_num

DESCRIPTION
  This function is a utility function to update the current GFN.

DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/

extern void srchgsm_update_gsm_frame_num (uint8 gfn, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchcm_gsm_get_gfn

DESCRIPTION
  This function is a utility function to return current GFN.

DEPENDENCIES
  None

RETURN VALUE
  Current GSM frame number.

SIDE EFFECTS
  None
===========================================================================*/

extern uint8 srchcm_gsm_get_gfn( wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchcm_gsm_update_gap_params_to_gsm_tl

DESCRIPTION
  This function convert the WCDMA compressed gap parameters to GSM timeline.
  The GSM gap is the GAP in which measurement can be done. It excludes the UL
  transmission time and DL pilot time in the start and end of gap respectively.
  
  See description in function comments.

DEPENDENCIES
  None

RETURN VALUE
  Compressed mode GAP in GSM time info structure pointer.

SIDE EFFECTS
  None
===========================================================================*/

extern srchgsm_gap_param_gsm_struct_type* srchcm_gsm_update_gap_params_to_gsm_tl(
  /* WCDMA frame offset from the GAP. If 0 indicate that GAP is in the next frame */
  uint8 wcdma_frame_offset,
  /* GAP start inf slot number in WCDMA slot unit */
  uint8 gap_start_slot_num,
  /* GAP length in WCDMA slot units */
  uint8 gap_length, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_send_cmd

DESCRIPTION
  This function sends the GSM command. It checks for the GSM frame number of
  the command to be sent. If this is the frame in which the command can be sent
  then immediately send it other wise it queues the command in comand Q.
  
DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/

extern void srchgsm_send_cmd(
  /* GSM Command type */
  srchgsm_cmd_type_enum_type cmd_type,
  /* GSM command pointer */
  void* gsm_mdsp_cmd_ptr,
  /* call back function after command has been sent */
  SRCH_GSM_CMD_SENT_POST_CB_FUNC_TYPE* cmd_sent_post_cb_func, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_send_cmd

DESCRIPTION
  This function sends the GSM command immediately. It calls appropriate
  forwarding function in this module to send the command to GSM mDSP drivers.
  
DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/

extern void srchgsm_send_cmd_now(
  /* GSM Command type */
  srchgsm_cmd_type_enum_type cmd_type,
  /* GSM command pointer */
  void* gsm_mdsp_cmd_ptr,
  /* call back function after command has been sent */
  SRCH_GSM_CMD_SENT_POST_CB_FUNC_TYPE* cmd_sent_post_cb_func, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_prebuild_startup_cleanup_scripts

DESCRIPTION
  This function prebuilds the startup and cleanup scripts for W2G CM measurement.
  
DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/

extern void srchgsm_prebuild_startup_cleanup_scripts(
  /* startup command parameters */
  void *cm_startup_cmd_ptr,
  wsub_id_e_type wsub_id
);

/*===========================================================================
FUNCTION srchgsm_send_gsm_cm_startup_cmd

DESCRIPTION
  This function sends GSM CM startup command.
  
DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/

extern void srchgsm_send_gsm_cm_startup_cmd(
  /* startup command parameters */
  srchgsm_startup_cmd_param_struct_type *cm_startup_cmd_ptr, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_send_gsm_cm_cleanup_cmd

DESCRIPTION
  This function sends GSM CM cleanup command.
  
DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/

extern void srchgsm_send_gsm_cm_cleanup_cmd(
  /* Cleanup command parameters */
  srchgsm_cleanup_cmd_param_struct_type *cm_cleanup_cmd_ptr, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_send_pwr_meas_cmd

DESCRIPTION
  This function sends GSM RSSI measure command.
  
DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/

extern void srchgsm_send_pwr_meas_cmd(
  /* RSSI meas command parameters */
  srchgsm_pwr_scan_cmd_param_struct_type *pwr_meas_cmd_ptr, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_set_pwr_meas_result_poll_cb_func

DESCRIPTION
  This function set the RSSI scan result poll call back function
  
DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/

extern void srchgsm_set_pwr_meas_result_poll_cb_func(
  /* RSSI scan result poll call back function */
  SRCHGSM_CMD_RESULT_POLL_CB_FUNC_TYPE *cb_func, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_read_pwr_meas_result

DESCRIPTION
  This function reads the RSSI meas result from GSM driver
  
DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/

extern void srchgsm_read_pwr_meas_result(
  /* number of RSSI scan burst */
  uint8 num_bursts,
  /* RSSI measured values */
  int16 *rssi_meas_buffer,
  /* lna state values */
  uint8 *lna_state_buffer,
  /* GSM HW frame layer tags */
  gl1_hw_rx_tags_type *tags,
  /*schedule error during rf script builiding*/
  boolean *schedule_error,
  /* command index used for logging */
  uint8 cmd_index,
  wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_send_acq_start_cmd

DESCRIPTION
  This function sends ACQ start command.
  
DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/

extern void srchgsm_send_acq_start_cmd(
  /* FCCH ACQ start command parameters */
  srchgsm_start_acq_cmd_param_struct_type *acq_start_cmd_ptr, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_send_acq_stop_cmd

DESCRIPTION
  This function sends ACQ stop command.
  
DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/

extern void srchgsm_send_acq_stop_cmd(
  /* FCCH ACQ stop command parameters */
  srchgsm_stop_acq_cmd_param_struct_type *acq_stop_cmd_ptr, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_set_acq_result_poll_cb_func

DESCRIPTION
  This function sets the FCCH tone detect result poll call back function.
  
DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/

extern void srchgsm_set_acq_result_poll_cb_func(
  /* FCCH tone detect result poll call back function */
  SRCHGSM_CMD_RESULT_POLL_CB_FUNC_TYPE *cb_func, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_send_sch_decode_cmd

DESCRIPTION
  This function send GSM SCH decode async read command.
  
DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/

extern void srchgsm_send_sch_decode_cmd(
  /* SCH decode command parameter */
  srchgsm_sch_decode_cmd_param_struct_type *sch_decode_cmd_ptr, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_set_sch_decode_search_width

DESCRIPTION
  This function sets the SCH decode search width. This function should be
  called after calling srchgsm_send_sch_decode_cmd.
  Function srchgsm_send_sch_decode_cmd calls gl1_hw_rx_async_sch_burst which
  sets the default SCH search width.
  
DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/

extern void srchgsm_set_sch_decode_search_width(
  /* number of Symbols for SCH to decode */
  uint16 search_width_qs,
  wsub_id_e_type wsub_id
  );

/*===========================================================================
FUNCTION srchgsm_set_acq_result_poll_cb_func

DESCRIPTION
  This function sets the SCH decode result poll call back function.
  
DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/

extern void srchgsm_set_sch_decode_result_poll_cb_func(
  /* SCH decode result poll call back function */
  SRCHGSM_CMD_RESULT_POLL_CB_FUNC_TYPE *cb_func, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_set_result_poll_cb_func

DESCRIPTION
  This function set the results call back function to call all the search result poll function
  
DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/

extern void srchgsm_set_result_poll_cb_func(
  /* Call back function to call poll result function*/
  SRCHGSM_CMD_RESULT_POLL_CB_FUNC_TYPE *cb_func, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION      SRCHGSM_GET_PWR_MEAS_RESULT

DESCRIPTION
  This function is called from the call back poll function called from 
  the GSM frame tick handler to get the RSSI measurement result. 
  While triggering the RSSI measurement, the result processing parameters are updated. 
  In that, GFN of the current command to poll indicates the GFN when the results are 
  available.

  Once the GFN matches the GFN for which the command is to be read, it calls 
  the GL1 API function to read the RSSI result for that command. If all the
  command results are available, it then calls the function to process the RSSI
  result.

DEPENDENCIES
  None

RETURN VALUE
  TRUE if results for all the PWR MSR commands have been received
  FALSE in any other case

SIDE EFFECTS
  None
===========================================================================*/

extern boolean srchgsm_get_pwr_meas_result (uint8 cur_gfn, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION      SRCHGSM_GET_TONE_DETECT_RESULT

DESCRIPTION
  This function is called from the call back poll function called from 
  the GSM frame tick handler to get the BSIC ID Tone detectection result. 
  While triggering the BSIC ID measurement, the result processing parameters are updated. 
  In that, GFN of the current command to poll indicates the GFN when the results are 
  available.

  Once the GFN matches the GFN for which the command is to be read, it calls 
  the GL1 API function to read the result for that command. 

DEPENDENCIES
  None

RETURN VALUE
  Tone detection result

SIDE EFFECTS
  None
===========================================================================*/

extern boolean srchgsm_get_tone_detect_result 
(
  /* Current GSM frame number */
  uint8 cur_gfn,
  /* GSM ARFCN  */
  W_ARFCN_T arfcn,
  /* FCCH results from GL1 */
  gl1_hw_cm_tone_results_t *fcch_tone_detected_results,
  /* Tone Detect Result */
  boolean *tone_detected
, wsub_id_e_type wsub_id
);

/*===========================================================================
FUNCTION      SRCHGSM_GET_SCH_DECODE_RESULT

DESCRIPTION
  This function is called from the call back poll function called from 
  the GSM frame tick handler to get the BSIC ID SCH decode result. 
  While triggering the BSIC ID measurement, the result processing parameters are updated. 
  In that, GFN of the current command to poll indicates the GFN when the results are 
  available.

  Once the GFN matches the GFN for which the command is to be read, it calls 
  the GL1 API function to read the result for that command. 

DEPENDENCIES
  None

RETURN VALUE
  SCH decode result
  
SIDE EFFECTS
  None
===========================================================================*/
extern boolean srchgsm_get_sch_decode_result
(
  uint8 cur_gfn,
  gl1_hw_cm_sch_results_t *sch_detected_results,
  boolean *result,
  uint8 srch_type,
  wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION      srchgsm_get_cm_sch_decode_result

DESCRIPTION
  This function is called from the call back poll function called from 
  the GSM frame tick handler to get the BSIC ID SCH decode result in DCH state. 
  While triggering the BSIC ID measurement, the result processing parameters are updated. 
  In that, GFN of the current command to poll indicates the GFN when the results are 
  available.

  Once the GFN matches the GFN for which the command is to be read, it calls 
  the GL1 API function to read the result for that command. 

DEPENDENCIES
  None

RETURN VALUE
  SCH decode result

SIDE EFFECTS
  None
===========================================================================*/

extern boolean srchgsm_get_cm_sch_decode_result
(
  uint8 cur_gfn,
  gl1_hw_cm_sch_results_t *sch_decoded_results,
  boolean *result,
  uint8 srch_type,
  wsub_id_e_type wsub_id);


/*===========================================================================
FUNCTION      srchgsm_check_forbidden_tone

DESCRIPTION
  This function is called from the Tone detect result poll function to check 
  whether the detected tone was forbidden before. This function is called in 
  DCH and FACH states.

DEPENDENCIES
  None

RETURN VALUE
  TRUE if tone detected is not forbidden
  FALSE in any other case

SIDE EFFECTS
  None
===========================================================================*/

extern boolean srchgsm_check_forbidden_tone 
(
  int32 tone_detect_offset, 
  uint8 num_forbidden_offset
, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_check_mdsp_status

DESCRIPTION
  This function returns the sleep status of GSM mDSP.
  
DEPENDENCIES
  None

RETURN VALUE
  TRUE if mDSP is awake
  FALSE otherwise

SIDE EFFECTS
  None
===========================================================================*/
extern boolean srchgsm_check_mdsp_status( wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_check_mdsp_suspend_after_cleanup

DESCRIPTION
  This function checks if GSM mDSP is already sent to suspend. If not, it 
  sets a callback to keep polling until GSM mDSP is finished with suspend cmd. 
  This is only used during IDLE W2G. 
  
DEPENDENCIES
  None

RETURN VALUE
  TRUE of FALSE based on mDSP suspend

SIDE EFFECTS
  None
===========================================================================*/
extern boolean srchgsm_check_mdsp_suspend_after_cleanup(
  /* Cmd cleanup poll call back function */
  SRCHGSM_CMD_CLEANUP_POLL_CB_FUNC_TYPE *cb_func, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_waiting_on_gfw_suspend

DESCRIPTION
  This function tells if the SRCH GSM DRV is waitng on GFW to get suspended.
  
DEPENDENCIES
  None

RETURN VALUE
  TRUE if polling cb registered with SRCHGSMDRV
  FALSE otherwise

SIDE EFFECTS
  None
===========================================================================*/
extern boolean srchgsm_waiting_on_gfw_suspend(wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_set_cleanup_poll_cb_func

DESCRIPTION
  This function sets the a callback to keep polling until GSM mDSP is 
  finished with suspend cmd. This is used during FACH W2G module cleanup. 
  
DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/
extern void srchgsm_set_cleanup_poll_cb_func(
  /* Cmd cleanup poll call back function */
  SRCHGSM_CMD_CLEANUP_POLL_CB_FUNC_TYPE *cb_func, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_check_pending_cmd_q

DESCRIPTION
  This function checks cmd Q for any pending cmd that need not be sent
  as the part of cleanup.
  
DEPENDENCIES
  None

RETURN VALUE
  TRUE of FALSE based on remaining pending commands

SIDE EFFECTS
  None
===========================================================================*/

extern boolean srchgsm_check_pending_cmd_q(
  /* Cmd cleanup poll call back function */
  SRCHGSM_CMD_CLEANUP_POLL_CB_FUNC_TYPE *cb_func, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_clean_pending_cmd_q

DESCRIPTION
  This function cleans cmd Q for any pending cmd that need not be sent
  as the part of cleanup.
  
DEPENDENCIES
  None

RETURN VALUE
  TRUE of FALSE based on remaining pending commands

SIDE EFFECTS
  None
===========================================================================*/
extern void srchgsm_clean_pending_cmd_q( wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_set_cmd_cleanup_pre_cb

DESCRIPTION
  This function sets the callback function for srchgsm_cmd_cleanup_pre_cb_func.
  
DEPENDENCIES
  None

RETURN VALUE
  TRUE of FALSE based on remaining pending commands

SIDE EFFECTS
  None
===========================================================================*/
extern void srchgsm_set_cmd_cleanup_pre_cb(
  /* Cmd cleanup pre call back function */
  SRCHGSM_CMD_CLEANUP_PRE_CB_FUNC_TYPE *cb_func, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_init_gsm

DESCRIPTION
  This function initializes GSM for W2G functionality.
  
DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/
extern void srchgsm_init_gsm(
  /* Ptr to task waiting for this to be done */
  rex_tcb_type*  task_ptr,
  /* Signal handler */
  void           (* task_wait_handler)(rex_sigs_type),
  /* Timeout signal 1 */
  rex_sigs_type  task_wait_sig,
  /* Timeout signal 2 */
  rex_sigs_type  task_wait_sig_1);

/*===========================================================================
FUNCTION srchgsm_get_error_status

DESCRIPTION
  This function returns the error status of GSM RxFE.
  
DEPENDENCIES
  None

RETURN VALUE
  TRUE means it's bad
  FALSE means it's good

SIDE EFFECTS
  None
===========================================================================*/
extern boolean srchgsm_get_error_status( wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_set_error_status

DESCRIPTION
    This function sets the error status of GSM RxFE.
  
DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/
extern void srchgsm_set_error_status(boolean status, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_edge_block_cb

DESCRIPTION
    This function is a callback from MCPM when a GSM EDGE core reset happens.
  
DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/
extern void srchgsm_edge_block_cb(wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_init_gl1

DESCRIPTION
  This function starts off a delayed/parallelized version of the gsm 
  initializations needed to handle GSM measurements while in WCDMA.  This 
  should save ~20 ms from wl1m_init, which is where a blocking call used to 
  happen.
  
DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  
===========================================================================*/
extern void srchgsm_init_gl1( wsub_id_e_type wsub_id);


/*===========================================================================
FUNCTION srchgsm_gl1_hw_cm_gsm_init

DESCRIPTION
  This function starts of the gsm 
  initializations needed to handle GSM measurements while in WCDMA.  
  
DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  
===========================================================================*/
extern void srchgsm_gl1_hw_cm_gsm_init( wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_process_gl1_init

DESCRIPTION
  This function sets GL1 init state to ON. W2G search commands can be issued now.
  
DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  
===========================================================================*/
extern void srchgsm_process_gl1_init( wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_deinit_gl1

DESCRIPTION
  Used to de-initialize the gl1 functions needed by WCDMA for W2G searches
  
DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  
===========================================================================*/
extern void srchgsm_deinit_gl1( wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_init_gl1_now

DESCRIPTION
  This function initializes GL1 SW so WCDMA can make use of GSM function calls 
  for GSM searches.  GSM must have been initialized before anything else can 
  take place for W2G, so think of calling this as a pre-requisite.

  Currently this is called shortly after wl1m_init() in ISR context.
  
DEPENDENCIES
  Must be called only from seq.c's seq_generic_event_handler() function.  
  Cannot be called generically.

RETURN VALUE
  None

SIDE EFFECTS
  Initializes GL1 sw so WCDMA can search for GSM cells.
===========================================================================*/
extern void srchgsm_init_gl1_now(void);

/*===========================================================================
FUNCTION srchgsm_query_ready_for_cmds

DESCRIPTION
  This function lets parent-modules poll whether srchgsmdrv is ready to accept 
  commands to be sent to GL1.  Parent-modules should check this function before
  sending any commands.  Otherwise srchgsmdrv may crash if it is sent a command
  before it is ready.
  
DEPENDENCIES
  Should only be called by code that runs between wl1m_init and wl1m_deinit.  
  Additionally the code that sends commands must only be active during this 
  time.  Otherwise it's possible to have a scenario where this is checked just 
  before wl1m_deinit, and then the command can come after the wl1m_deinit.  
  This will cause srchgsmdrv to crash.

RETURN VALUE
  Returns TRUE if srchgsmdrv is ready for commands to gsm
  Returns FALSE if srchgsmdrv is NOT ready for commands yet

SIDE EFFECTS
  None
===========================================================================*/
extern boolean srchgsm_query_ready_for_cmds( wsub_id_e_type wsub_id);

extern boolean srchgsm_gl1_init_pending(SRCHGSM_GL1_INIT_PENDING_CB_FUNC_TYPE *cb_func, wsub_id_e_type wsub_id);


/*===========================================================================
FUNCTION srchgsm_is_gl1_init_ongoing

DESCRIPTION
  This function gives information if GL1 initialization is ongoing. 
  
DEPENDENCIES  
  None
  
RETURN VALUE
  Returns TRUE if GL1 initialization is ongoing
  Returns FALSE if GL1 initialization is not ongoing

SIDE EFFECTS
  None
===========================================================================*/
extern boolean srchgsm_is_gl1_init_ongoing (wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION SRCHGSM_SEND_CMD_HANDLER

DESCRIPTION
  This function will handle the timing when we send cmd to FW. If frame num of 
  the cmd is not equal to curr GFN, we have to set a critical section before 
  sending the cmd to a queue for ISR. While frame number of the cmd now is at 
  curr GFN, we need to send it right away to FW without locking it. 

DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/
extern void srchgsm_send_cmd_handler(
  /* Num of cmds in the list */
  uint8 num_cmd, 
  /* List of cmd seqeunce */
  srchgsm_send_cmd_seq_type *cmd_seq, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchcm_get_cur_gsm_rssi_meas_state

DESCRIPTION
  This function returns the current RSSI measurement state.

DEPENDENCIES
  None

RETURN VALUE
  RSSI measuremnt state.

SIDE EFFECTS
  None
===========================================================================*/
extern srchcm_gsm_meas_state_enum_type srchcm_get_cur_gsm_rssi_meas_state( wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchcm_set_gsm_rssi_meas_state

DESCRIPTION
  This function sets the RSSI meas state

DEPENDENCIES
  None

RETURN VALUE
  RSSI measuremnt state.

SIDE EFFECTS
  None
===========================================================================*/
extern void srchcm_set_gsm_rssi_meas_state(
  /* RSSI meas state */
  srchcm_gsm_meas_state_enum_type state, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchcm_get_cur_gsm_bsic_id_state

DESCRIPTION
  This function returns the current BSIC Id measurement state.

DEPENDENCIES
  None

RETURN VALUE
  BSIC Id measuremnt state.

SIDE EFFECTS
  None
===========================================================================*/
extern srchcm_gsm_meas_state_enum_type srchcm_get_cur_gsm_bsic_id_state( wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchcm_set_gsm_bsic_id_meas_state

DESCRIPTION
  This function sets the BSIC Id measurement state.

DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/
extern void srchcm_set_gsm_bsic_id_meas_state(
  /* BSIC Id measurement state */
  srchcm_gsm_meas_state_enum_type state, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchcm_get_cur_gsm_bsic_reconf_state

DESCRIPTION
  This function returns the current BSIC reconf measurement state.

DEPENDENCIES
  None

RETURN VALUE
  BSIC reconf measuremnt state.

SIDE EFFECTS
  None
===========================================================================*/
extern srchcm_gsm_meas_state_enum_type srchcm_get_cur_gsm_bsic_reconf_state( wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchcm_set_gsm_bsic_reconf_meas_state

DESCRIPTION
  This function sets the BSIC reconf measurement state.

DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/
extern void srchcm_set_gsm_bsic_reconf_meas_state(
  /* BSIC Id reconf state */
  srchcm_gsm_meas_state_enum_type state, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_query_w2g_dch_fach_meas_ongoing

DESCRIPTION
  This function is to determine if W2G DCH or FACH meas is in the progress.
  
RETURN VALUE
  NONE
  
SIDE EFFECTS
=============================================================================*/
boolean srchgsm_query_w2g_dch_fach_meas_ongoing(wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_update_startup_cmd_params

DESCRIPTION
  This function updates the W2G startup command parameters. It puts the CM start up
  command SRCHCM_GSM_CM_START_UP_TIME_QS before the gap startup time. It
  also adjusts the command frame and QS offset based of GSM FTSM.

DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/
extern void srchgsm_update_startup_cmd_params(
  /* gap parameters in GSM time units */
  srchgsm_gap_param_gsm_struct_type *gap_param_for_gsm,
  /* CM startup command parameters */
  srchgsm_startup_cmd_param_struct_type *startup_cmd_params,
  /* TRUE for idle mode. FALSE for FACH/DCH*/
  boolean is_idle_mode,
  wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_update_cleanup_cmd_params

DESCRIPTION
  This function updates the CM cleanup parameters. It set the cleanup command
  to be sent at the clean up GFN passed to the function and adjust the command
  frame and QS offset for FTMS.

DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/

extern void srchgsm_update_cleanup_cmd_params(
  /* GFN at which cleanup command should go  */
  uint8 cleanup_frame_num,
  /* CM cleanup offset. This can be larger than QS per frame */
  uint16 cleanup_offset,
  /* clean up command parameters */
  srchgsm_cleanup_cmd_param_struct_type *cleanup_cmd_params,
  wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_update_pwr_msr_cmd_params

DESCRIPTION
  This function updates the GSM RSSI burst parameters. 

DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/

extern uint8 srchgsm_update_pwr_msr_cmd_params(
  /* gap parameters in GSM time units */
  srchgsm_gap_param_gsm_struct_type *gap_param_for_gsm,
  /* GSM meas info struct pointer */
  srchgsm_meas_info_struct_type *meas_info,
  /* Count of GSM neighbor cells */
  uint8 gsm_cell_count,
  wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_calculate_num_gsm_rssi_meas

DESCRIPTION
  This function figures out how many rssi burst measurements can be performed 
  in a gap.

DEPENDENCIES
  None

RETURN VALUE
  The number of bursts we can do in the gap.

SIDE EFFECTS
  None
===========================================================================*/
extern uint8 srchgsm_calculate_num_gsm_rssi_meas(
  /* The qs offset to the start of the search gap, with respect to the previous GSM frame boundary */
  uint16 pwr_meas_start_offset_qs, 
  /* the size of the search window in qs */
  uint16 gap_win_size_qs, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_update_gsm_rssi_cmd_params

DESCRIPTION
  This function update the RSSI scan command buffre. The required number of RSSI
  scan may span multiple GSM frames. This function checks the location of each
  burst in GAP and put the burst in their respective command buffer.

DEPENDENCIES
  None

RETURN VALUE
  Number of RSSI scan command updated.

SIDE EFFECTS
  None
===========================================================================*/
extern uint8 srchgsm_update_rssi_cmd_params(
  /* Number of burst to be programmed in this GAP */
  uint8 *num_bursts,
  /* RSSI scan measurement parameters info */
  srchgsm_pwr_scan_params_struct_type *pwr_scan_params,
  /* RSSI scan GSM command parameters */
  srchgsm_pwr_scan_cmd_param_struct_type *pwr_cmd_params,
  /* This gap is used for BSIC ID (SCH) or BSIC RC */
  boolean is_bsic_gap,
  wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_update_bsic_id_acq_start_cmd_params

DESCRIPTION
  This function sets the FCCH and FCCH+SCH ACQ start command parameters. 
  ACQ start command is set for doing ACQ at the start of ACQ window .

DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/

extern void srchgsm_update_bsic_id_acq_start_cmd_params(
  /* BSIC Id parameters */
  srchgsm_bsic_id_params_struct_type *bsic_id_params,
  /* ACQ start cmd params */
  srchgsm_start_acq_cmd_param_struct_type *acq_start_cmd_params,
  /* Indicate if this is only FCCH ACQ or FCCH+SCH ACQ */
  boolean sch_decode, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_update_bsic_id_acq_stop_cmd_params

DESCRIPTION
  This function sets the ACQ stop command parameters. 
  ACQ stop command is set for the end of the ACQ window .

DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/

extern void srchgsm_update_bsic_id_acq_stop_cmd_params(
  /* BSIC Id parameters */
  srchgsm_bsic_id_params_struct_type *bsic_id_params,
  /* FCCH ACQ start cmd params */
  srchgsm_start_acq_cmd_param_struct_type *acq_start_cmd_params,
  /* FCCH ACQ stop cmd params */
  srchgsm_stop_acq_cmd_param_struct_type *acq_stop_cmd_params, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_update_bsic_id_sch_dec_cmd_params

DESCRIPTION
  This function sets the SCH decode command parameter.

DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/
extern void srchgsm_update_bsic_id_sch_dec_cmd_params(
  /* BSIC Id parameters */
  srchgsm_bsic_id_params_struct_type *bsic_id_params,
  /* SCH decode cmd params */
  srchgsm_sch_decode_cmd_param_struct_type *sch_decode_params,
  /* sch decode command index */
  uint8 command_idx,
  /* TRUE for idle mode. FALSE for FACH/DCH*/
  boolean is_idle_mode,
  wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_update_bsic_reconf_sch_dec_cmd_params

DESCRIPTION
  This function sets the SCH decode command parameter for BSIC reconf.

DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/
extern void srchgsm_update_bsic_reconf_sch_dec_cmd_params(
  /* BSIC Id parameters */
  srchgsm_bsic_reconf_params_struct_type *bsic_reconf_params,
  /* SCH decode cmd params */
  srchgsm_sch_decode_cmd_param_struct_type *sch_decode_params,
  /* Command index */
  uint8 command_idx, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_update_gsm_band_info_list

DESCRIPTION
  

DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/

extern void srchgsm_update_gsm_band_info_list(
  srchgsmdrv_bandlist_update_action_enum_type action,
  W_ARFCN_T *arfcn, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION 
         srchgsm_update_fcch_acq_result
         srchgsm_rssi_result_get_num_cmds
         srchgsm_rssi_result_get_result_posted
         srchgsm_rssi_result_get_num_bursts
         srchgsm_rssi_result_get_rssi_dbx16
         srchgsm_rssi_result_get_result_frame_num

DESCRIPTION
  These SRCHGSMDRV API functions are for the higher modules like 
  SRCHCMMEAS, SRCHFACH and SRCHCRGSM to access and update 
  GSM measurement result structure elements 

DEPENDENCIES
  The caller of these functions must lock the W2G mutex.

RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/
extern void srchgsm_update_fcch_acq_result(srchgsm_fcch_acq_result_struct_type * result, wsub_id_e_type wsub_id);
extern uint8 srchgsm_rssi_result_get_num_cmds ( wsub_id_e_type wsub_id);
extern boolean srchgsm_rssi_result_get_result_posted( wsub_id_e_type wsub_id);
extern uint8 srchgsm_rssi_result_get_num_bursts(uint8 cmd_idx, wsub_id_e_type wsub_id);
extern uint16 srchgsm_rssi_result_get_rssi_dbx16(uint8 cmd_idx, uint8 burst_idx, wsub_id_e_type wsub_id);
extern uint8 srchgsm_rssi_result_get_result_frame_num(uint8 cmd_idx, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION SRCHGSM_TOO_CLOSE_TO_FRAME

DESCRIPTION
  This function returns TRUE if we are less than 3ms from the GFN boundary
  when the startup GFN is the current GFN.

DEPENDENCIES
  
RETURN VALUE
  TRUE: not enough time for prebuild
  FALSE: enough time for prebuild

SIDE EFFECTS
  None.
===========================================================================*/
boolean srchgsm_too_close_to_frame(uint8 start_frame_num, uint16 offset_qs_to_start, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION SRCHGSM_GAP_END_TUNE_DONE

DESCRIPTION
  This function is a handler to handle W2G CM gap end process. 
  Send WRM measurement complete here.

DEPENDENCIES
  
RETURN VALUE
  TRUE if gap end is complete

SIDE EFFECTS
  None.
===========================================================================*/
extern boolean srchgsm_gap_end_tune_done(uint8 evt_id, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_waiting_for_gap_end

DESCRIPTION
  This function checks if srchfach_unreserve or AGC tune done have been 
  received for the last FMO gap.

DEPENDENCIES
  
RETURN VALUE
  FALSE - Done with gap. 
  TRUE - Still waiting for srchfach_unreserve or AGC tune done at the end of the gap

SIDE EFFECTS
  None.
===========================================================================*/
extern boolean srchgsm_waiting_for_gap_end(wsub_id_e_type wsub_id);

extern void srchgsm_clear_fach_events_received (wsub_id_e_type wsub_id);


/*===========================================================================
FUNCTION srchgsm_drv_terminate_gsm

DESCRIPTION
  This function deregister gsm handle if it already register, terminate GSM and disable gsm clock.
  Will be called during state transition either from FACH or DCH.
  It won't be called if next state is SUSPEND i.e. from DCH->SUSPEND or FACH->SUSPEND, as this could be handover or reselction case.
  And we don't want to lose on acquired information.
  
DEPENDENCIES
  None

RETURN VALUE
  None

SIDE EFFECTS
  
===========================================================================*/
extern void srchgsm_drv_terminate_gsm(wsub_id_e_type wsub_id);

#ifdef FEATURE_WCDMA_QSH_DUMP
/*===========================================================================
FUNCTION srchgsm_get_gsmdrv_state_info

DESCRIPTION
  This function is to collect gsm meas driver state info for debugging.  

DEPENDENCIES  
  None
  
RETURN VALUE
  None

SIDE EFFECTS
  None
===========================================================================*/
extern void srchgsm_get_gsmdrv_state_info(void *debug_buf, wsub_id_e_type wsub_id);

/*===========================================================================
FUNCTION srchgsm_query_w2g_meas_ongoing

DESCRIPTION
  This function is to determine if W2G meas is in the progress for
  specified call process state.
 
RETURN VALUE
  NONE
  
SIDE EFFECTS
=============================================================================*/
extern boolean srchgsm_query_w2g_meas_ongoing(boolean wl1_in_idle, wsub_id_e_type wsub_id);
#endif /* FEATURE_WCDMA_QSH_DUMP*/

#ifdef FEATURE_CM_UNIT_TEST
#error code not present
#endif

#ifdef FEATURE_QSH_MDUMP
/*===========================================================================
FUNCTION wl1_qsh_mdump_collect_irat_srchgsm

DESCRIPTION
  This is a minidump function for dumping the selected IRAT global variables for W2G searches

DEPENDENCIES
  NONE

RETURN VALUE
  None
  
SIDE EFFECTS
  None
===========================================================================*/
extern QSH_MDUMP_FN_ATTR void wl1_qsh_mdump_collect_irat_srchgsm(wsub_id_e_type wsub_id);
#endif

#endif /* SRCHGSMDRV_H */
