#ifndef WL1HWIOIF_H
#define WL1HWIOIF_H

/*==========================================================================
             WCDMA L1 HSUPA UL ENC driver related header file

DESCRIPTION
  This file contains definition, declaration required for HSUPA UL ENC driver
  
  Copyright (c) 2006 by Qualcomm Technologies, Inc.
  All Rights Reserved.
===========================================================================*/

/*===========================================================================

                        EDIT HISTORY FOR MODULE

This section contains comments describing changes made to the module.
Notice that changes are listed in reverse chronological order.

$Header: //components/rel/wcdma.mpss/8.4.0/l1/offline/inc/wl1hwioif.h#3 $
$DateTime: 2020/01/22 08:56:27 $
$Author: pwbldsvc $

when       who     what, where, why
--------   ---     ----------------------------------------------------------
08/01/15   vr      Changes and fixes needed for ATLAS RUMI.
07/08/15   yw      Fix compile errors for BO2.1.2 branch
07/07/15   yw      Create new file for HWIO interface access (UL part)

*/


/* Register Definations*/

/*Group 1: WL1_HWIO_OUT(A,B) = WL1_HWIO_##A##_OUT(B)*/

#define WL1_HWIO_TX_GENERAL_CTL_OUT(val)                           HWIO_TX_GENERAL_CTL_OUT(val) 
#define WL1_HWIO_TX_HSDPCCH_OVSF_NUM_OUT(val)                      HWIO_TX_HSDPCCH_OVSF_NUM_OUT(val) 
#define WL1_HWIO_TX_ERAMA_INCRACC_INIT_OUT(val)                    HWIO_TX_ERAMA_INCRACC_INIT_OUT(val)
#define WL1_HWIO_TX_W_OFFL_ENC_FRAME_OUT(val)                      HWIO_TX_W_OFFL_ENC_FRAME_OUT(val)
#define WL1_HWIO_TX_PHY_CH_TYPE_OUT(val)                           HWIO_TX_PHY_CH_TYPE_OUT(val)
#define WL1_HWIO_TX_MEM_ACCESS_CFG_OUT(val)                        HWIO_TX_MEM_ACCESS_CFG_OUT(val)
#define WL1_HWIO_TX_TXC_VALID_FALL_TIME_OUT(val)                   HWIO_TX_TXC_VALID_FALL_TIME_OUT(val)
#define WL1_HWIO_TX_TEST_CTL_OUT(val)                              HWIO_TX_TEST_CTL_OUT(val)
#define WL1_HWIO_TX_EUL_ERAM_MEMORY_BANK_C1_OUT(val)               HWIO_TX_EUL_ERAM_MEMORY_BANK_C1_OUT(val)
#define WL1_HWIO_TX_EUL_INCRACC_INIT_C1_OUT(val)                   HWIO_TX_EUL_INCRACC_INIT_C1_OUT(val)
#define WL1_HWIO_TX_EUL_ERAM_MEMORY_BANK_OUT(val)                  HWIO_TX_EUL_ERAM_MEMORY_BANK_OUT(val)
#define WL1_HWIO_TX_EUL_INCRACC_INIT_OUT(val)                      HWIO_TX_EUL_INCRACC_INIT_OUT(val)
#define WL1_HWIO_TX_TEST_MEM_MODE_C1_OUT(val)                      HWIO_TX_TEST_MEM_MODE_C1_OUT(val)
#define WL1_HWIO_TX_TEST_MEM_SEL_C1_OUT(val)                       HWIO_TX_TEST_MEM_SEL_C1_OUT(val)
#define WL1_HWIO_TX_TEST_MEM_MODE_OUT(val)                         HWIO_TX_TEST_MEM_MODE_OUT(val)
#define WL1_HWIO_TX_TEST_MEM_SEL_OUT(val)                          HWIO_TX_TEST_MEM_SEL_OUT(val)
#define WL1_HWIO_TX_ERAM_AB_TRCHS_OUT(val)                         HWIO_TX_ERAM_AB_TRCHS_OUT(val)
#define WL1_HWIO_TX_TRCH_MUX_ORDER_OUT(val)                        HWIO_TX_TRCH_MUX_ORDER_OUT(val)
#define WL1_HWIO_TX_DPDCH_OVSF_NUM_OUT(val)                        HWIO_TX_DPDCH_OVSF_NUM_OUT(val)
#define WL1_HWIO_TX_DATA_SPR_FACTOR_OUT(val)                       HWIO_TX_DATA_SPR_FACTOR_OUT(val)
#define WL1_HWIO_TX_SCR_CODE_INIT_OUT(val)                         HWIO_TX_SCR_CODE_INIT_OUT(val)
#define WL1_HWIO_TX_SCR_CODE_INIT_C1_OUT(val)                      HWIO_TX_SCR_CODE_INIT_C1_OUT(val)
#define WL1_HWIO_TX_ERAMA_INCRACC_OUT(val)                         HWIO_TX_ERAMA_INCRACC_OUT(val)
#define WL1_HWIO_TX_ENC_TIMING_CTL_OUT(val)                        HWIO_TX_ENC_TIMING_CTL_OUT(val)
#define WL1_HWIO_TX_BETA_GAIN_GROUP_DLY_OUT(val)                   HWIO_TX_BETA_GAIN_GROUP_DLY_OUT(val)
#define WL1_HWIO_TX_CONDITIONING_RESET_OUT(val)                    HWIO_TX_CONDITIONING_RESET_OUT(val)
#define WL1_HWIO_TX_ROT_ANGLE_0_CTL_OUT(val)                       HWIO_TX_ROT_ANGLE_0_CTL_OUT(val)
#define WL1_HWIO_TX_ROT_ANGLE_1_CTL_OUT(val)                       HWIO_TX_ROT_ANGLE_1_CTL_OUT(val)
#define WL1_HWIO_TX_FILLER_POLARITY_OUT(val)                       HWIO_TX_FILLER_POLARITY_OUT(val)
#define WL1_HWIO_TX_UNIFIED_ENC_NUM_ACTIVE_TRCHS_OUT(val)          HWIO_TX_UNIFIED_ENC_NUM_ACTIVE_TRCHS_OUT(val)
#define WL1_HWIO_TX_UMTS_DPDCH_CTL_OUT(val)                        HWIO_TX_UMTS_DPDCH_CTL_OUT(val)
#define WL1_HWIO_TX_UNIFIED_MEM_PTR_EN_OUT(val)                    HWIO_TX_UNIFIED_MEM_PTR_EN_OUT(val)
#define WL1_HWIO_TX_UNIFIED_ENC_ERAM_INCRACC_INIT_OUT(val)         HWIO_TX_UNIFIED_ENC_ERAM_INCRACC_INIT_OUT(val)
#define WL1_HWIO_TX_UNIFIED_ERAM_CTL_OUT(val)                      HWIO_TX_UNIFIED_ERAM_CTL_OUT(val)
#define WL1_HWIO_TX_UNIFIED_ENC_ENDIAN_FRMT_CTL_OUT(val)           HWIO_TX_UNIFIED_ENC_ENDIAN_FRMT_CTL_OUT(val)
#define WL1_HWIO_TX_UNIFIED_ENC_FILLER_POLARITY_OUT(val)           HWIO_TX_UNIFIED_ENC_FILLER_POLARITY_OUT(val)
#define WL1_HWIO_TX_UMTS_DCH_RACH_LAST_OUT(val)                    HWIO_TX_UMTS_DCH_RACH_LAST_OUT(val)
#define WL1_HWIO_TX_UNIFIED_ENC_OFFL_ENC_FRAME_OUT(val)            HWIO_TX_UNIFIED_ENC_OFFL_ENC_FRAME_OUT(val)
#define WL1_HWIO_TX_MEM_PAGE_OUT(val)                              HWIO_TX_MEM_PAGE_OUT(val)
#define WL1_HWIO_TX_UMTS_HSDPCCH_CTL_OUT(val)                      HWIO_TX_UMTS_HSDPCCH_CTL_OUT(val)
#define WL1_HWIO_TX_UNIFIED_ENC_TRCH_MUX_ORDER_CCTRCH1_OUT(val)    HWIO_TX_UNIFIED_ENC_TRCH_MUX_ORDER_CCTRCH1_OUT(val)
#define WL1_HWIO_TX_UMTS_SCR_CODE_INIT_OUT(val)                    HWIO_TX_UMTS_SCR_CODE_INIT_OUT(val)
#define WL1_HWIO_TX_UNIFIED_PN_LD_OUT(val)                         HWIO_TX_UNIFIED_PN_LD_OUT(val)
#define WL1_HWIO_TX_UMTS_PHY_CH_TYPE_OUT(val)                      HWIO_TX_UMTS_PHY_CH_TYPE_OUT(val)
#define WL1_HWIO_TX_UMTS_EUL_TTI_MODE_OUT(val)                     HWIO_TX_UMTS_EUL_TTI_MODE_OUT(val)
#define WL1_HWIO_TX_UNIFIED_ENC_EUL_ENC_BANK_CFG_OUT(val)          HWIO_TX_UNIFIED_ENC_EUL_ENC_BANK_CFG_OUT(val)
#define WL1_HWIO_TX_UNIFIED_ENC_EUL_ENC_BANK_CFG_C1_OUT(val)       HWIO_TX_UNIFIED_ENC_EUL_ENC_BANK_CFG_C1_OUT(val)
#define WL1_HWIO_TX_UNIFIED_ENC_ERAM_DATA_INCRACC_0_OUT(val)       HWIO_TX_UNIFIED_ENC_ERAM_DATA_INCRACC_0_OUT(val)
#define WL1_HWIO_TX_UNIFIED_ENC_ERAM_DATA_INCRACC_1_OUT(val)       HWIO_TX_UNIFIED_ENC_ERAM_DATA_INCRACC_1_OUT(val)
#define WL1_HWIO_TX_UNIFIED_ENC_ERAM_DATA_INCRACC_2_OUT(val)       HWIO_TX_UNIFIED_ENC_ERAM_DATA_INCRACC_2_OUT(val)
#define WL1_HWIO_TX_UNIFIED_ENC_ERAM_DATA_INCRACC_3_OUT(val)       HWIO_TX_UNIFIED_ENC_ERAM_DATA_INCRACC_3_OUT(val)
#define WL1_HWIO_TX_UNIFIED_DCH_RACH_ENC_TRIGGER_OUT(val)          HWIO_TX_UNIFIED_DCH_RACH_ENC_TRIGGER_OUT(val)
#define WL1_HWIO_TX_BETA_GAIN_GROUP_DLY_OUT(val)                   HWIO_TX_BETA_GAIN_GROUP_DLY_OUT(val)
#define WL1_HWIO_TX_PHASE_ACC_RESET_OUT(val)                       HWIO_TX_PHASE_ACC_RESET_OUT(val)
#define WL1_HWIO_TX_CONDITIONING_RESET_OUT(val)                    HWIO_TX_CONDITIONING_RESET_OUT(val)
#define WL1_HWIO_TX_EVENT_SEL_0_OUT(val)                           HWIO_TX_EVENT_SEL_0_OUT(val)
#define WL1_HWIO_TX_EVENT_SEL_1_OUT(val)                           HWIO_TX_EVENT_SEL_1_OUT(val)
#define  WL1_HWIO_TX_MEM_TEST_WR_ADDR_OUT(val)                     HWIO_TX_MEM_TEST_WR_ADDR_OUT(val)
#define  WL1_HWIO_TX_TESTBUS_SEL_OUT(val)                          HWIO_TX_TESTBUS_SEL_OUT(val)
#define  WL1_HWIO_TX_EVENT_LOG_EN_OUT(val)                         HWIO_TX_EVENT_LOG_EN_OUT(val)
#define  WL1_HWIO_TX_MEM_TEST_WR_ADDR_OUT(val)                     HWIO_TX_MEM_TEST_WR_ADDR_OUT(val)
#define  WL1_HWIO_TX_MODE_OUT(val)                                 HWIO_TX_MODE_OUT(val);



/*Group 2: WL1_HWIO_OUTI(A,B,C) = WL1_HWIO_##A##_OUTI(B,C)*/


#define WL1_HWIO_TX_SW_AHB_EVENT_ADDRm_OUTI(index, val)                       HWIO_TX_SW_AHB_EVENT_ADDRm_OUTI(index, val)
#define WL1_HWIO_TX_UNIFIED_ENC_EUL_CODING_PARAM_BANKc_OUTI(index, val)       HWIO_TX_UNIFIED_ENC_EUL_CODING_PARAM_BANKc_OUTI(index, val)
#define WL1_HWIO_TX_UNIFIED_ENC_EUL_CODE_SEG_SIZE_BANKc_OUTI(index, val)      HWIO_TX_UNIFIED_ENC_EUL_CODE_SEG_SIZE_BANKc_OUTI(index, val)
#define WL1_HWIO_TX_UNIFIED_ENC_EUL_CODING_PARAM_BANKc_C1_OUTI(index, val)       HWIO_TX_UNIFIED_ENC_EUL_CODING_PARAM_BANKc_C1_OUTI(index, val)
#define WL1_HWIO_TX_UNIFIED_ENC_EUL_CODE_SEG_SIZE_BANKc_C1_OUTI(index, val)      HWIO_TX_UNIFIED_ENC_EUL_CODE_SEG_SIZE_BANKc_C1_OUTI(index, val)
#define WL1_HWIO_TX_EUL_CODING_PARAM_BANKc_C1_OUTI(index, val)                HWIO_TX_EUL_CODING_PARAM_BANKc_C1_OUTI(index, val)
#define WL1_HWIO_TX_EUL_CODE_SEG_SIZE_BANKc_C1_OUTI(index, val)               HWIO_TX_EUL_CODE_SEG_SIZE_BANKc_C1_OUTI(index, val)
#define WL1_HWIO_TX_EUL_TURBO_INTLV_PARAM0_BANKc_C1_OUTI(index, val)          HWIO_TX_EUL_TURBO_INTLV_PARAM0_BANKc_C1_OUTI(index, val)
#define WL1_HWIO_TX_EUL_TURBO_INTLV_PARAM1_BANKc_C1_OUTI(index, val)          HWIO_TX_EUL_TURBO_INTLV_PARAM1_BANKc_C1_OUTI(index, val)
#define WL1_HWIO_TX_EUL_CODING_PARAM_BANKc_OUTI(index, val)                   HWIO_TX_EUL_CODING_PARAM_BANKc_OUTI(index, val)
#define WL1_HWIO_TX_EUL_CODE_SEG_SIZE_BANKc_OUTI(index, val)                  HWIO_TX_EUL_CODE_SEG_SIZE_BANKc_OUTI(index, val)
#define WL1_HWIO_TX_EUL_TURBO_INTLV_PARAM0_BANKc_OUTI(index, val)             HWIO_TX_EUL_TURBO_INTLV_PARAM0_BANKc_OUTI(index, val)
#define WL1_HWIO_TX_EUL_TURBO_INTLV_PARAM1_BANKc_OUTI(index, val)             HWIO_TX_EUL_TURBO_INTLV_PARAM1_BANKc_OUTI(index, val)
#define WL1_HWIO_TX_UNIFIED_ENC_EUL_TURBO_INTLV_PARAM0_BANKc_OUTI(index, val) HWIO_TX_UNIFIED_ENC_EUL_TURBO_INTLV_PARAM0_BANKc_OUTI(index, val)
#define WL1_HWIO_TX_UNIFIED_ENC_EUL_TURBO_INTLV_PARAM1_BANKc_OUTI(index, val) HWIO_TX_UNIFIED_ENC_EUL_TURBO_INTLV_PARAM1_BANKc_OUTI(index, val)
#define WL1_HWIO_TX_UNIFIED_ENC_EUL_TURBO_INTLV_PARAM0_BANKc_C1_OUTI(index, val) HWIO_TX_UNIFIED_ENC_EUL_TURBO_INTLV_PARAM0_BANKc_C1_OUTI(index, val)
#define WL1_HWIO_TX_UNIFIED_ENC_EUL_TURBO_INTLV_PARAM1_BANKc_C1_OUTI(index, val) HWIO_TX_UNIFIED_ENC_EUL_TURBO_INTLV_PARAM1_BANKc_C1_OUTI(index, val)
#define WL1_HWIO_TX_UNIFIED_ENC_ERAM_INCRACC_INIT_OUTI(index, val)            HWIO_TX_UNIFIED_ENC_ERAM_INCRACC_INIT_OUTI(index, val)
#define WL1_HWIO_TX_UNIFIED_ENC_TRBLK_PARAM_TRCHc_OUTI(index, val)            HWIO_TX_UNIFIED_ENC_TRBLK_PARAM_TRCHc_OUTI(index, val)
#define WL1_HWIO_TX_UNIFIED_ENC_ERAMB_ADDR_TRCHc_OUTI(index, val)             HWIO_TX_UNIFIED_ENC_ERAMB_ADDR_TRCHc_OUTI(index, val)
#define WL1_HWIO_TX_UNIFIED_ENC_CODING_PARAM_TRCHc_OUTI(index, val)           HWIO_TX_UNIFIED_ENC_CODING_PARAM_TRCHc_OUTI(index, val)
#define WL1_HWIO_TX_UNIFIED_ENC_CODE_SEG_SIZE_TRCHc_OUTI(index, val)          HWIO_TX_UNIFIED_ENC_CODE_SEG_SIZE_TRCHc_OUTI(index, val)
#define WL1_HWIO_TX_UNIFIED_ENC_CODE_SEG_SIZE_TRCHc_OUTI(index, val)          HWIO_TX_UNIFIED_ENC_CODE_SEG_SIZE_TRCHc_OUTI(index, val)
#define WL1_HWIO_TX_UNIFIED_ENC_RM_EINI_TRCHc_OUTI(index, val)                HWIO_TX_UNIFIED_ENC_RM_EINI_TRCHc_OUTI(index, val)
#define WL1_HWIO_TX_UNIFIED_ENC_RM_EMINUS_TRCHc_OUTI(index, val)              HWIO_TX_UNIFIED_ENC_RM_EMINUS_TRCHc_OUTI(index, val)
#define WL1_HWIO_TX_UNIFIED_ENC_RM_EPLUS_TRCHc_OUTI(index, val)               HWIO_TX_UNIFIED_ENC_RM_EPLUS_TRCHc_OUTI(index, val)
#define WL1_HWIO_TX_UNIFIED_ENC_TURBO_INTLV_PARAM0_TRCHc_OUTI(index, val)     HWIO_TX_UNIFIED_ENC_TURBO_INTLV_PARAM0_TRCHc_OUTI(index, val)
#define WL1_HWIO_TX_UNIFIED_ENC_TURBO_INTLV_PARAM1_TRCHc_OUTI(index, val)     HWIO_TX_UNIFIED_ENC_TURBO_INTLV_PARAM1_TRCHc_OUTI(index, val)
#define WL1_HWIO_TX_UNIFIED_ENC_CIPHER_CK0_m_OUTI(index, val)                 HWIO_TX_UNIFIED_ENC_CIPHER_CK0_m_OUTI(index, val)
#define WL1_HWIO_TX_UNIFIED_ENC_CIPHER_CK1_m_OUTI(index, val)                 HWIO_TX_UNIFIED_ENC_CIPHER_CK1_m_OUTI(index, val)
#define WL1_HWIO_TX_UNIFIED_ENC_CIPHER_CK2_m_OUTI(index, val)                 HWIO_TX_UNIFIED_ENC_CIPHER_CK2_m_OUTI(index, val)
#define WL1_HWIO_TX_UNIFIED_ENC_CIPHER_CK3_m_OUTI(index, val)                 HWIO_TX_UNIFIED_ENC_CIPHER_CK3_m_OUTI(index, val)
#define WL1_HWIO_TX_MODE_c_OUTI(index, val)                                   HWIO_TX_MODE_c_OUTI(index, val)



/*Group 3: WL1_HWIO_IN(A) = WL1_HWIO_##A##_IN*/

#define WL1_HWIO_TX_STATUS_IN                               HWIO_TX_STATUS_IN
#define WL1_HWIO_TX_STATUS_RD_IN                            HWIO_TX_STATUS_RD_IN
#define WL1_HWIO_TX_MODE_IN                                 HWIO_TX_MODE_IN
#define WL1_HWIO_TX_UNIFIED_ENC_EUL_ENC_BANK_CFG_IN         HWIO_TX_UNIFIED_ENC_EUL_ENC_BANK_CFG_IN
#define WL1_HWIO_TX_UNIFIED_ENC_EUL_RM_SYS_EINI_IN          HWIO_TX_UNIFIED_ENC_EUL_RM_SYS_EINI_IN
#define WL1_HWIO_TX_UNIFIED_ENC_EUL_RM_SYS_EPLUS_EMINUS_IN  HWIO_TX_UNIFIED_ENC_EUL_RM_SYS_EPLUS_EMINUS_IN
#define WL1_HWIO_TX_UNIFIED_ENC_EUL_RM_P1_EINI_IN           HWIO_TX_UNIFIED_ENC_EUL_RM_P1_EINI_IN
#define WL1_HWIO_TX_UNIFIED_ENC_EUL_RM_P1_EPLUS_IN          HWIO_TX_UNIFIED_ENC_EUL_RM_P1_EPLUS_IN
#define WL1_HWIO_TX_UNIFIED_ENC_EUL_RM_P1_EMINUS_IN         HWIO_TX_UNIFIED_ENC_EUL_RM_P1_EMINUS_IN
#define WL1_HWIO_TX_UNIFIED_ENC_EUL_RM_P2_EINI_IN           HWIO_TX_UNIFIED_ENC_EUL_RM_P2_EINI_IN
#define WL1_HWIO_TX_UNIFIED_ENC_EUL_RM_P2_EPLUS_EMINUS_IN   HWIO_TX_UNIFIED_ENC_EUL_RM_P2_EPLUS_EMINUS_IN
#define WL1_HWIO_TX_UNIFIED_ENC_EUL_RM_SYS_NUMBITS_IN       HWIO_TX_UNIFIED_ENC_EUL_RM_SYS_NUMBITS_IN
#define WL1_HWIO_TX_UNIFIED_ENC_EUL_RM_P1P2_NUMBITS_IN      HWIO_TX_UNIFIED_ENC_EUL_RM_P1P2_NUMBITS_IN
#define WL1_HWIO_UMTS_TX_EUL_RM_RAM_BASE_ADDR_IN            HWIO_UMTS_TX_EUL_RM_RAM_BASE_ADDR_IN
#define WL1_HWIO_TX_UMTS_SCR_CODE_INIT_IN                   HWIO_TX_UMTS_SCR_CODE_INIT_IN
#define WL1_HWIO_TX_UMTS_PHY_CH_TYPE_IN                     HWIO_TX_UMTS_PHY_CH_TYPE_IN
#define WL1_HWIO_TX_UMTS_RACH_CTL_IN                        HWIO_TX_UMTS_RACH_CTL_IN
#define WL1_HWIO_TX_UMTS_RACH_OVSF_IN                       HWIO_TX_UMTS_RACH_OVSF_IN
#define WL1_HWIO_TX_UMTS_CTL_CH_DATA_IN                     HWIO_TX_UMTS_CTL_CH_DATA_IN
#define WL1_HWIO_TX_UMTS_DPDCH_CTL_IN                       HWIO_TX_UMTS_DPDCH_CTL_IN
#define WL1_HWIO_TX_UMTS_HSDPCCH_CTL_IN                     HWIO_TX_UMTS_HSDPCCH_CTL_IN
#define WL1_HWIO_TX_UMTS_HSDPCCH_DATA_IN                    HWIO_TX_UMTS_HSDPCCH_DATA_IN
#define WL1_HWIO_TX_UMTS_EUL_EDPDCH_CONFIG_IN               HWIO_TX_UMTS_EUL_EDPDCH_CONFIG_IN
#define WL1_HWIO_TX_UMTS_EUL_EDPDCH_CTL0_IN                 HWIO_TX_UMTS_EUL_EDPDCH_CTL0_IN
#define WL1_HWIO_TX_UMTS_EUL_EDPDCH_CTL1_IN                 HWIO_TX_UMTS_EUL_EDPDCH_CTL1_IN
#define WL1_HWIO_TX_UMTS_EUL_EDPDCH_CTL2_IN                 HWIO_TX_UMTS_EUL_EDPDCH_CTL2_IN
#define WL1_HWIO_TX_UMTS_EUL_EDPDCH_CTL3_IN                 HWIO_TX_UMTS_EUL_EDPDCH_CTL3_IN
#define WL1_HWIO_TX_UMTS_EUL_EDPCCH_CTL_IN                  HWIO_TX_UMTS_EUL_EDPCCH_CTL_IN
#define WL1_HWIO_TX_UMTS_EUL_EDPCCH_DATA_IN                 HWIO_TX_UMTS_EUL_EDPCCH_DATA_IN
#define WL1_HWIO_TX_UMTS_EUL_TTI_MODE_IN                    HWIO_TX_UMTS_EUL_TTI_MODE_IN
#define WL1_HWIO_TX_UMTS_HSDPCCH_OFFSET_IN                  HWIO_TX_UMTS_HSDPCCH_OFFSET_IN
#define WL1_HWIO_TX_UNIFIED_BETAP_GAIN_UPDATE_IN            HWIO_TX_UNIFIED_BETAP_GAIN_UPDATE_IN
#define WL1_HWIO_TX_UNIFIED_PA_RANGE_UPDATE_IN              HWIO_TX_UNIFIED_PA_RANGE_UPDATE_IN
#define WL1_HWIO_TX_UNIFIED_OFFL_EN_IN                      HWIO_TX_UNIFIED_OFFL_EN_IN
#define WL1_HWIO_TX_UNIFIED_DTX_EN_IN                       HWIO_TX_UNIFIED_DTX_EN_IN
#define WL1_HWIO_TX_UNIFIED_ERAM_CTL_IN                     HWIO_TX_UNIFIED_ERAM_CTL_IN
#define WL1_HWIO_TX_UNIFIED_ENC_STATUS_IN                   HWIO_TX_UNIFIED_ENC_STATUS_IN
#define WL1_HWIO_TX_UNIFIED_GAIN_0_IN                       HWIO_TX_UNIFIED_GAIN_0_IN
#define WL1_HWIO_TX_UNIFIED_GAIN_1_IN                       HWIO_TX_UNIFIED_GAIN_1_IN
#define WL1_HWIO_TX_UNIFIED_GAIN_2_IN                       HWIO_TX_UNIFIED_GAIN_2_IN
#define WL1_HWIO_TX_UNIFIED_GAIN_3_IN                       HWIO_TX_UNIFIED_GAIN_3_IN
#define WL1_HWIO_TX_UNIFIED_GAIN_4_IN                       HWIO_TX_UNIFIED_GAIN_4_IN
#define WL1_HWIO_TX_UNIFIED_GAIN_5_IN                       HWIO_TX_UNIFIED_GAIN_5_IN
#define WL1_HWIO_TX_UMTS_DCH_RACH_LAST_IN                   HWIO_TX_UMTS_DCH_RACH_LAST_IN
#define WL1_HWIO_TX_UNIFIED_PA_RANGE_IN                     HWIO_TX_UNIFIED_PA_RANGE_IN
#define WL1_HWIO_TX_UNIFIED_ENC_ENDIAN_FRMT_CTL_IN          HWIO_TX_UNIFIED_ENC_ENDIAN_FRMT_CTL_IN
#define WL1_HWIO_TX_UNIFIED_ENC_FILLER_POLARITY_IN          HWIO_TX_UNIFIED_ENC_FILLER_POLARITY_IN



/*Group 3: WL1_HWIO_INI(A,B) = WL1_HWIO_##A##_INI(B)*/

#define WL1_HWIO_TX_MODE_c_INI(val)                           HWIO_TX_MODE_c_INI(val)
#define WL1_HWIO_TX_UNIFIED_ENC_CIPHER_CK0_m_INI(val)         HWIO_TX_UNIFIED_ENC_CIPHER_CK0_m_INI(val)


#define WL1_HWIO_TX_UNIFIED_ENC_CIPHER_CK1_m_INI(val)         HWIO_TX_UNIFIED_ENC_CIPHER_CK1_m_INI(val)
#define WL1_HWIO_TX_UNIFIED_ENC_CIPHER_CK2_m_INI(val)         HWIO_TX_UNIFIED_ENC_CIPHER_CK2_m_INI(val)
#define WL1_HWIO_TX_UNIFIED_ENC_CIPHER_CK3_m_INI(val)         HWIO_TX_UNIFIED_ENC_CIPHER_CK3_m_INI(val)
#define WL1_HWIO_TX_UNIFIED_ENC_CIPHER_CK4_m_INI(val)         HWIO_TX_UNIFIED_ENC_CIPHER_CK4_m_INI(val)
#define WL1_HWIO_TX_UNIFIED_ENC_CIPHER_CK5_m_INI(val)         HWIO_TX_UNIFIED_ENC_CIPHER_CK5_m_INI(val)

#define WL1_HWIO_TX_UNIFIED_ENC_EUL_CODING_PARAM_BANKc_INI(val)               HWIO_TX_UNIFIED_ENC_EUL_CODING_PARAM_BANKc_INI(val)
#define WL1_HWIO_TX_UNIFIED_ENC_EUL_CODE_SEG_SIZE_BANKc_INI(val)              HWIO_TX_UNIFIED_ENC_EUL_CODE_SEG_SIZE_BANKc_INI(val)
#define WL1_HWIO_TX_UNIFIED_ENC_EUL_TURBO_INTLV_PARAM0_BANKc_INI(val)         HWIO_TX_UNIFIED_ENC_EUL_TURBO_INTLV_PARAM0_BANKc_INI(val)
#define WL1_HWIO_TX_UNIFIED_ENC_EUL_TURBO_INTLV_PARAM1_BANKc_INI(val)         HWIO_TX_UNIFIED_ENC_EUL_TURBO_INTLV_PARAM1_BANKc_INI(val)


#define WL1_HWIO_TX_UMTS_EUL_NUMBITS_EDPDCHc_INI(val)         HWIO_TX_UMTS_EUL_NUMBITS_EDPDCHc_INI(val)


/*Group 4: WL1_HWIO_INM(A, M) = WL1_HWIO_##A##_IN(M)*/

#define WL1_HWIO_TX_STATUS_INM(mask)                          HWIO_TX_STATUS_INM(mask)



/*Group 5: WL1_HWIO_ADDR(A) = WL1_HWIO_##A##_ADDR*/

#define WL1_HWIO_TX_MEM_START_ADDR                            HWIO_TX_MEM_START_ADDR
#if defined(FEATURE_WCDMA_RUMI_SUPPORT) && defined(FEATURE_WCDMA_ATLAS_MODEM)
#define WL1_HWIO_MSS_RESERVE_01_ADDR                          HWIO_MSS_RESERVE_01_ADDR
#endif /* defined(FEATURE_WCDMA_RUMI_SUPPORT) && defined(FEATURE_WCDMA_ATLAS_MODEM) */


/*Group 6: WL1_HWIO_ADDRI(A, B)= WL1_HWIO_##A##_ADDR(B) */

#define WL1_HWIO_TX_CIPHER_CK0_m_ADDR(index)                  HWIO_TX_CIPHER_CK0_m_ADDR(index)
#define WL1_HWIO_TX_TRBLK_PARAM_TRCHc_ADDR(index)             HWIO_TX_TRBLK_PARAM_TRCHc_ADDR(index)
#define WL1_HWIO_TX_ERAMB_ADDR_TRCHc_ADDR(index)              HWIO_TX_ERAMB_ADDR_TRCHc_ADDR(index)
#define WL1_HWIO_TX_CODING_PARAM_TRCHc_ADDR(index)            HWIO_TX_CODING_PARAM_TRCHc_ADDR(index)
#define WL1_HWIO_TX_CODE_SEG_SIZE_TRCHc_ADDR(index)           HWIO_TX_CODE_SEG_SIZE_TRCHc_ADDR(index)
#define WL1_HWIO_TX_RM_EINI_TRCHc_ADDR(index)                 HWIO_TX_RM_EINI_TRCHc_ADDR(index)
#define WL1_HWIO_TX_RM_EMINUS_TRCHc_ADDR(index)               HWIO_TX_RM_EMINUS_TRCHc_ADDR(index)
#define WL1_HWIO_TX_RM_EPLUS_TRCHc_ADDR(index)                HWIO_TX_RM_EPLUS_TRCHc_ADDR(index)
#define WL1_HWIO_TX_TURBO_INTLV_PARAM0_TRCHc_ADDR(index)      HWIO_TX_TURBO_INTLV_PARAM0_TRCHc_ADDR(index)
#define WL1_HWIO_TX_TURBO_INTLV_PARAM1_TRCHc_ADDR(index)      HWIO_TX_TURBO_INTLV_PARAM1_TRCHc_ADDR(index)
#define WL1_HWIO_MODEM_CLK_HALT_MDSP_CLK_HALT_FMSK            HWIO_MODEM_CLK_HALT_MDSP_CLK_HALT_BMSK



/*Group 7: WL1_HWIO_SHFT(A)= WL1_HWIO_##A## */

#define WL1_HWIO_TX_UNIFIED_ENC_NUM_ACTIVE_TRCHS_NUM_ACTIVE_TRCHS_CCTRCH1_SHFT     HWIO_TX_UNIFIED_ENC_NUM_ACTIVE_TRCHS_NUM_ACTIVE_TRCHS_CCTRCH1_SHFT
#define WL1_HWIO_TX_UNIFIED_ENC_NUM_ACTIVE_TRCHS_NUM_ERAMA_TRCHS_SHFT              HWIO_TX_UNIFIED_ENC_NUM_ACTIVE_TRCHS_NUM_ERAMA_TRCHS_SHFT

#define WL1_HWIO_TX_UMTS_DPDCH_CTL_EN_SHFT                                         HWIO_TX_UMTS_DPDCH_CTL_EN_SHFT
#define WL1_HWIO_TX_UMTS_DPDCH_CTL_SPR_FACTOR_SHFT                                 HWIO_TX_UMTS_DPDCH_CTL_SPR_FACTOR_SHFT
#define WL1_HWIO_TX_UMTS_DPDCH_CTL_OVSF_SHFT                                       HWIO_TX_UMTS_DPDCH_CTL_OVSF_SHFT


#define WL1_HWIO_TX_UMTS_DCH_RACH_LAST_LAST_ROW_SHFT                                    HWIO_TX_UMTS_DCH_RACH_LAST_LAST_ROW_SHFT

#define WL1_HWIO_TX_UNIFIED_ENC_TRCH_MUX_ORDER_CCTRCH1_TRCH_CFG1_INDEX_CCTRCH1_SHFT     HWIO_TX_UNIFIED_ENC_TRCH_MUX_ORDER_CCTRCH1_TRCH_CFG1_INDEX_CCTRCH1_SHFT
#define WL1_HWIO_TX_UNIFIED_ENC_TRCH_MUX_ORDER_CCTRCH1_TRCH_START_ADDR_CCTRCH1_SHFT     HWIO_TX_UNIFIED_ENC_TRCH_MUX_ORDER_CCTRCH1_TRCH_START_ADDR_CCTRCH1_SHFT

#define WL1_HWIO_TX_UMTS_SCR_CODE_INIT_SCR_CODE_INIT_SHFT                               HWIO_TX_UMTS_SCR_CODE_INIT_SCR_CODE_INIT_SHFT


#define WL1_HWIO_TX_UNIFIED_ENC_TRBLK_PARAM_TRCHc_TRBLK_SIZE_SHFT                       HWIO_TX_UNIFIED_ENC_TRBLK_PARAM_TRCHc_TRBLK_SIZE_SHFT
#define WL1_HWIO_TX_UNIFIED_ENC_TRBLK_PARAM_TRCHc_CRC_SIZE_SHFT                         HWIO_TX_UNIFIED_ENC_TRBLK_PARAM_TRCHc_CRC_SIZE_SHFT
#define WL1_HWIO_TX_UNIFIED_ENC_TRBLK_PARAM_TRCHc_NUM_TRBLKS_SHFT                       HWIO_TX_UNIFIED_ENC_TRBLK_PARAM_TRCHc_NUM_TRBLKS_SHFT


#define WL1_HWIO_TX_UNIFIED_ENC_CODING_PARAM_TRCHc_NUM_PRE_RM_BITS_SHFT                 HWIO_TX_UNIFIED_ENC_CODING_PARAM_TRCHc_NUM_PRE_RM_BITS_SHFT
#define WL1_HWIO_TX_UNIFIED_ENC_CODING_PARAM_TRCHc_TRCH_TTI_SHFT                        HWIO_TX_UNIFIED_ENC_CODING_PARAM_TRCHc_TRCH_TTI_SHFT
#define WL1_HWIO_TX_UNIFIED_ENC_CODING_PARAM_TRCHc_NUM_CODE_SEGS_SHFT                   HWIO_TX_UNIFIED_ENC_CODING_PARAM_TRCHc_NUM_CODE_SEGS_SHFT
#define WL1_HWIO_TX_UNIFIED_ENC_CODING_PARAM_TRCHc_CODING_RATE_TYPE_SHFT                HWIO_TX_UNIFIED_ENC_CODING_PARAM_TRCHc_CODING_RATE_TYPE_SHFT



#define WL1_HWIO_TX_UNIFIED_ENC_CODE_SEG_SIZE_TRCHc_PUNCTURE_FLAG_SHFT                  HWIO_TX_UNIFIED_ENC_CODE_SEG_SIZE_TRCHc_PUNCTURE_FLAG_SHFT
#define WL1_HWIO_TX_UNIFIED_ENC_CODE_SEG_SIZE_TRCHc_NUM_FILLER_BITS_SHFT                HWIO_TX_UNIFIED_ENC_CODE_SEG_SIZE_TRCHc_NUM_FILLER_BITS_SHFT
#define WL1_HWIO_TX_UNIFIED_ENC_CODE_SEG_SIZE_TRCHc_NUM_BITS_CODE_SEG_SHFT              HWIO_TX_UNIFIED_ENC_CODE_SEG_SIZE_TRCHc_NUM_BITS_CODE_SEG_SHFT


#define WL1_HWIO_TX_UNIFIED_ENC_RM_EINI_TRCHc_INITIAL_ERROR2_SHFT                       HWIO_TX_UNIFIED_ENC_RM_EINI_TRCHc_INITIAL_ERROR2_SHFT
#define WL1_HWIO_TX_UNIFIED_ENC_RM_EINI_TRCHc_INITIAL_ERROR1_SHFT                       HWIO_TX_UNIFIED_ENC_RM_EINI_TRCHc_INITIAL_ERROR1_SHFT

#define WL1_HWIO_TX_UNIFIED_ENC_RM_EMINUS_TRCHc_EMINUS2_SHFT                            HWIO_TX_UNIFIED_ENC_RM_EMINUS_TRCHc_EMINUS2_SHFT
#define WL1_HWIO_TX_UNIFIED_ENC_RM_EMINUS_TRCHc_EMINUS1_SHFT                            HWIO_TX_UNIFIED_ENC_RM_EMINUS_TRCHc_EMINUS1_SHFT

#define WL1_HWIO_TX_UNIFIED_ENC_RM_EPLUS_TRCHc_EPLUS2_SHFT                              HWIO_TX_UNIFIED_ENC_RM_EPLUS_TRCHc_EPLUS2_SHFT
#define WL1_HWIO_TX_UNIFIED_ENC_RM_EPLUS_TRCHc_EPLUS1_SHFT                              HWIO_TX_UNIFIED_ENC_RM_EPLUS_TRCHc_EPLUS1_SHFT



#define WL1_HWIO_TX_UNIFIED_ENC_TURBO_INTLV_PARAM0_TRCHc_NUM_COLUMNS_MINUS1_SHFT        HWIO_TX_UNIFIED_ENC_TURBO_INTLV_PARAM0_TRCHc_NUM_COLUMNS_MINUS1_SHFT
#define WL1_HWIO_TX_UNIFIED_ENC_TURBO_INTLV_PARAM0_TRCHc_LAST_COLUMN_SHFT               HWIO_TX_UNIFIED_ENC_TURBO_INTLV_PARAM0_TRCHc_LAST_COLUMN_SHFT
#define WL1_HWIO_TX_UNIFIED_ENC_TURBO_INTLV_PARAM0_TRCHc_NUM_ROW_INDEX_SHFT             HWIO_TX_UNIFIED_ENC_TURBO_INTLV_PARAM0_TRCHc_NUM_ROW_INDEX_SHFT
#define WL1_HWIO_TX_UNIFIED_ENC_TURBO_INTLV_PARAM0_TRCHc_LAST_ROW_BIT_EXCH_SHFT         HWIO_TX_UNIFIED_ENC_TURBO_INTLV_PARAM0_TRCHc_LAST_ROW_BIT_EXCH_SHFT
#define WL1_HWIO_TX_UNIFIED_ENC_TURBO_INTLV_PARAM0_TRCHc_LAST_ROW_SHFT                  HWIO_TX_UNIFIED_ENC_TURBO_INTLV_PARAM0_TRCHc_LAST_ROW_SHFT
#define WL1_HWIO_TX_UNIFIED_ENC_TURBO_INTLV_PARAM1_TRCHc_PRIME_NUM_INDEX_SHFT           HWIO_TX_UNIFIED_ENC_TURBO_INTLV_PARAM1_TRCHc_PRIME_NUM_INDEX_SHFT
#define WL1_HWIO_TX_UNIFIED_ENC_TURBO_INTLV_PARAM1_TRCHc_PRIME_NUMBER_SHFT              HWIO_TX_UNIFIED_ENC_TURBO_INTLV_PARAM1_TRCHc_PRIME_NUMBER_SHFT



/*Group 8: WL1_HWIO_CONST(A)= WL1_HWIO_##A##_SHFT */


#define WL1_HWIO_TX_UMTS_DCH_RACH_LAST_LAST_ROW_BMSK                                    HWIO_TX_UMTS_DCH_RACH_LAST_LAST_ROW_BMSK
#define WL1_HWIO_TX_UMTS_DCH_RACH_LAST_LAST_COL_BMSK                                    HWIO_TX_UMTS_DCH_RACH_LAST_LAST_COL_BMSK

#define WL1_HWIO_TX_UNIFIED_ENC_TRCH_MUX_ORDER_CCTRCH1_TRCH_START_ADDR_CCTRCH1_BMSK     HWIO_TX_UNIFIED_ENC_TRCH_MUX_ORDER_CCTRCH1_TRCH_START_ADDR_CCTRCH1_BMSK







/* HARQ level ERAM Read back data structure - 
 * harq_eram_mem - Memory is allocated from Dynamic memory pool
 * buff_avail - indicates whether the data is already flushed to loggin or not
 * subfn_cfn - Notes the value of CFN/SubFN info for log packet purpose
 * num_bits - valid number of bits in this harq_eram_mem based on etfci
 * etfci - selected etfci
 * new_tx - Indicates new or retransmission in this TTI
 */

#define HWIO_WCDMA_EUL_ERAM_BANK0_START_OFFSET 0x1000
#define HWIO_WCDMA_EUL_ERAM_BANK1_START_OFFSET 0x2000
#ifdef FEATURE_WCDMA_DC_HSUPA
#define HWIO_WCDMA_EUL_ERAM_BANK0_START_OFFSET_C1 0x1800
#define HWIO_WCDMA_EUL_ERAM_BANK1_START_OFFSET_C1 0x2800
#endif /* FEATURE_WCDMA_DC_HSUPA */




#define EULENC_ERAM_COPY_ERAM_HARQ_MEM_BYTES   (1500)  /* DSM Item allocation max size 1500 bytes */
#define EULENC_ERAM_COPY_ERAM_HARQ_MEM_BITS    (12000) /* 1500*8 =12000 bits */

/*
#define L1_CIPH_BUFFER_IDX_INIT_VAL  0xFFFFFFFF
#define L1_COPY_ENG_BUFFER_IDX_INIT_VAL  0xFFFFFFFF
*/

/* Index at which Ciphering keys should be written to and read from in A2 UL SEC memory */
#define EULENC_A2_UL_CIPH_INDEX  4

#define A2_FILL_TASK_MAX_DATA_SIZE_BITS 128

// In order to get the phy address of each ERAM bank, we add the size of all the banks upto this one, to the base address
// There are only 4 banks in 10ms TTI, but 8 banks in 2ms TTI
#define EULENC_DEST_ERAM_BANK_PHY_ADDR( tti, curr_eram_bank )  \
                ( 0xB3A00000 + ((curr_eram_bank << EULENC_ERAM_BANK_TTI_SHFT_FACTOR( tti ) ) << EULENC_ERAM_BANK_ADDR_OFST ))

// Macro for destination address for BURST interface for COPY engine control words.
#define EULENC_DEST_COPY_ENGINE_PHY_ADDR() (ENC_BURST_BASE_PHYS + 0xA000)

#ifdef FEATURE_WCDMA_TABASCO_MODEM
#define EULENC_DEST_ERAM_BANK_REL_OFST_RD( curr_eram_bank_id )  \
                ( curr_eram_bank_id? (HWIO_WCDMA_EUL_ERAM_BANK1_START_OFFSET) : (HWIO_WCDMA_EUL_ERAM_BANK0_START_OFFSET) )

#ifdef FEATURE_WCDMA_DC_HSUPA
#define EULENC_DEST_ERAM_BANK_REL_OFST_RD_C1( curr_eram_bank_id )  \
                ( curr_eram_bank_id? (HWIO_WCDMA_EUL_ERAM_BANK1_START_OFFSET_C1) : (HWIO_WCDMA_EUL_ERAM_BANK0_START_OFFSET_C1) )
#endif /*FEATURE_WCDMA_DC_HSUPA*/

#else
#define EULENC_DEST_ERAM_BANK_REL_OFST_RD( curr_eram_bank_id )  \
                ( curr_eram_bank_id? (0x1000) : (0x0) )
#endif

#define WRITE_EUL_COPY_ENG_CTRL_WORD( addr, ctrl_wrd )  \
                ( OUTP32( ENC_BURST_BASE + addr, ctrl_wrd ) )
/* MSM7200 HW interface TX_EUL_CODING_PARAM_BANKc
 * num_code_blocks at bits 17~20 and pre RM bits or Ne,j at bits 0~16
 */
#define EULENC_PRE_RM_BITS_BMSK     0x01FFFF
#define EULENC_NUM_CODE_BLKS_BMSK   0x1E0000
#define EULENC_NUM_CODE_BLKS_SHFT   17

/* MSM7200 HW interface TX_EUL_CODE_SEG_SIZE_BANKc
 * num_filler_bits at bits 13~18 and bits_per_block at bits 0~12
 */
#define EULENC_BITS_PER_BLK_BMSK    0x001FFF
#define EULENC_NUM_FILL_BITS_BMSK   0x07E000
#define EULENC_NUM_FILL_BITS_SHFT   13


/* MSM7200 HW interface TX_EUL_TURBO_INTLV_PARAM0_BANKc
 * Bits     Name Description
 * 23:16    NUM_COLUMNS_MINUS1
 * 15:8     LAST_COLUMN
 * 7:6      NUM_ROW_INDEX
 * 5        LAST_ROW_BIT_EXCH
 * 4:0      LAST_ROW
 */
#define EULENC_TURBO_INTLV_LAST_ROW_BMSK           0x1F
#define EULENC_TURBO_INTLV_LAST_ROW_BIT_EXCH_SHFT  5
#define EULENC_TURBO_INTLV_NUM_ROW_INDEX_SHFT      6
#define EULENC_TURBO_INTLV_LAST_COLUMN_SHFT        8
#define EULENC_TURBO_INTLV_NUM_COLUMNS_MINUS1_SHFT 16

/* MSM7200 HW interface TX_EUL_TURBO_INTLV_PARAM1_BANKc
 * 14:9     PRIME_NUM_INDEX
 * 8:0      PRIME_NUMBER
 */
#define EULENC_TURBO_INTLV_PRIME_NUMBER_BMSK     0x1FF
#define EULENC_TURBO_INTLV_PRIME_NUM_INDEX_SHFT  9



#if defined(FEATURE_THOR_MODEM) || defined(FEATURE_WCDMA_ATLAS_MODEM)
  #ifdef FEATURE_WCDMA_ATLAS_MODEM
    #define MCALWCDMA_WENC_ENC_LMEM_START_ADDR  HWIO_SVUSS2_VUSS_DMEM_ENC_START_ADDR
  #else
    #define MCALWCDMA_WENC_ENC_LMEM_START_ADDR  HWIO_ENC_VUSS_DMEM_ENC_START_ADDR
  #endif

  #ifdef HWIO_MEMSS_CLST0_BASE_MIN_ADDR
    #define MCALWCDMA_WENC_VPE0_LMEM_START_ADDR HWIO_MEMSS_CLST0_BASE_MIN_ADDR
  #else
    #ifdef HWIO_MNOC_AXI_BR_CLST0_BASE_MIN_ADDR
      #define MCALWCDMA_WENC_VPE0_LMEM_START_ADDR HWIO_MNOC_AXI_BR_CLST0_BASE_MIN_ADDR
    #else
      #define MCALWCDMA_WENC_VPE0_LMEM_START_ADDR MNOC_AXI_BR_MEM_REG_BASE
    #endif
  #endif
#else
  #define MCALWCDMA_WENC_ENC_LMEM_START_ADDR HWIO_ENC_LMEM_PAGE0_START_ADDR
  #define MCALWCDMA_WENC_VPE0_LMEM_START_ADDR HWIO_MODEM_LMEM_RAM_START_ADDR  
#endif


#endif

