#ifndef PS_SOCK_PROTOCOLSTACK_GLOBALEVENTDEFS_H
#define PS_SOCK_PROTOCOLSTACK_GLOBALEVENTDEFS_H
//TODO Change this
/*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*

                      S O C K P L A T F O R M L I B . H

GENERAL DESCRIPTION
  This header file defines the sockets platform library for all targets (WM,
  Linux, AMSS etc.). Any target which wants to support ds Sockets API shall
  implement this library

INITIALIZATION AND SEQUENCING REQUIREMENTS
  None

Copyright (c) 2008 by Qualcomm Technologies, Incorporated.  All Rights Reserved.
*====*====*====*====*====*====*====*====*====*====*====*====*====*====*====*/
/*===========================================================================

                        EDIT HISTORY FOR MODULE

  $Header: //components/rel/data.mpss/3.5..2.1/interface/pssock/src/PS_Sock_ProtocolStack_GlobalEventDefs.h#2 $
  $DateTime: 2019/10/22 02:53:17 $ $Author: pwbldsvc $

===========================================================================*/
/*===========================================================================

                     INCLUDE FILES FOR MODULE

===========================================================================*/
#include "comdef.h"
#include "customer.h"
#include "target.h"

/*===========================================================================

                      PUBLIC DATA DECLARATIONS

===========================================================================*/
namespace PS
{
  namespace Sock
  {
    namespace ProtocolStack
    {
      typedef int32  GlobalEventType;

      /** List of global events that are generated by the PS Stack.

        This namespace defines the events that are generated by the PS Stack.

        @see PS::Sock::ProtocolStack::iGlobalEventListener
      */
      namespace GlobalEvent
      {
        const GlobalEventType  PS_MEM_BUF_AVAILABLE     = 0;
        /**< Posted when PS Stack has enough free PS_MEM buffers */
        const GlobalEventType  PS_MEM_BUF_NOT_AVAILABLE = 1;
        /**< Posted when PS Stack runs out of PS_MEM buffers */
        const GlobalEventType  DSM_ITEM_AVAILABLE       = 2;
        /**< Posted when PS Stack has enough DSM items */
        const GlobalEventType  DSM_ITEM_NOT_AVAILABLE   = 3;
        /**< Posted when PS Stack runs out of DSM items */
      }

    } /* namespace ProtocolStack */
  } /* namespace Sock */
} /* namespace PS */

#endif /* PS_SOCK_PROTOCOLSTACK_GLOBALEVENTDEFS_H */
