/*===========================================================================

FILE:        ul_data.c

DESCRIPTION: This file implements the target-specific NPA Bus subnodes

   Copyright (c) 2019 QUALCOMM Technologies, Incorporated.
             All Rights Reserved
             QUALCOMM Proprietary/GTDR
-------------------------------------------------------------------------------

$Header: //components/rel/core.mpss/10.0/settings/systemdrivers/icb/config/agatti/ul_data.c#1 $ 
$DateTime: 2020/07/26 11:21:23 $
$Author: pwbldsvc $
$Change: 25101703 $

                      EDIT HISTORY FOR FILE

 Autogenerated for target: Modem
 This file was generated using Autogen script: 
 gen.py

 when         who     what, where, why
 ----------   ---     -----------------------------------------------------------
 2019/01/30 Autogen  Autogenerated version

=============================================================================*/
#include "npa.h"
#include "npa_resource.h"
#include "npa_log.h"
#include "ul_i.h"
#include "ul_tree.h"
#include "icb_soc_data.h"

/*============================================================================
                          DEFINES
============================================================================*/
/*============================================================================
                   INTERNAL DATA DECLARATIONS
============================================================================*/
/*============================================================================
                        AXI CONFIG DECLARATIONS
============================================================================*/

/****************************************************************************/
/*                              BUSES                                       */
/****************************************************************************/
/**** Bus: bimc ****/
static HAL_bimc_InfoType bimc_hal_info =
{
  0, /* Base address */
  19200, /* QoS frequency */
};

static const char *bus_bimc_clk_names[1] =
{
  "/clk/bimc",
};

static npa_client_handle bus_bimc_clk_clients[1] = {0};

static icb_bus_def_type bimc_bus =
{
  "+BIMC", /* HWIO base name */
  false, /* remote node? */ 
  0, /* base address */
  0x80000, /* HWIO region size */
  ICB_BUS_BIMC, /* Bus type */
  0, /* Address width */
  8, /* Data width */
  (void *)&bimc_hal_info, /* Bus info structure */
  1,    /* Config clock info */
  bus_bimc_clk_names,
  bus_bimc_clk_clients,
  0,    /* No enable/disable config clocks. */
  NULL,
  NULL,
  {
    ICB_AGG_SCHEME_0,
    153,
    100,
  },
};

/**** Bus: clk_virt ****/

static const char *bus_clk_virt_clk_names[1] =
{
  "/clk/qup",
};

static npa_client_handle bus_clk_virt_clk_clients[1] = {0};

static icb_bus_def_type clk_virt_bus =
{
  "", /* HWIO base name */
  true, /* remote node? */ 
  0, /* base address */
  0x0, /* HWIO region size */
  ICB_BUS_VIRT, /* Bus type */
  0, /* Address width */
  4, /* Data width */
  NULL, /* Bus info structure */
  1,    /* Config clock info */
  bus_clk_virt_clk_names,
  bus_clk_virt_clk_clients,
  0,    /* No enable/disable config clocks. */
  NULL,
  NULL,
  {
    ICB_AGG_SCHEME_LEGACY,
    0,
    0,
  },
};

/**** Bus: config_noc ****/
static HAL_noc_InfoType config_noc_hal_info =
{
  0,        /* Base address */
  1,     /* Number of masters */
  0, /* Number of masters with QoS */ 
  14,      /* Number of slaves */ 
  19200,         /* QoS frequency */ 
  NULL, /* QoS master info */
  false, /* Save/Restore unused here. */
  NULL,
  0,
  NULL,
  NOC_QOS_OFFSET_LEGACY, /* NOC layout type */
  0, /* QoS offset */
  0, /* QoS block size */
  NOC_VERSION_QNOC4,  /*NOC version */
};

static const char *bus_config_noc_clk_names[1] =
{
  "/clk/cnoc",
};

static npa_client_handle bus_config_noc_clk_clients[1] = {0};

static icb_bus_def_type config_noc_bus =
{
  "CONFIG_NOC", /* HWIO base name */
  true, /* remote node? */ 
  0, /* base address */
  0x9200, /* HWIO region size */
  ICB_BUS_NOC, /* Bus type */
  0, /* Address width */
  4, /* Data width */
  (void *)&config_noc_hal_info, /* Bus info structure */
  1,    /* Config clock info */
  bus_config_noc_clk_names,
  bus_config_noc_clk_clients,
  0,    /* No enable/disable config clocks. */
  NULL,
  NULL,
  {
    ICB_AGG_SCHEME_0,
    0,
    100,
  },
};

/**** Bus: sys_noc ****/
static HAL_noc_QosMasterInfoType sys_noc_master_info[22] =
{
  {0}, /* unused port 0 */
  {0}, /* unused port 1 */
  {0}, /* unused port 2 */
  {0}, /* unused port 3 */
  {0}, /* unused port 4 */
  {0}, /* unused port 5 */
  {NOC_QOS_ALLOWED_MODE_BYPASS | NOC_QOS_ALLOWED_MODE_FIXED | NOC_QOS_ALLOWED_MODE_LIMITER | NOC_QOS_ALLOWED_MODE_REGULATOR}, /* qxm_mss */
  {NOC_QOS_ALLOWED_MODE_BYPASS | NOC_QOS_ALLOWED_MODE_FIXED | NOC_QOS_ALLOWED_MODE_LIMITER | NOC_QOS_ALLOWED_MODE_REGULATOR}, /* qxm_mss_nav */
  {0}, /* unused port 8 */
  {0}, /* unused port 9 */
  {0}, /* unused port 10 */
  {0}, /* unused port 11 */
  {0}, /* unused port 12 */
  {0}, /* unused port 13 */
  {0}, /* unused port 14 */
  {0}, /* unused port 15 */
  {0}, /* unused port 16 */
  {0}, /* unused port 17 */
  {0}, /* unused port 18 */
  {0}, /* unused port 19 */
  {0}, /* unused port 20 */
  {NOC_QOS_ALLOWED_MODE_BYPASS | NOC_QOS_ALLOWED_MODE_FIXED | NOC_QOS_ALLOWED_MODE_LIMITER | NOC_QOS_ALLOWED_MODE_REGULATOR}, /* qxm_mss_ce */
};

static HAL_noc_InfoType sys_noc_hal_info =
{
  0,        /* Base address */
  5,     /* Number of masters */
  22, /* Number of masters with QoS */ 
  5,      /* Number of slaves */ 
  19200,         /* QoS frequency */ 
  sys_noc_master_info, /* QoS master info */
  false, /* Save/Restore unused here. */
  NULL,
  0,
  NULL,
  NOC_QOS_OFFSET_LEGACY, /* NOC layout type */
  0x15000, /* QoS offset */
  0x1000, /* QoS block size */
  NOC_VERSION_QNOC4,  /*NOC version */
};

static const char *bus_sys_noc_clk_names[1] =
{
  "/clk/snoc",
};

static npa_client_handle bus_sys_noc_clk_clients[1] = {0};

static icb_bus_def_type sys_noc_bus =
{
  "SYSTEM_NOC", /* HWIO base name */
  false, /* remote node? */ 
  0, /* base address */
  0x5E080, /* HWIO region size */
  ICB_BUS_NOC, /* Bus type */
  0, /* Address width */
  16, /* Data width */
  (void *)&sys_noc_hal_info, /* Bus info structure */
  1,    /* Config clock info */
  bus_sys_noc_clk_names,
  bus_sys_noc_clk_clients,
  0,    /* No enable/disable config clocks. */
  NULL,
  NULL,
  {
    ICB_AGG_SCHEME_LEGACY,
    0,
    0,
  },
};

/**** Bus: sys_noc_anoc ****/
static HAL_noc_QosMasterInfoType sys_noc_anoc_master_info[12] =
{
  {NOC_QOS_ALLOWED_MODE_BYPASS | NOC_QOS_ALLOWED_MODE_FIXED | NOC_QOS_ALLOWED_MODE_LIMITER | NOC_QOS_ALLOWED_MODE_REGULATOR}, /* qhm_qup0 */
  {0}, /* unused port 1 */
  {0}, /* unused port 2 */
  {NOC_QOS_ALLOWED_MODE_BYPASS | NOC_QOS_ALLOWED_MODE_FIXED | NOC_QOS_ALLOWED_MODE_LIMITER | NOC_QOS_ALLOWED_MODE_REGULATOR}, /* qxm_ipa */
  {0}, /* unused port 4 */
  {0}, /* unused port 5 */
  {0}, /* unused port 6 */
  {0}, /* unused port 7 */
  {0}, /* unused port 8 */
  {0}, /* unused port 9 */
  {0}, /* unused port 10 */
  {NOC_QOS_ALLOWED_MODE_BYPASS | NOC_QOS_ALLOWED_MODE_FIXED | NOC_QOS_ALLOWED_MODE_LIMITER | NOC_QOS_ALLOWED_MODE_REGULATOR}, /* qxm_wcss */
};

static HAL_noc_InfoType sys_noc_anoc_hal_info =
{
  0,        /* Base address */
  3,     /* Number of masters */
  12, /* Number of masters with QoS */ 
  1,      /* Number of slaves */ 
  19200,         /* QoS frequency */ 
  sys_noc_anoc_master_info, /* QoS master info */
  false, /* Save/Restore unused here. */
  NULL,
  0,
  NULL,
  NOC_QOS_OFFSET_LEGACY, /* NOC layout type */
  0x15000, /* QoS offset */
  0x1000, /* QoS block size */
  NOC_VERSION_QNOC4,  /*NOC version */
};

static const char *bus_sys_noc_anoc_clk_names[2] =
{
  "/clk/snoc",
  "/clk/snoc_periph",
};

static npa_client_handle bus_sys_noc_anoc_clk_clients[2] = {0};

static icb_bus_def_type sys_noc_anoc_bus =
{
  "SYSTEM_NOC", /* HWIO base name */
  false, /* remote node? */ 
  0, /* base address */
  0x5E080, /* HWIO region size */
  ICB_BUS_NOC, /* Bus type */
  0, /* Address width */
  16, /* Data width */
  (void *)&sys_noc_anoc_hal_info, /* Bus info structure */
  2,    /* Config clock info */
  bus_sys_noc_anoc_clk_names,
  bus_sys_noc_anoc_clk_clients,
  0,    /* No enable/disable config clocks. */
  NULL,
  NULL,
  {
    ICB_AGG_SCHEME_LEGACY,
    0,
    0,
  },
};

/****************************************************************************/
/*                              SLAVES                                      */
/****************************************************************************/
/**** Slave: anoc_snoc ****/
/* slave port ids */
static uint32_t cfg_slave_anoc_snoc_ports[1] =
{
  0, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_anoc_snoc =
{
  ICBID_SLAVE_ANOC_SNOC, /* slaveId */
  &sys_noc_anoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_anoc_snoc_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: bimc_snoc ****/
/* slave port ids */
static uint32_t cfg_slave_bimc_snoc_ports[1] =
{
  1, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_bimc_snoc =
{
  ICBID_SLAVE_BIMC_SNOC, /* slaveId */
  &bimc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_bimc_snoc_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: ebi ****/
/* slave port ids */
static uint32_t cfg_slave_ebi_ports[1] =
{
  0, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_ebi =
{
  ICBID_SLAVE_EBI1, /* slaveId */
  &bimc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_ebi_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: qhs_clk_ctl ****/
/* slave port ids */
static uint32_t cfg_slave_qhs_clk_ctl_ports[1] =
{
  8, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_qhs_clk_ctl =
{
  ICBID_SLAVE_CLK_CTL, /* slaveId */
  &config_noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_qhs_clk_ctl_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: qhs_crypto0_cfg ****/
/* slave port ids */
static uint32_t cfg_slave_qhs_crypto0_cfg_ports[1] =
{
  12, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_qhs_crypto0_cfg =
{
  ICBID_SLAVE_CRYPTO_0_CFG, /* slaveId */
  &config_noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_qhs_crypto0_cfg_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: qhs_hwkm ****/
/* slave port ids */
static uint32_t cfg_slave_qhs_hwkm_ports[1] =
{
  20, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_qhs_hwkm =
{
  ICBID_SLAVE_HWKM_CORE, /* slaveId */
  &config_noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_qhs_hwkm_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: qhs_mesg_ram ****/
/* slave port ids */
static uint32_t cfg_slave_qhs_mesg_ram_ports[1] =
{
  26, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_qhs_mesg_ram =
{
  ICBID_SLAVE_MESSAGE_RAM, /* slaveId */
  &config_noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_qhs_mesg_ram_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: qhs_pdm ****/
/* slave port ids */
static uint32_t cfg_slave_qhs_pdm_ports[1] =
{
  28, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_qhs_pdm =
{
  ICBID_SLAVE_PDM, /* slaveId */
  &config_noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_qhs_pdm_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: qhs_pimem_cfg ****/
/* slave port ids */
static uint32_t cfg_slave_qhs_pimem_cfg_ports[1] =
{
  29, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_qhs_pimem_cfg =
{
  ICBID_SLAVE_PIMEM_CFG, /* slaveId */
  &config_noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_qhs_pimem_cfg_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: qhs_pka_wrapper ****/
/* slave port ids */
static uint32_t cfg_slave_qhs_pka_wrapper_ports[1] =
{
  30, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_qhs_pka_wrapper =
{
  ICBID_SLAVE_PKA_CORE, /* slaveId */
  &config_noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_qhs_pka_wrapper_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: qhs_pmic_arb ****/
/* slave port ids */
static uint32_t cfg_slave_qhs_pmic_arb_ports[1] =
{
  31, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_qhs_pmic_arb =
{
  ICBID_SLAVE_PMIC_ARB, /* slaveId */
  &config_noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_qhs_pmic_arb_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: qhs_qup0 ****/
/* slave port ids */
static uint32_t cfg_slave_qhs_qup0_ports[1] =
{
  37, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_qhs_qup0 =
{
  ICBID_SLAVE_QUP_0, /* slaveId */
  &config_noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_qhs_qup0_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: qhs_sdc1 ****/
/* slave port ids */
static uint32_t cfg_slave_qhs_sdc1_ports[1] =
{
  39, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_qhs_sdc1 =
{
  ICBID_SLAVE_SDCC_1, /* slaveId */
  &config_noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_qhs_sdc1_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: qhs_sdc2 ****/
/* slave port ids */
static uint32_t cfg_slave_qhs_sdc2_ports[1] =
{
  40, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_qhs_sdc2 =
{
  ICBID_SLAVE_SDCC_2, /* slaveId */
  &config_noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_qhs_sdc2_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: qhs_tcsr ****/
/* slave port ids */
static uint32_t cfg_slave_qhs_tcsr_ports[1] =
{
  43, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_qhs_tcsr =
{
  ICBID_SLAVE_TCSR, /* slaveId */
  &config_noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_qhs_tcsr_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: qhs_tlmm ****/
/* slave port ids */
static uint32_t cfg_slave_qhs_tlmm_ports[1] =
{
  44, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_qhs_tlmm =
{
  ICBID_SLAVE_TLMM, /* slaveId */
  &config_noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_qhs_tlmm_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: qhs_wcss ****/
/* slave port ids */
static uint32_t cfg_slave_qhs_wcss_ports[1] =
{
  1, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_qhs_wcss =
{
  ICBID_SLAVE_WCSS, /* slaveId */
  &sys_noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_qhs_wcss_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: qup0_core_slave ****/
/* slave port ids */
static uint32_t cfg_slave_qup0_core_slave_ports[1] =
{
  2, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_qup0_core_slave =
{
  ICBID_SLAVE_QUP_CORE_0, /* slaveId */
  &clk_virt_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_qup0_core_slave_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: qxs_imem ****/
/* slave port ids */
static uint32_t cfg_slave_qxs_imem_ports[1] =
{
  6, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_qxs_imem =
{
  ICBID_SLAVE_IMEM, /* slaveId */
  &sys_noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_qxs_imem_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: snoc_bimc ****/
/* slave port ids */
static uint32_t cfg_slave_snoc_bimc_ports[1] =
{
  9, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_snoc_bimc =
{
  ICBID_SLAVE_SNOC_BIMC, /* slaveId */
  &sys_noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_snoc_bimc_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: snoc_cnoc ****/
/* slave port ids */
static uint32_t cfg_slave_snoc_cnoc_ports[1] =
{
  4, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_snoc_cnoc =
{
  ICBID_SLAVE_SNOC_CNOC, /* slaveId */
  &sys_noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_snoc_cnoc_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: srvc_cnoc ****/
/* slave port ids */
static uint32_t cfg_slave_srvc_cnoc_ports[1] =
{
  49, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_srvc_cnoc =
{
  ICBID_SLAVE_SERVICE_CNOC, /* slaveId */
  &config_noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_srvc_cnoc_ports, /* pPortIds */
  false, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/**** Slave: xs_qdss_stm ****/
/* slave port ids */
static uint32_t cfg_slave_xs_qdss_stm_ports[1] =
{
  11, /* port 0 */
};

/* slave definition */
static icb_slave_def_type cfg_slave_xs_qdss_stm =
{
  ICBID_SLAVE_QDSS_STM, /* slaveId */
  &sys_noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_slave_xs_qdss_stm_ports, /* pPortIds */
  true, /* remote node? */
  3, /* Number of slave segments */
  NULL, /* pDefaults */
  1, /* Number of ports for aggregation purposes */
};

/****************************************************************************/
/*                              MASTERS                                     */
/****************************************************************************/
/**** Master: anoc_snoc ****/
/* master port ids */
static uint32_t cfg_master_anoc_snoc_ports[1] =
{
  2, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_anoc_snoc =
{
  ICBID_MASTER_ANOC_SNOC, /* master id */
  &sys_noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_anoc_snoc_ports, /* pPortIds */
  NULL, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: bimc_snoc ****/
/* master port ids */
static uint32_t cfg_master_bimc_snoc_ports[1] =
{
  5, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_bimc_snoc =
{
  ICBID_MASTER_BIMC_SNOC, /* master id */
  &sys_noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_bimc_snoc_ports, /* pPortIds */
  NULL, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: mss_proc ****/
/* master port ids */
static uint32_t cfg_master_mss_proc_ports[1] =
{
  5, /* port 0 */
};

static uint32_t cfg_master_mss_proc_qos_ports[1] =
{
  5, /* port 0 */
};

/* master port default settings */
static icb_bimc_master_defaults_type cfg_master_mss_proc_defaults =
{
  /* BIMC ClockGate */
  {
    true, /* Core clock gating */ 
    true,  /* Arb clock gating */
    true, /* Port clock gating */
  },
  /* BIMC Request Type */
  ICB_BW_REQ_TYPE_DEFAULT,
  /* BIMC Mode */
  {BIMC_QOS_MODE_FIXED},
  /* BIMC Priority */
  {
    /* Fixed priority */
    {
      7,    /* PriorityLvl */ 
      7,  /* AReqPriorityRead  */ 
      7, /* AReqPriorityWrite */ 
    },
  },
  /* BIMC Threshold */
  0, /* No threshold. */
};

/* master definition */
static icb_master_def_type cfg_master_mss_proc =
{
  ICBID_MASTER_MSS_PROC, /* master id */
  &bimc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_mss_proc_ports, /* pPortIds */
  cfg_master_mss_proc_qos_ports, /* pQosPortIds */
  false, /* remote node? */ 
  10000, /* default window size */
  &cfg_master_mss_proc_defaults, /* pDefaults */
  NULL, /* pHaltPorts */
  true, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: qhm_qup0 ****/
/* master port ids */
static uint32_t cfg_master_qhm_qup0_ports[1] =
{
  2, /* port 0 */
};

static uint32_t cfg_master_qhm_qup0_qos_ports[1] =
{
  0, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_qhm_qup0 =
{
  ICBID_MASTER_QUP_0, /* master id */
  &sys_noc_anoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_qhm_qup0_ports, /* pPortIds */
  cfg_master_qhm_qup0_qos_ports, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: qup0_core_master ****/
/* master port ids */
static uint32_t cfg_master_qup0_core_master_ports[1] =
{
  2, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_qup0_core_master =
{
  ICBID_MASTER_QUP_CORE_0, /* master id */
  &clk_virt_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_qup0_core_master_ports, /* pPortIds */
  NULL, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: qxm_ipa ****/
/* master port ids */
static uint32_t cfg_master_qxm_ipa_ports[1] =
{
  4, /* port 0 */
};

static uint32_t cfg_master_qxm_ipa_qos_ports[1] =
{
  3, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_qxm_ipa =
{
  ICBID_MASTER_IPA, /* master id */
  &sys_noc_anoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_qxm_ipa_ports, /* pPortIds */
  cfg_master_qxm_ipa_qos_ports, /* pQosPortIds */
  true, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: qxm_mss ****/
/* master port ids */
static uint32_t cfg_master_qxm_mss_ports[1] =
{
  7, /* port 0 */
};

static uint32_t cfg_master_qxm_mss_qos_ports[1] =
{
  6, /* port 0 */
};

/* master port default settings */
static icb_qnoc4_master_defaults_type cfg_master_qxm_mss_defaults =
{
  5, /**< default_priority */
  /**< limiter */
  {
    0, /**< bandwidth */
    0, /**< saturation */
  },
  false, /**< limiter_enabled */
  /**< regulator */
  {
    0, /**< low priority */
    0, /**< high priority */
    0, /**< bandwidth */
    0, /**< saturation */
  },
  /**< regulator_mode */
  {
    false, /**< read enable */
    false, /**< write enable */
  },
  false, /**< urgency_forwarding_enabled */
};

/* master definition */
static icb_master_def_type cfg_master_qxm_mss =
{
  ICBID_MASTER_MSS, /* master id */
  &sys_noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_qxm_mss_ports, /* pPortIds */
  cfg_master_qxm_mss_qos_ports, /* pQosPortIds */
  false, /* remote node? */ 
  0, /* default window size */
  &cfg_master_qxm_mss_defaults, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: qxm_mss_ce ****/
/* master port ids */
static uint32_t cfg_master_qxm_mss_ce_ports[1] =
{
  8, /* port 0 */
};

static uint32_t cfg_master_qxm_mss_ce_qos_ports[1] =
{
  21, /* port 0 */
};

/* master port default settings */
static icb_qnoc4_master_defaults_type cfg_master_qxm_mss_ce_defaults =
{
  2, /**< default_priority */
  /**< limiter */
  {
    0, /**< bandwidth */
    0, /**< saturation */
  },
  false, /**< limiter_enabled */
  /**< regulator */
  {
    0, /**< low priority */
    0, /**< high priority */
    0, /**< bandwidth */
    0, /**< saturation */
  },
  /**< regulator_mode */
  {
    false, /**< read enable */
    false, /**< write enable */
  },
  false, /**< urgency_forwarding_enabled */
};

/* master definition */
static icb_master_def_type cfg_master_qxm_mss_ce =
{
  ICBID_MASTER_MSS_CE, /* master id */
  &sys_noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_qxm_mss_ce_ports, /* pPortIds */
  cfg_master_qxm_mss_ce_qos_ports, /* pQosPortIds */
  false, /* remote node? */ 
  0, /* default window size */
  &cfg_master_qxm_mss_ce_defaults, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: qxm_mss_nav ****/
/* master port ids */
static uint32_t cfg_master_qxm_mss_nav_ports[1] =
{
  9, /* port 0 */
};

static uint32_t cfg_master_qxm_mss_nav_qos_ports[1] =
{
  7, /* port 0 */
};

/* master port default settings */
static icb_qnoc4_master_defaults_type cfg_master_qxm_mss_nav_defaults =
{
  4, /**< default_priority */
  /**< limiter */
  {
    0, /**< bandwidth */
    0, /**< saturation */
  },
  false, /**< limiter_enabled */
  /**< regulator */
  {
    0, /**< low priority */
    0, /**< high priority */
    0, /**< bandwidth */
    0, /**< saturation */
  },
  /**< regulator_mode */
  {
    false, /**< read enable */
    false, /**< write enable */
  },
  false, /**< urgency_forwarding_enabled */
};

/* master definition */
static icb_master_def_type cfg_master_qxm_mss_nav =
{
  ICBID_MASTER_MSS_NAV, /* master id */
  &sys_noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_qxm_mss_nav_ports, /* pPortIds */
  cfg_master_qxm_mss_nav_qos_ports, /* pQosPortIds */
  false, /* remote node? */ 
  0, /* default window size */
  &cfg_master_qxm_mss_nav_defaults, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: qxm_wcss ****/
/* master port ids */
static uint32_t cfg_master_qxm_wcss_ports[1] =
{
  6, /* port 0 */
};

static uint32_t cfg_master_qxm_wcss_qos_ports[1] =
{
  11, /* port 0 */
};

/* master port default settings */
static icb_qnoc4_master_defaults_type cfg_master_qxm_wcss_defaults =
{
  3, /**< default_priority */
  /**< limiter */
  {
    0, /**< bandwidth */
    0, /**< saturation */
  },
  false, /**< limiter_enabled */
  /**< regulator */
  {
    0, /**< low priority */
    0, /**< high priority */
    0, /**< bandwidth */
    0, /**< saturation */
  },
  /**< regulator_mode */
  {
    false, /**< read enable */
    false, /**< write enable */
  },
  false, /**< urgency_forwarding_enabled */
};

/* master definition */
static icb_master_def_type cfg_master_qxm_wcss =
{
  ICBID_MASTER_WCSS, /* master id */
  &sys_noc_anoc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_qxm_wcss_ports, /* pPortIds */
  cfg_master_qxm_wcss_qos_ports, /* pQosPortIds */
  false, /* remote node? */ 
  0, /* default window size */
  &cfg_master_qxm_wcss_defaults, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: snoc_bimc ****/
/* master port ids */
static uint32_t cfg_master_snoc_bimc_ports[1] =
{
  6, /* port 0 */
};

static uint32_t cfg_master_snoc_bimc_qos_ports[1] =
{
  6, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_snoc_bimc =
{
  ICBID_MASTER_SNOC_BIMC, /* master id */
  &bimc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_snoc_bimc_ports, /* pPortIds */
  cfg_master_snoc_bimc_qos_ports, /* pQosPortIds */
  true, /* remote node? */ 
  10000, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/**** Master: snoc_cnoc ****/
/* master port ids */
static uint32_t cfg_master_snoc_cnoc_ports[1] =
{
  2, /* port 0 */
};

/* master definition */
static icb_master_def_type cfg_master_snoc_cnoc =
{
  ICBID_MASTER_SNOC_CNOC, /* master id */
  &config_noc_bus, /* pBus */
  1, /* Number of ports */
  cfg_master_snoc_cnoc_ports, /* pPortIds */
  NULL, /* pQosPortIds */
  false, /* remote node? */ 
  0, /* default window size */
  NULL, /* pDefaults */
  NULL, /* pHaltPorts */
  false, /* Supports latency request? */
  1, /* Number of ports for aggregation purposes */
  {
    ICB_AGG_SCHEME_UNUSED,
    0,
    0,
  },
  NULL,
  NULL,
};

/****************************************************************************/
/*                              LISTS                                       */
/****************************************************************************/
/* List of buses */
const uint32 u32cfg_bus_list_size   = 5;
icb_bus_def_type *cfg_bus_list[5] = 
{
  &bimc_bus,
  &clk_virt_bus,
  &config_noc_bus,
  &sys_noc_bus,
  &sys_noc_anoc_bus,
};

/* List of slaves */
const uint32 u32cfg_slave_list_size   = 23;
icb_slave_def_type *cfg_slave_list[23] = 
{
  &cfg_slave_anoc_snoc,
  &cfg_slave_bimc_snoc,
  &cfg_slave_ebi,
  &cfg_slave_qhs_clk_ctl,
  &cfg_slave_qhs_crypto0_cfg,
  &cfg_slave_qhs_hwkm,
  &cfg_slave_qhs_mesg_ram,
  &cfg_slave_qhs_pdm,
  &cfg_slave_qhs_pimem_cfg,
  &cfg_slave_qhs_pka_wrapper,
  &cfg_slave_qhs_pmic_arb,
  &cfg_slave_qhs_qup0,
  &cfg_slave_qhs_sdc1,
  &cfg_slave_qhs_sdc2,
  &cfg_slave_qhs_tcsr,
  &cfg_slave_qhs_tlmm,
  &cfg_slave_qhs_wcss,
  &cfg_slave_qup0_core_slave,
  &cfg_slave_qxs_imem,
  &cfg_slave_snoc_bimc,
  &cfg_slave_snoc_cnoc,
  &cfg_slave_srvc_cnoc,
  &cfg_slave_xs_qdss_stm,
};

/* List of masters */
const uint32 u32cfg_master_list_size   = 12;
icb_master_def_type *cfg_master_list[12] = 
{
  &cfg_master_anoc_snoc,
  &cfg_master_bimc_snoc,
  &cfg_master_mss_proc,
  &cfg_master_qhm_qup0,
  &cfg_master_qup0_core_master,
  &cfg_master_qxm_ipa,
  &cfg_master_qxm_mss,
  &cfg_master_qxm_mss_ce,
  &cfg_master_qxm_mss_nav,
  &cfg_master_qxm_wcss,
  &cfg_master_snoc_bimc,
  &cfg_master_snoc_cnoc,
};

/* List of configuration clocks */
const uint32 u32ul_cfg_clk_node_list_size   = 5;
const char *ul_cfg_clock_node_list[] =
{
  "/clk/bimc",
  "/clk/cnoc",
  "/clk/qup",
  "/clk/snoc",
  "/clk/snoc_periph",
};

/* TCSR definitions for port halting */
HAL_tcsr_InfoType *cfg_tcsr_info = NULL;

/*============================================================================
                        TOPOLOGY ROUTE DECLARATIONS
============================================================================*/

/*****************************************************/
/*                       bimc                                      */
/*****************************************************/
/* Masters */
/* SNOC_BIMC */
static ul_clock_type master_snoc_bimc_clks[1] =
{
  {
    "/clk/bimc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_snoc_bimc =
{
  /* Master Data */
  "/icb/master/snoc_bimc",
  ICBID_MASTER_SNOC_BIMC,                   /* External Master ID */
  16,
  1,
  master_snoc_bimc_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_snoc_bimc,
    NULL,
  },
  &cfg_master_snoc_bimc,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_snoc_bimc,
    NULL,
  },
};

/* MSS_PROC */
static ul_clock_type master_mss_proc_clks[1] =
{
  {
    "/clk/bimc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_mss_proc =
{
  /* Master Data */
  "/icb/master/mss_proc",
  ICBID_MASTER_MSS_PROC,                    /* External Master ID */
  8,
  1,
  master_mss_proc_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_mss_proc,
    NULL,
  },
  &cfg_master_mss_proc,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_mss_proc,
    NULL,
  },
};

/* Slaves */
/* EBI */
static ul_clock_type slave_ebi_slv_clks[1] =
{
  {
    "/clk/bimc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_ebi =
{
  /* Slave Data */
  "/icb/slave/ebi",
  ICBID_SLAVE_EBI1,                        /* External Slave ID */
  8,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_ebi_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_ebi,
    NULL,
  },
  &cfg_slave_ebi
};

/* BIMC_SNOC */
static ul_clock_type slave_bimc_snoc_slv_clks[1] =
{
  {
    "/clk/bimc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_bimc_snoc =
{
  /* Slave Data */
  "/icb/slave/bimc_snoc",
  ICBID_SLAVE_BIMC_SNOC,                   /* External Slave ID */
  16,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_bimc_snoc_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_bimc_snoc,
    NULL,
  },
  &cfg_slave_bimc_snoc
};

/*****************************************************/
/*                       clk_virt                                      */
/*****************************************************/
/* Masters */
/* QUP0_CORE_MASTER */
static ul_clock_type master_qup0_core_master_clks[1] =
{
  {
    "/clk/qup",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_qup0_core_master =
{
  /* Master Data */
  "/icb/master/qup0_core_master",
  ICBID_MASTER_QUP_CORE_0,                  /* External Master ID */
  4,
  1,
  master_qup0_core_master_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_qup0_core_master,
    NULL,
  },
  &cfg_master_qup0_core_master,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_qup0_core_master,
    NULL,
  },
};

/* Slaves */
/* QUP0_CORE_SLAVE */

static ul_slave_data_type  slave_qup0_core_slave =
{
  /* Slave Data */
  "/icb/slave/qup0_core_slave",
  ICBID_SLAVE_QUP_CORE_0,                  /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  0,
  NULL,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_qup0_core_slave,
    NULL,
  },
  &cfg_slave_qup0_core_slave
};

/*****************************************************/
/*                       config_noc                                      */
/*****************************************************/
/* Masters */
/* SNOC_CNOC */
static ul_clock_type master_snoc_cnoc_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_snoc_cnoc =
{
  /* Master Data */
  "/icb/master/snoc_cnoc",
  ICBID_MASTER_SNOC_CNOC,                   /* External Master ID */
  8,
  1,
  master_snoc_cnoc_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_snoc_cnoc,
    NULL,
  },
  &cfg_master_snoc_cnoc,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_snoc_cnoc,
    NULL,
  },
};

/* Slaves */
/* QHS_CLK_CTL */
static ul_clock_type slave_qhs_clk_ctl_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_qhs_clk_ctl =
{
  /* Slave Data */
  "/icb/slave/qhs_clk_ctl",
  ICBID_SLAVE_CLK_CTL,                     /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_qhs_clk_ctl_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_qhs_clk_ctl,
    NULL,
  },
  &cfg_slave_qhs_clk_ctl
};

/* QHS_CRYPTO0_CFG */
static ul_clock_type slave_qhs_crypto0_cfg_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_qhs_crypto0_cfg =
{
  /* Slave Data */
  "/icb/slave/qhs_crypto0_cfg",
  ICBID_SLAVE_CRYPTO_0_CFG,                /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_qhs_crypto0_cfg_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_qhs_crypto0_cfg,
    NULL,
  },
  &cfg_slave_qhs_crypto0_cfg
};

/* QHS_HWKM */
static ul_clock_type slave_qhs_hwkm_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_qhs_hwkm =
{
  /* Slave Data */
  "/icb/slave/qhs_hwkm",
  ICBID_SLAVE_HWKM_CORE,                   /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_qhs_hwkm_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_qhs_hwkm,
    NULL,
  },
  &cfg_slave_qhs_hwkm
};

/* QHS_MESG_RAM */
static ul_clock_type slave_qhs_mesg_ram_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_qhs_mesg_ram =
{
  /* Slave Data */
  "/icb/slave/qhs_mesg_ram",
  ICBID_SLAVE_MESSAGE_RAM,                 /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_qhs_mesg_ram_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_qhs_mesg_ram,
    NULL,
  },
  &cfg_slave_qhs_mesg_ram
};

/* QHS_PDM */
static ul_clock_type slave_qhs_pdm_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_qhs_pdm =
{
  /* Slave Data */
  "/icb/slave/qhs_pdm",
  ICBID_SLAVE_PDM,                         /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_qhs_pdm_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_qhs_pdm,
    NULL,
  },
  &cfg_slave_qhs_pdm
};

/* QHS_PIMEM_CFG */
static ul_clock_type slave_qhs_pimem_cfg_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_qhs_pimem_cfg =
{
  /* Slave Data */
  "/icb/slave/qhs_pimem_cfg",
  ICBID_SLAVE_PIMEM_CFG,                   /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_qhs_pimem_cfg_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_qhs_pimem_cfg,
    NULL,
  },
  &cfg_slave_qhs_pimem_cfg
};

/* QHS_PKA_WRAPPER */
static ul_clock_type slave_qhs_pka_wrapper_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_qhs_pka_wrapper =
{
  /* Slave Data */
  "/icb/slave/qhs_pka_wrapper",
  ICBID_SLAVE_PKA_CORE,                    /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_qhs_pka_wrapper_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_qhs_pka_wrapper,
    NULL,
  },
  &cfg_slave_qhs_pka_wrapper
};

/* QHS_PMIC_ARB */
static ul_clock_type slave_qhs_pmic_arb_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_qhs_pmic_arb =
{
  /* Slave Data */
  "/icb/slave/qhs_pmic_arb",
  ICBID_SLAVE_PMIC_ARB,                    /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_qhs_pmic_arb_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_qhs_pmic_arb,
    NULL,
  },
  &cfg_slave_qhs_pmic_arb
};

/* QHS_QUP0 */
static ul_clock_type slave_qhs_qup0_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_qhs_qup0 =
{
  /* Slave Data */
  "/icb/slave/qhs_qup0",
  ICBID_SLAVE_QUP_0,                       /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_qhs_qup0_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_qhs_qup0,
    NULL,
  },
  &cfg_slave_qhs_qup0
};

/* QHS_SDC1 */
static ul_clock_type slave_qhs_sdc1_slv_clks[1] =
{
  {
    "/clk/snoc_periph",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_qhs_sdc1 =
{
  /* Slave Data */
  "/icb/slave/qhs_sdc1",
  ICBID_SLAVE_SDCC_1,                      /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_qhs_sdc1_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_qhs_sdc1,
    NULL,
  },
  &cfg_slave_qhs_sdc1
};

/* QHS_SDC2 */
static ul_clock_type slave_qhs_sdc2_slv_clks[1] =
{
  {
    "/clk/snoc_periph",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_qhs_sdc2 =
{
  /* Slave Data */
  "/icb/slave/qhs_sdc2",
  ICBID_SLAVE_SDCC_2,                      /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_qhs_sdc2_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_qhs_sdc2,
    NULL,
  },
  &cfg_slave_qhs_sdc2
};

/* QHS_TCSR */
static ul_clock_type slave_qhs_tcsr_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_qhs_tcsr =
{
  /* Slave Data */
  "/icb/slave/qhs_tcsr",
  ICBID_SLAVE_TCSR,                        /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_qhs_tcsr_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_qhs_tcsr,
    NULL,
  },
  &cfg_slave_qhs_tcsr
};

/* QHS_TLMM */
static ul_clock_type slave_qhs_tlmm_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_qhs_tlmm =
{
  /* Slave Data */
  "/icb/slave/qhs_tlmm",
  ICBID_SLAVE_TLMM,                        /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_qhs_tlmm_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_qhs_tlmm,
    NULL,
  },
  &cfg_slave_qhs_tlmm
};

/* SRVC_CNOC */
static ul_clock_type slave_srvc_cnoc_slv_clks[1] =
{
  {
    "/clk/cnoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_srvc_cnoc =
{
  /* Slave Data */
  "/icb/slave/srvc_cnoc",
  ICBID_SLAVE_SERVICE_CNOC,                /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_srvc_cnoc_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_srvc_cnoc,
    NULL,
  },
  &cfg_slave_srvc_cnoc
};

/*****************************************************/
/*                       sys_noc                                      */
/*****************************************************/
/* Masters */
/* ANOC_SNOC */
static ul_clock_type master_anoc_snoc_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_anoc_snoc =
{
  /* Master Data */
  "/icb/master/anoc_snoc",
  ICBID_MASTER_ANOC_SNOC,                   /* External Master ID */
  16,
  1,
  master_anoc_snoc_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_anoc_snoc,
    NULL,
  },
  &cfg_master_anoc_snoc,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_anoc_snoc,
    NULL,
  },
};

/* BIMC_SNOC */
static ul_clock_type master_bimc_snoc_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_bimc_snoc =
{
  /* Master Data */
  "/icb/master/bimc_snoc",
  ICBID_MASTER_BIMC_SNOC,                   /* External Master ID */
  8,
  1,
  master_bimc_snoc_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_bimc_snoc,
    NULL,
  },
  &cfg_master_bimc_snoc,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_bimc_snoc,
    NULL,
  },
};

/* QXM_MSS */
static ul_clock_type master_qxm_mss_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_qxm_mss =
{
  /* Master Data */
  "/icb/master/qxm_mss",
  ICBID_MASTER_MSS,                         /* External Master ID */
  8,
  1,
  master_qxm_mss_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_qxm_mss,
    NULL,
  },
  &cfg_master_qxm_mss,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_qxm_mss,
    NULL,
  },
};

/* QXM_MSS_CE */
static ul_clock_type master_qxm_mss_ce_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_qxm_mss_ce =
{
  /* Master Data */
  "/icb/master/qxm_mss_ce",
  ICBID_MASTER_MSS_CE,                      /* External Master ID */
  8,
  1,
  master_qxm_mss_ce_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_qxm_mss_ce,
    NULL,
  },
  &cfg_master_qxm_mss_ce,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_qxm_mss_ce,
    NULL,
  },
};

/* QXM_MSS_NAV */
static ul_clock_type master_qxm_mss_nav_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_qxm_mss_nav =
{
  /* Master Data */
  "/icb/master/qxm_mss_nav",
  ICBID_MASTER_MSS_NAV,                     /* External Master ID */
  8,
  1,
  master_qxm_mss_nav_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_qxm_mss_nav,
    NULL,
  },
  &cfg_master_qxm_mss_nav,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_qxm_mss_nav,
    NULL,
  },
};

/* Slaves */
/* QHS_WCSS */
static ul_clock_type slave_qhs_wcss_slv_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_qhs_wcss =
{
  /* Slave Data */
  "/icb/slave/qhs_wcss",
  ICBID_SLAVE_WCSS,                        /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_qhs_wcss_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_qhs_wcss,
    NULL,
  },
  &cfg_slave_qhs_wcss
};

/* SNOC_CNOC */
static ul_clock_type slave_snoc_cnoc_slv_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_snoc_cnoc =
{
  /* Slave Data */
  "/icb/slave/snoc_cnoc",
  ICBID_SLAVE_SNOC_CNOC,                   /* External Slave ID */
  8,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_snoc_cnoc_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_snoc_cnoc,
    NULL,
  },
  &cfg_slave_snoc_cnoc
};

/* QXS_IMEM */
static ul_clock_type slave_qxs_imem_slv_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_qxs_imem =
{
  /* Slave Data */
  "/icb/slave/qxs_imem",
  ICBID_SLAVE_IMEM,                        /* External Slave ID */
  8,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_qxs_imem_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_qxs_imem,
    NULL,
  },
  &cfg_slave_qxs_imem
};

/* SNOC_BIMC */
static ul_clock_type slave_snoc_bimc_slv_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_snoc_bimc =
{
  /* Slave Data */
  "/icb/slave/snoc_bimc",
  ICBID_SLAVE_SNOC_BIMC,                   /* External Slave ID */
  16,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_snoc_bimc_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_snoc_bimc,
    NULL,
  },
  &cfg_slave_snoc_bimc
};

/* XS_QDSS_STM */
static ul_clock_type slave_xs_qdss_stm_slv_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_xs_qdss_stm =
{
  /* Slave Data */
  "/icb/slave/xs_qdss_stm",
  ICBID_SLAVE_QDSS_STM,                    /* External Slave ID */
  4,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_xs_qdss_stm_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_xs_qdss_stm,
    NULL,
  },
  &cfg_slave_xs_qdss_stm
};

/*****************************************************/
/*                       sys_noc_anoc                                      */
/*****************************************************/
/* Masters */
/* QHM_QUP0 */
static ul_clock_type master_qhm_qup0_clks[1] =
{
  {
    "/clk/snoc_periph",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_qhm_qup0 =
{
  /* Master Data */
  "/icb/master/qhm_qup0",
  ICBID_MASTER_QUP_0,                       /* External Master ID */
  4,
  1,
  master_qhm_qup0_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_qhm_qup0,
    NULL,
  },
  &cfg_master_qhm_qup0,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_qhm_qup0,
    NULL,
  },
};

/* QXM_IPA */
static ul_clock_type master_qxm_ipa_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_qxm_ipa =
{
  /* Master Data */
  "/icb/master/qxm_ipa",
  ICBID_MASTER_IPA,                         /* External Master ID */
  8,
  1,
  master_qxm_ipa_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_qxm_ipa,
    NULL,
  },
  &cfg_master_qxm_ipa,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_qxm_ipa,
    NULL,
  },
};

/* QXM_WCSS */
static ul_clock_type master_qxm_wcss_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};

static ul_master_data_type  master_qxm_wcss =
{
  /* Master Data */
  "/icb/master/qxm_wcss",
  ICBID_MASTER_WCSS,                        /* External Master ID */
  8,
  1,
  master_qxm_wcss_clks,
  {
    0                                      /* Ab value */
  },
  {
    NULL,
    NULL,
    0,
    &master_qxm_wcss,
    NULL,
  },
  &cfg_master_qxm_wcss,
  {
    0,
    0,
    NULL,
  },
  {
    NULL,
    NULL,
    0,
    &master_qxm_wcss,
    NULL,
  },
};

/* Slaves */
/* ANOC_SNOC */
static ul_clock_type slave_anoc_snoc_slv_clks[1] =
{
  {
    "/clk/snoc",
    NULL,
    NULL,
  },
};


static ul_slave_data_type  slave_anoc_snoc =
{
  /* Slave Data */
  "/icb/slave/anoc_snoc",
  ICBID_SLAVE_ANOC_SNOC,                   /* External Slave ID */
  16,
  {
    0,                                       /* Current Ib value */
    0,                                       /* Current Ib value */
    0,                                       /* Current Ab value */
  },
  1,
  slave_anoc_snoc_slv_clks,
  0,
  NULL,
  {
    0,
    0,
    NULL
  },
  {
    NULL,
    NULL,
    0,
    &slave_anoc_snoc,
    NULL,
  },
  &cfg_slave_anoc_snoc
};

/* Define the valid routes  */
static ul_pair_type route_mss_proc_ebi_list_array[1] =
{
  {
    &master_mss_proc,
    &slave_ebi
  },
};
static ul_route_list_type route_mss_proc_ebi_list =
{
  1,
  route_mss_proc_ebi_list_array
};
static ul_pair_type route_mss_proc_qhs_clk_ctl_list_array[3] =
{
  {
    &master_mss_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_qhs_clk_ctl
  },
};
static ul_route_list_type route_mss_proc_qhs_clk_ctl_list =
{
  3,
  route_mss_proc_qhs_clk_ctl_list_array
};
static ul_pair_type route_mss_proc_qhs_crypto0_cfg_list_array[3] =
{
  {
    &master_mss_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_qhs_crypto0_cfg
  },
};
static ul_route_list_type route_mss_proc_qhs_crypto0_cfg_list =
{
  3,
  route_mss_proc_qhs_crypto0_cfg_list_array
};
static ul_pair_type route_mss_proc_qhs_hwkm_list_array[3] =
{
  {
    &master_mss_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_qhs_hwkm
  },
};
static ul_route_list_type route_mss_proc_qhs_hwkm_list =
{
  3,
  route_mss_proc_qhs_hwkm_list_array
};
static ul_pair_type route_mss_proc_qhs_mesg_ram_list_array[3] =
{
  {
    &master_mss_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_qhs_mesg_ram
  },
};
static ul_route_list_type route_mss_proc_qhs_mesg_ram_list =
{
  3,
  route_mss_proc_qhs_mesg_ram_list_array
};
static ul_pair_type route_mss_proc_qhs_pdm_list_array[3] =
{
  {
    &master_mss_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_qhs_pdm
  },
};
static ul_route_list_type route_mss_proc_qhs_pdm_list =
{
  3,
  route_mss_proc_qhs_pdm_list_array
};
static ul_pair_type route_mss_proc_qhs_pimem_cfg_list_array[3] =
{
  {
    &master_mss_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_qhs_pimem_cfg
  },
};
static ul_route_list_type route_mss_proc_qhs_pimem_cfg_list =
{
  3,
  route_mss_proc_qhs_pimem_cfg_list_array
};
static ul_pair_type route_mss_proc_qhs_pka_wrapper_list_array[3] =
{
  {
    &master_mss_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_qhs_pka_wrapper
  },
};
static ul_route_list_type route_mss_proc_qhs_pka_wrapper_list =
{
  3,
  route_mss_proc_qhs_pka_wrapper_list_array
};
static ul_pair_type route_mss_proc_qhs_pmic_arb_list_array[3] =
{
  {
    &master_mss_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_qhs_pmic_arb
  },
};
static ul_route_list_type route_mss_proc_qhs_pmic_arb_list =
{
  3,
  route_mss_proc_qhs_pmic_arb_list_array
};
static ul_pair_type route_mss_proc_qhs_qup0_list_array[3] =
{
  {
    &master_mss_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_qhs_qup0
  },
};
static ul_route_list_type route_mss_proc_qhs_qup0_list =
{
  3,
  route_mss_proc_qhs_qup0_list_array
};
static ul_pair_type route_mss_proc_qhs_sdc1_list_array[3] =
{
  {
    &master_mss_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_qhs_sdc1
  },
};
static ul_route_list_type route_mss_proc_qhs_sdc1_list =
{
  3,
  route_mss_proc_qhs_sdc1_list_array
};
static ul_pair_type route_mss_proc_qhs_sdc2_list_array[3] =
{
  {
    &master_mss_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_qhs_sdc2
  },
};
static ul_route_list_type route_mss_proc_qhs_sdc2_list =
{
  3,
  route_mss_proc_qhs_sdc2_list_array
};
static ul_pair_type route_mss_proc_qhs_tcsr_list_array[3] =
{
  {
    &master_mss_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_qhs_tcsr
  },
};
static ul_route_list_type route_mss_proc_qhs_tcsr_list =
{
  3,
  route_mss_proc_qhs_tcsr_list_array
};
static ul_pair_type route_mss_proc_qhs_tlmm_list_array[3] =
{
  {
    &master_mss_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_qhs_tlmm
  },
};
static ul_route_list_type route_mss_proc_qhs_tlmm_list =
{
  3,
  route_mss_proc_qhs_tlmm_list_array
};
static ul_pair_type route_mss_proc_qhs_wcss_list_array[2] =
{
  {
    &master_mss_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_qhs_wcss
  },
};
static ul_route_list_type route_mss_proc_qhs_wcss_list =
{
  2,
  route_mss_proc_qhs_wcss_list_array
};
static ul_pair_type route_mss_proc_qxs_imem_list_array[2] =
{
  {
    &master_mss_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_qxs_imem
  },
};
static ul_route_list_type route_mss_proc_qxs_imem_list =
{
  2,
  route_mss_proc_qxs_imem_list_array
};
static ul_pair_type route_mss_proc_srvc_cnoc_list_array[3] =
{
  {
    &master_mss_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_srvc_cnoc
  },
};
static ul_route_list_type route_mss_proc_srvc_cnoc_list =
{
  3,
  route_mss_proc_srvc_cnoc_list_array
};
static ul_pair_type route_mss_proc_xs_qdss_stm_list_array[2] =
{
  {
    &master_mss_proc,
    &slave_bimc_snoc
  },
  {
    &master_bimc_snoc,
    &slave_xs_qdss_stm
  },
};
static ul_route_list_type route_mss_proc_xs_qdss_stm_list =
{
  2,
  route_mss_proc_xs_qdss_stm_list_array
};
static ul_pair_type route_qhm_qup0_ebi_list_array[3] =
{
  {
    &master_qhm_qup0,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_snoc_bimc
  },
  {
    &master_snoc_bimc,
    &slave_ebi
  },
};
static ul_route_list_type route_qhm_qup0_ebi_list =
{
  3,
  route_qhm_qup0_ebi_list_array
};
static ul_pair_type route_qhm_qup0_qhs_clk_ctl_list_array[3] =
{
  {
    &master_qhm_qup0,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_qhs_clk_ctl
  },
};
static ul_route_list_type route_qhm_qup0_qhs_clk_ctl_list =
{
  3,
  route_qhm_qup0_qhs_clk_ctl_list_array
};
static ul_pair_type route_qhm_qup0_qhs_crypto0_cfg_list_array[3] =
{
  {
    &master_qhm_qup0,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_qhs_crypto0_cfg
  },
};
static ul_route_list_type route_qhm_qup0_qhs_crypto0_cfg_list =
{
  3,
  route_qhm_qup0_qhs_crypto0_cfg_list_array
};
static ul_pair_type route_qhm_qup0_qhs_hwkm_list_array[3] =
{
  {
    &master_qhm_qup0,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_qhs_hwkm
  },
};
static ul_route_list_type route_qhm_qup0_qhs_hwkm_list =
{
  3,
  route_qhm_qup0_qhs_hwkm_list_array
};
static ul_pair_type route_qhm_qup0_qhs_mesg_ram_list_array[3] =
{
  {
    &master_qhm_qup0,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_qhs_mesg_ram
  },
};
static ul_route_list_type route_qhm_qup0_qhs_mesg_ram_list =
{
  3,
  route_qhm_qup0_qhs_mesg_ram_list_array
};
static ul_pair_type route_qhm_qup0_qhs_pdm_list_array[3] =
{
  {
    &master_qhm_qup0,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_qhs_pdm
  },
};
static ul_route_list_type route_qhm_qup0_qhs_pdm_list =
{
  3,
  route_qhm_qup0_qhs_pdm_list_array
};
static ul_pair_type route_qhm_qup0_qhs_pimem_cfg_list_array[3] =
{
  {
    &master_qhm_qup0,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_qhs_pimem_cfg
  },
};
static ul_route_list_type route_qhm_qup0_qhs_pimem_cfg_list =
{
  3,
  route_qhm_qup0_qhs_pimem_cfg_list_array
};
static ul_pair_type route_qhm_qup0_qhs_pka_wrapper_list_array[3] =
{
  {
    &master_qhm_qup0,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_qhs_pka_wrapper
  },
};
static ul_route_list_type route_qhm_qup0_qhs_pka_wrapper_list =
{
  3,
  route_qhm_qup0_qhs_pka_wrapper_list_array
};
static ul_pair_type route_qhm_qup0_qhs_pmic_arb_list_array[3] =
{
  {
    &master_qhm_qup0,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_qhs_pmic_arb
  },
};
static ul_route_list_type route_qhm_qup0_qhs_pmic_arb_list =
{
  3,
  route_qhm_qup0_qhs_pmic_arb_list_array
};
static ul_pair_type route_qhm_qup0_qhs_qup0_list_array[3] =
{
  {
    &master_qhm_qup0,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_qhs_qup0
  },
};
static ul_route_list_type route_qhm_qup0_qhs_qup0_list =
{
  3,
  route_qhm_qup0_qhs_qup0_list_array
};
static ul_pair_type route_qhm_qup0_qhs_sdc1_list_array[3] =
{
  {
    &master_qhm_qup0,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_qhs_sdc1
  },
};
static ul_route_list_type route_qhm_qup0_qhs_sdc1_list =
{
  3,
  route_qhm_qup0_qhs_sdc1_list_array
};
static ul_pair_type route_qhm_qup0_qhs_sdc2_list_array[3] =
{
  {
    &master_qhm_qup0,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_qhs_sdc2
  },
};
static ul_route_list_type route_qhm_qup0_qhs_sdc2_list =
{
  3,
  route_qhm_qup0_qhs_sdc2_list_array
};
static ul_pair_type route_qhm_qup0_qhs_tcsr_list_array[3] =
{
  {
    &master_qhm_qup0,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_qhs_tcsr
  },
};
static ul_route_list_type route_qhm_qup0_qhs_tcsr_list =
{
  3,
  route_qhm_qup0_qhs_tcsr_list_array
};
static ul_pair_type route_qhm_qup0_qhs_tlmm_list_array[3] =
{
  {
    &master_qhm_qup0,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_qhs_tlmm
  },
};
static ul_route_list_type route_qhm_qup0_qhs_tlmm_list =
{
  3,
  route_qhm_qup0_qhs_tlmm_list_array
};
static ul_pair_type route_qhm_qup0_qhs_wcss_list_array[2] =
{
  {
    &master_qhm_qup0,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_qhs_wcss
  },
};
static ul_route_list_type route_qhm_qup0_qhs_wcss_list =
{
  2,
  route_qhm_qup0_qhs_wcss_list_array
};
static ul_pair_type route_qhm_qup0_qxs_imem_list_array[2] =
{
  {
    &master_qhm_qup0,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_qxs_imem
  },
};
static ul_route_list_type route_qhm_qup0_qxs_imem_list =
{
  2,
  route_qhm_qup0_qxs_imem_list_array
};
static ul_pair_type route_qhm_qup0_snoc_bimc_list_array[2] =
{
  {
    &master_qhm_qup0,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_snoc_bimc
  },
};
static ul_route_list_type route_qhm_qup0_snoc_bimc_list =
{
  2,
  route_qhm_qup0_snoc_bimc_list_array
};
static ul_pair_type route_qhm_qup0_srvc_cnoc_list_array[3] =
{
  {
    &master_qhm_qup0,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_snoc_cnoc
  },
  {
    &master_snoc_cnoc,
    &slave_srvc_cnoc
  },
};
static ul_route_list_type route_qhm_qup0_srvc_cnoc_list =
{
  3,
  route_qhm_qup0_srvc_cnoc_list_array
};
static ul_pair_type route_qhm_qup0_xs_qdss_stm_list_array[2] =
{
  {
    &master_qhm_qup0,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_xs_qdss_stm
  },
};
static ul_route_list_type route_qhm_qup0_xs_qdss_stm_list =
{
  2,
  route_qhm_qup0_xs_qdss_stm_list_array
};
static ul_pair_type route_qup0_core_master_qup0_core_slave_list_array[1] =
{
  {
    &master_qup0_core_master,
    &slave_qup0_core_slave
  },
};
static ul_route_list_type route_qup0_core_master_qup0_core_slave_list =
{
  1,
  route_qup0_core_master_qup0_core_slave_list_array
};
static ul_pair_type route_qxm_ipa_ebi_list_array[3] =
{
  {
    &master_qxm_ipa,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_snoc_bimc
  },
  {
    &master_snoc_bimc,
    &slave_ebi
  },
};
static ul_route_list_type route_qxm_ipa_ebi_list =
{
  3,
  route_qxm_ipa_ebi_list_array
};
static ul_pair_type route_qxm_ipa_qhs_wcss_list_array[2] =
{
  {
    &master_qxm_ipa,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_qhs_wcss
  },
};
static ul_route_list_type route_qxm_ipa_qhs_wcss_list =
{
  2,
  route_qxm_ipa_qhs_wcss_list_array
};
static ul_pair_type route_qxm_ipa_qxs_imem_list_array[2] =
{
  {
    &master_qxm_ipa,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_qxs_imem
  },
};
static ul_route_list_type route_qxm_ipa_qxs_imem_list =
{
  2,
  route_qxm_ipa_qxs_imem_list_array
};
static ul_pair_type route_qxm_ipa_snoc_bimc_list_array[2] =
{
  {
    &master_qxm_ipa,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_snoc_bimc
  },
};
static ul_route_list_type route_qxm_ipa_snoc_bimc_list =
{
  2,
  route_qxm_ipa_snoc_bimc_list_array
};
static ul_pair_type route_qxm_ipa_xs_qdss_stm_list_array[2] =
{
  {
    &master_qxm_ipa,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_xs_qdss_stm
  },
};
static ul_route_list_type route_qxm_ipa_xs_qdss_stm_list =
{
  2,
  route_qxm_ipa_xs_qdss_stm_list_array
};
static ul_pair_type route_qxm_mss_ce_ebi_list_array[2] =
{
  {
    &master_qxm_mss_ce,
    &slave_snoc_bimc
  },
  {
    &master_snoc_bimc,
    &slave_ebi
  },
};
static ul_route_list_type route_qxm_mss_ce_ebi_list =
{
  2,
  route_qxm_mss_ce_ebi_list_array
};
static ul_pair_type route_qxm_mss_ce_qxs_imem_list_array[1] =
{
  {
    &master_qxm_mss_ce,
    &slave_qxs_imem
  },
};
static ul_route_list_type route_qxm_mss_ce_qxs_imem_list =
{
  1,
  route_qxm_mss_ce_qxs_imem_list_array
};
static ul_pair_type route_qxm_mss_ce_snoc_bimc_list_array[1] =
{
  {
    &master_qxm_mss_ce,
    &slave_snoc_bimc
  },
};
static ul_route_list_type route_qxm_mss_ce_snoc_bimc_list =
{
  1,
  route_qxm_mss_ce_snoc_bimc_list_array
};
static ul_pair_type route_qxm_mss_nav_ebi_list_array[2] =
{
  {
    &master_qxm_mss_nav,
    &slave_snoc_bimc
  },
  {
    &master_snoc_bimc,
    &slave_ebi
  },
};
static ul_route_list_type route_qxm_mss_nav_ebi_list =
{
  2,
  route_qxm_mss_nav_ebi_list_array
};
static ul_pair_type route_qxm_mss_nav_qxs_imem_list_array[1] =
{
  {
    &master_qxm_mss_nav,
    &slave_qxs_imem
  },
};
static ul_route_list_type route_qxm_mss_nav_qxs_imem_list =
{
  1,
  route_qxm_mss_nav_qxs_imem_list_array
};
static ul_pair_type route_qxm_mss_nav_snoc_bimc_list_array[1] =
{
  {
    &master_qxm_mss_nav,
    &slave_snoc_bimc
  },
};
static ul_route_list_type route_qxm_mss_nav_snoc_bimc_list =
{
  1,
  route_qxm_mss_nav_snoc_bimc_list_array
};
static ul_pair_type route_qxm_mss_ebi_list_array[2] =
{
  {
    &master_qxm_mss,
    &slave_snoc_bimc
  },
  {
    &master_snoc_bimc,
    &slave_ebi
  },
};
static ul_route_list_type route_qxm_mss_ebi_list =
{
  2,
  route_qxm_mss_ebi_list_array
};
static ul_pair_type route_qxm_mss_qxs_imem_list_array[1] =
{
  {
    &master_qxm_mss,
    &slave_qxs_imem
  },
};
static ul_route_list_type route_qxm_mss_qxs_imem_list =
{
  1,
  route_qxm_mss_qxs_imem_list_array
};
static ul_pair_type route_qxm_mss_snoc_bimc_list_array[1] =
{
  {
    &master_qxm_mss,
    &slave_snoc_bimc
  },
};
static ul_route_list_type route_qxm_mss_snoc_bimc_list =
{
  1,
  route_qxm_mss_snoc_bimc_list_array
};
static ul_pair_type route_qxm_mss_xs_qdss_stm_list_array[1] =
{
  {
    &master_qxm_mss,
    &slave_xs_qdss_stm
  },
};
static ul_route_list_type route_qxm_mss_xs_qdss_stm_list =
{
  1,
  route_qxm_mss_xs_qdss_stm_list_array
};
static ul_pair_type route_qxm_wcss_ebi_list_array[3] =
{
  {
    &master_qxm_wcss,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_snoc_bimc
  },
  {
    &master_snoc_bimc,
    &slave_ebi
  },
};
static ul_route_list_type route_qxm_wcss_ebi_list =
{
  3,
  route_qxm_wcss_ebi_list_array
};
static ul_pair_type route_qxm_wcss_qhs_wcss_list_array[2] =
{
  {
    &master_qxm_wcss,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_qhs_wcss
  },
};
static ul_route_list_type route_qxm_wcss_qhs_wcss_list =
{
  2,
  route_qxm_wcss_qhs_wcss_list_array
};
static ul_pair_type route_qxm_wcss_qxs_imem_list_array[2] =
{
  {
    &master_qxm_wcss,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_qxs_imem
  },
};
static ul_route_list_type route_qxm_wcss_qxs_imem_list =
{
  2,
  route_qxm_wcss_qxs_imem_list_array
};
static ul_pair_type route_qxm_wcss_snoc_bimc_list_array[2] =
{
  {
    &master_qxm_wcss,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_snoc_bimc
  },
};
static ul_route_list_type route_qxm_wcss_snoc_bimc_list =
{
  2,
  route_qxm_wcss_snoc_bimc_list_array
};
static ul_pair_type route_qxm_wcss_xs_qdss_stm_list_array[2] =
{
  {
    &master_qxm_wcss,
    &slave_anoc_snoc
  },
  {
    &master_anoc_snoc,
    &slave_xs_qdss_stm
  },
};
static ul_route_list_type route_qxm_wcss_xs_qdss_stm_list =
{
  2,
  route_qxm_wcss_xs_qdss_stm_list_array
};
static ul_pair_type route_snoc_bimc_ebi_list_array[1] =
{
  {
    &master_snoc_bimc,
    &slave_ebi
  },
};
static ul_route_list_type route_snoc_bimc_ebi_list =
{
  1,
  route_snoc_bimc_ebi_list_array
};

/*============================================================================
                         ROUTE TREE - 59 routes
============================================================================*/
/* Forward declarations */
static ul_treeNodeType route_0x100000000L_mss_proc_ebi_node;
static ul_treeNodeType route_0x100000017L_mss_proc_qhs_wcss_node;
static ul_treeNodeType route_0x10000001aL_mss_proc_qxs_imem_node;
static ul_treeNodeType route_0x10000001eL_mss_proc_xs_qdss_stm_node;
static ul_treeNodeType route_0x10000001fL_mss_proc_qhs_sdc1_node;
static ul_treeNodeType route_0x100000021L_mss_proc_qhs_sdc2_node;
static ul_treeNodeType route_0x100000029L_mss_proc_qhs_pdm_node;
static ul_treeNodeType route_0x10000002fL_mss_proc_qhs_clk_ctl_node;
static ul_treeNodeType route_0x100000032L_mss_proc_qhs_tcsr_node;
static ul_treeNodeType route_0x100000033L_mss_proc_qhs_tlmm_node;
static ul_treeNodeType route_0x100000034L_mss_proc_qhs_crypto0_cfg_node;
static ul_treeNodeType route_0x100000037L_mss_proc_qhs_mesg_ram_node;
static ul_treeNodeType route_0x10000003bL_mss_proc_qhs_pmic_arb_node;
static ul_treeNodeType route_0x10000004cL_mss_proc_srvc_cnoc_node;
static ul_treeNodeType route_0x1000000a7L_mss_proc_qhs_pimem_cfg_node;
static ul_treeNodeType route_0x100000105L_mss_proc_qhs_qup0_node;
static ul_treeNodeType route_0x100000118L_mss_proc_qhs_hwkm_node;
static ul_treeNodeType route_0x100000119L_mss_proc_qhs_pka_wrapper_node;
static ul_treeNodeType route_0x300000000L_snoc_bimc_ebi_node;
static ul_treeNodeType route_0x1a00000000L_qxm_mss_ebi_node;
static ul_treeNodeType route_0x1a00000018L_qxm_mss_snoc_bimc_node;
static ul_treeNodeType route_0x1a0000001aL_qxm_mss_qxs_imem_node;
static ul_treeNodeType route_0x1a0000001eL_qxm_mss_xs_qdss_stm_node;
static ul_treeNodeType route_0x1b00000000L_qxm_mss_nav_ebi_node;
static ul_treeNodeType route_0x1b00000018L_qxm_mss_nav_snoc_bimc_node;
static ul_treeNodeType route_0x1b0000001aL_qxm_mss_nav_qxs_imem_node;
static ul_treeNodeType route_0x1e00000000L_qxm_wcss_ebi_node;
static ul_treeNodeType route_0x1e00000017L_qxm_wcss_qhs_wcss_node;
static ul_treeNodeType route_0x1e00000018L_qxm_wcss_snoc_bimc_node;
static ul_treeNodeType route_0x1e0000001aL_qxm_wcss_qxs_imem_node;
static ul_treeNodeType route_0x1e0000001eL_qxm_wcss_xs_qdss_stm_node;
static ul_treeNodeType route_0x3b00000000L_qxm_ipa_ebi_node;
static ul_treeNodeType route_0x3b00000017L_qxm_ipa_qhs_wcss_node;
static ul_treeNodeType route_0x3b00000018L_qxm_ipa_snoc_bimc_node;
static ul_treeNodeType route_0x3b0000001aL_qxm_ipa_qxs_imem_node;
static ul_treeNodeType route_0x3b0000001eL_qxm_ipa_xs_qdss_stm_node;
static ul_treeNodeType route_0x9400000000L_qxm_mss_ce_ebi_node;
static ul_treeNodeType route_0x9400000018L_qxm_mss_ce_snoc_bimc_node;
static ul_treeNodeType route_0x940000001aL_qxm_mss_ce_qxs_imem_node;
static ul_treeNodeType route_0xa600000000L_qhm_qup0_ebi_node;
static ul_treeNodeType route_0xa600000017L_qhm_qup0_qhs_wcss_node;
static ul_treeNodeType route_0xa600000018L_qhm_qup0_snoc_bimc_node;
static ul_treeNodeType route_0xa60000001aL_qhm_qup0_qxs_imem_node;
static ul_treeNodeType route_0xa60000001eL_qhm_qup0_xs_qdss_stm_node;
static ul_treeNodeType route_0xa60000001fL_qhm_qup0_qhs_sdc1_node;
static ul_treeNodeType route_0xa600000021L_qhm_qup0_qhs_sdc2_node;
static ul_treeNodeType route_0xa600000029L_qhm_qup0_qhs_pdm_node;
static ul_treeNodeType route_0xa60000002fL_qhm_qup0_qhs_clk_ctl_node;
static ul_treeNodeType route_0xa600000032L_qhm_qup0_qhs_tcsr_node;
static ul_treeNodeType route_0xa600000033L_qhm_qup0_qhs_tlmm_node;
static ul_treeNodeType route_0xa600000034L_qhm_qup0_qhs_crypto0_cfg_node;
static ul_treeNodeType route_0xa600000037L_qhm_qup0_qhs_mesg_ram_node;
static ul_treeNodeType route_0xa60000003bL_qhm_qup0_qhs_pmic_arb_node;
static ul_treeNodeType route_0xa60000004cL_qhm_qup0_srvc_cnoc_node;
static ul_treeNodeType route_0xa6000000a7L_qhm_qup0_qhs_pimem_cfg_node;
static ul_treeNodeType route_0xa600000105L_qhm_qup0_qhs_qup0_node;
static ul_treeNodeType route_0xa600000118L_qhm_qup0_qhs_hwkm_node;
static ul_treeNodeType route_0xa600000119L_qhm_qup0_qhs_pka_wrapper_node;
static ul_treeNodeType route_0xaa00000108L_qup0_core_master_qup0_core_slave_node;

/* Create the tree */
static ul_treeNodeType route_0x100000000L_mss_proc_ebi_node =
{
  0x100000000ULL,                         /* KEY: MASTER_ID:SLAVE_ID */
  &route_mss_proc_ebi_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x100000017L_mss_proc_qhs_wcss_node =
{
  0x100000017ULL,                         /* KEY: MASTER_ID:SLAVE_ID */
  &route_mss_proc_qhs_wcss_list,
  &route_0x100000000L_mss_proc_ebi_node,
  &route_0x10000001aL_mss_proc_qxs_imem_node
};
static ul_treeNodeType route_0x10000001aL_mss_proc_qxs_imem_node =
{
  0x10000001aULL,                         /* KEY: MASTER_ID:SLAVE_ID */
  &route_mss_proc_qxs_imem_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x10000001eL_mss_proc_xs_qdss_stm_node =
{
  0x10000001eULL,                         /* KEY: MASTER_ID:SLAVE_ID */
  &route_mss_proc_xs_qdss_stm_list,
  &route_0x100000017L_mss_proc_qhs_wcss_node,
  &route_0x10000001fL_mss_proc_qhs_sdc1_node
};
static ul_treeNodeType route_0x10000001fL_mss_proc_qhs_sdc1_node =
{
  0x10000001fULL,                         /* KEY: MASTER_ID:SLAVE_ID */
  &route_mss_proc_qhs_sdc1_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x100000021L_mss_proc_qhs_sdc2_node =
{
  0x100000021ULL,                         /* KEY: MASTER_ID:SLAVE_ID */
  &route_mss_proc_qhs_sdc2_list,
  &route_0x10000001eL_mss_proc_xs_qdss_stm_node,
  &route_0x100000037L_mss_proc_qhs_mesg_ram_node
};
static ul_treeNodeType route_0x100000029L_mss_proc_qhs_pdm_node =
{
  0x100000029ULL,                         /* KEY: MASTER_ID:SLAVE_ID */
  &route_mss_proc_qhs_pdm_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x10000002fL_mss_proc_qhs_clk_ctl_node =
{
  0x10000002fULL,                         /* KEY: MASTER_ID:SLAVE_ID */
  &route_mss_proc_qhs_clk_ctl_list,
  &route_0x100000029L_mss_proc_qhs_pdm_node,
  &route_0x100000032L_mss_proc_qhs_tcsr_node
};
static ul_treeNodeType route_0x100000032L_mss_proc_qhs_tcsr_node =
{
  0x100000032ULL,                         /* KEY: MASTER_ID:SLAVE_ID */
  &route_mss_proc_qhs_tcsr_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x100000033L_mss_proc_qhs_tlmm_node =
{
  0x100000033ULL,                         /* KEY: MASTER_ID:SLAVE_ID */
  &route_mss_proc_qhs_tlmm_list,
  &route_0x10000002fL_mss_proc_qhs_clk_ctl_node,
  &route_0x100000034L_mss_proc_qhs_crypto0_cfg_node
};
static ul_treeNodeType route_0x100000034L_mss_proc_qhs_crypto0_cfg_node =
{
  0x100000034ULL,                         /* KEY: MASTER_ID:SLAVE_ID */
  &route_mss_proc_qhs_crypto0_cfg_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x100000037L_mss_proc_qhs_mesg_ram_node =
{
  0x100000037ULL,                         /* KEY: MASTER_ID:SLAVE_ID */
  &route_mss_proc_qhs_mesg_ram_list,
  &route_0x100000033L_mss_proc_qhs_tlmm_node,
  &route_0x100000105L_mss_proc_qhs_qup0_node
};
static ul_treeNodeType route_0x10000003bL_mss_proc_qhs_pmic_arb_node =
{
  0x10000003bULL,                         /* KEY: MASTER_ID:SLAVE_ID */
  &route_mss_proc_qhs_pmic_arb_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x10000004cL_mss_proc_srvc_cnoc_node =
{
  0x10000004cULL,                         /* KEY: MASTER_ID:SLAVE_ID */
  &route_mss_proc_srvc_cnoc_list,
  &route_0x10000003bL_mss_proc_qhs_pmic_arb_node,
  &route_0x1000000a7L_mss_proc_qhs_pimem_cfg_node
};
static ul_treeNodeType route_0x1000000a7L_mss_proc_qhs_pimem_cfg_node =
{
  0x1000000a7ULL,                         /* KEY: MASTER_ID:SLAVE_ID */
  &route_mss_proc_qhs_pimem_cfg_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x100000105L_mss_proc_qhs_qup0_node =
{
  0x100000105ULL,                         /* KEY: MASTER_ID:SLAVE_ID */
  &route_mss_proc_qhs_qup0_list,
  &route_0x10000004cL_mss_proc_srvc_cnoc_node,
  &route_0x100000118L_mss_proc_qhs_hwkm_node
};
static ul_treeNodeType route_0x100000118L_mss_proc_qhs_hwkm_node =
{
  0x100000118ULL,                         /* KEY: MASTER_ID:SLAVE_ID */
  &route_mss_proc_qhs_hwkm_list,
  NULL,
  &route_0x100000119L_mss_proc_qhs_pka_wrapper_node
};
static ul_treeNodeType route_0x100000119L_mss_proc_qhs_pka_wrapper_node =
{
  0x100000119ULL,                         /* KEY: MASTER_ID:SLAVE_ID */
  &route_mss_proc_qhs_pka_wrapper_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x300000000L_snoc_bimc_ebi_node =
{
  0x300000000ULL,                         /* KEY: MASTER_ID:SLAVE_ID */
  &route_snoc_bimc_ebi_list,
  &route_0x100000021L_mss_proc_qhs_sdc2_node,
  &route_0x3b0000001eL_qxm_ipa_xs_qdss_stm_node
};
static ul_treeNodeType route_0x1a00000000L_qxm_mss_ebi_node =
{
  0x1a00000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_mss_ebi_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x1a00000018L_qxm_mss_snoc_bimc_node =
{
  0x1a00000018ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_mss_snoc_bimc_list,
  &route_0x1a00000000L_qxm_mss_ebi_node,
  &route_0x1a0000001eL_qxm_mss_xs_qdss_stm_node
};
static ul_treeNodeType route_0x1a0000001aL_qxm_mss_qxs_imem_node =
{
  0x1a0000001aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_mss_qxs_imem_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x1a0000001eL_qxm_mss_xs_qdss_stm_node =
{
  0x1a0000001eULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_mss_xs_qdss_stm_list,
  &route_0x1a0000001aL_qxm_mss_qxs_imem_node,
  &route_0x1b00000000L_qxm_mss_nav_ebi_node
};
static ul_treeNodeType route_0x1b00000000L_qxm_mss_nav_ebi_node =
{
  0x1b00000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_mss_nav_ebi_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x1b00000018L_qxm_mss_nav_snoc_bimc_node =
{
  0x1b00000018ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_mss_nav_snoc_bimc_list,
  &route_0x1a00000018L_qxm_mss_snoc_bimc_node,
  &route_0x1e00000018L_qxm_wcss_snoc_bimc_node
};
static ul_treeNodeType route_0x1b0000001aL_qxm_mss_nav_qxs_imem_node =
{
  0x1b0000001aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_mss_nav_qxs_imem_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x1e00000000L_qxm_wcss_ebi_node =
{
  0x1e00000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_wcss_ebi_list,
  &route_0x1b0000001aL_qxm_mss_nav_qxs_imem_node,
  &route_0x1e00000017L_qxm_wcss_qhs_wcss_node
};
static ul_treeNodeType route_0x1e00000017L_qxm_wcss_qhs_wcss_node =
{
  0x1e00000017ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_wcss_qhs_wcss_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x1e00000018L_qxm_wcss_snoc_bimc_node =
{
  0x1e00000018ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_wcss_snoc_bimc_list,
  &route_0x1e00000000L_qxm_wcss_ebi_node,
  &route_0x3b00000017L_qxm_ipa_qhs_wcss_node
};
static ul_treeNodeType route_0x1e0000001aL_qxm_wcss_qxs_imem_node =
{
  0x1e0000001aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_wcss_qxs_imem_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x1e0000001eL_qxm_wcss_xs_qdss_stm_node =
{
  0x1e0000001eULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_wcss_xs_qdss_stm_list,
  &route_0x1e0000001aL_qxm_wcss_qxs_imem_node,
  &route_0x3b00000000L_qxm_ipa_ebi_node
};
static ul_treeNodeType route_0x3b00000000L_qxm_ipa_ebi_node =
{
  0x3b00000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_ipa_ebi_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x3b00000017L_qxm_ipa_qhs_wcss_node =
{
  0x3b00000017ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_ipa_qhs_wcss_list,
  &route_0x1e0000001eL_qxm_wcss_xs_qdss_stm_node,
  &route_0x3b00000018L_qxm_ipa_snoc_bimc_node
};
static ul_treeNodeType route_0x3b00000018L_qxm_ipa_snoc_bimc_node =
{
  0x3b00000018ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_ipa_snoc_bimc_list,
  NULL,
  &route_0x3b0000001aL_qxm_ipa_qxs_imem_node
};
static ul_treeNodeType route_0x3b0000001aL_qxm_ipa_qxs_imem_node =
{
  0x3b0000001aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_ipa_qxs_imem_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x3b0000001eL_qxm_ipa_xs_qdss_stm_node =
{
  0x3b0000001eULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_ipa_xs_qdss_stm_list,
  &route_0x1b00000018L_qxm_mss_nav_snoc_bimc_node,
  &route_0xa600000032L_qhm_qup0_qhs_tcsr_node
};
static ul_treeNodeType route_0x9400000000L_qxm_mss_ce_ebi_node =
{
  0x9400000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_mss_ce_ebi_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0x9400000018L_qxm_mss_ce_snoc_bimc_node =
{
  0x9400000018ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_mss_ce_snoc_bimc_list,
  &route_0x9400000000L_qxm_mss_ce_ebi_node,
  &route_0x940000001aL_qxm_mss_ce_qxs_imem_node
};
static ul_treeNodeType route_0x940000001aL_qxm_mss_ce_qxs_imem_node =
{
  0x940000001aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qxm_mss_ce_qxs_imem_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0xa600000000L_qhm_qup0_ebi_node =
{
  0xa600000000ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qhm_qup0_ebi_list,
  &route_0x9400000018L_qxm_mss_ce_snoc_bimc_node,
  &route_0xa600000017L_qhm_qup0_qhs_wcss_node
};
static ul_treeNodeType route_0xa600000017L_qhm_qup0_qhs_wcss_node =
{
  0xa600000017ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qhm_qup0_qhs_wcss_list,
  NULL,
  &route_0xa600000018L_qhm_qup0_snoc_bimc_node
};
static ul_treeNodeType route_0xa600000018L_qhm_qup0_snoc_bimc_node =
{
  0xa600000018ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qhm_qup0_snoc_bimc_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0xa60000001aL_qhm_qup0_qxs_imem_node =
{
  0xa60000001aULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qhm_qup0_qxs_imem_list,
  &route_0xa600000000L_qhm_qup0_ebi_node,
  &route_0xa600000029L_qhm_qup0_qhs_pdm_node
};
static ul_treeNodeType route_0xa60000001eL_qhm_qup0_xs_qdss_stm_node =
{
  0xa60000001eULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qhm_qup0_xs_qdss_stm_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0xa60000001fL_qhm_qup0_qhs_sdc1_node =
{
  0xa60000001fULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qhm_qup0_qhs_sdc1_list,
  &route_0xa60000001eL_qhm_qup0_xs_qdss_stm_node,
  &route_0xa600000021L_qhm_qup0_qhs_sdc2_node
};
static ul_treeNodeType route_0xa600000021L_qhm_qup0_qhs_sdc2_node =
{
  0xa600000021ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qhm_qup0_qhs_sdc2_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0xa600000029L_qhm_qup0_qhs_pdm_node =
{
  0xa600000029ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qhm_qup0_qhs_pdm_list,
  &route_0xa60000001fL_qhm_qup0_qhs_sdc1_node,
  &route_0xa60000002fL_qhm_qup0_qhs_clk_ctl_node
};
static ul_treeNodeType route_0xa60000002fL_qhm_qup0_qhs_clk_ctl_node =
{
  0xa60000002fULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qhm_qup0_qhs_clk_ctl_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0xa600000032L_qhm_qup0_qhs_tcsr_node =
{
  0xa600000032ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qhm_qup0_qhs_tcsr_list,
  &route_0xa60000001aL_qhm_qup0_qxs_imem_node,
  &route_0xa600000105L_qhm_qup0_qhs_qup0_node
};
static ul_treeNodeType route_0xa600000033L_qhm_qup0_qhs_tlmm_node =
{
  0xa600000033ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qhm_qup0_qhs_tlmm_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0xa600000034L_qhm_qup0_qhs_crypto0_cfg_node =
{
  0xa600000034ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qhm_qup0_qhs_crypto0_cfg_list,
  &route_0xa600000033L_qhm_qup0_qhs_tlmm_node,
  &route_0xa600000037L_qhm_qup0_qhs_mesg_ram_node
};
static ul_treeNodeType route_0xa600000037L_qhm_qup0_qhs_mesg_ram_node =
{
  0xa600000037ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qhm_qup0_qhs_mesg_ram_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0xa60000003bL_qhm_qup0_qhs_pmic_arb_node =
{
  0xa60000003bULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qhm_qup0_qhs_pmic_arb_list,
  &route_0xa600000034L_qhm_qup0_qhs_crypto0_cfg_node,
  &route_0xa6000000a7L_qhm_qup0_qhs_pimem_cfg_node
};
static ul_treeNodeType route_0xa60000004cL_qhm_qup0_srvc_cnoc_node =
{
  0xa60000004cULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qhm_qup0_srvc_cnoc_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0xa6000000a7L_qhm_qup0_qhs_pimem_cfg_node =
{
  0xa6000000a7ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qhm_qup0_qhs_pimem_cfg_list,
  &route_0xa60000004cL_qhm_qup0_srvc_cnoc_node,
  NULL
};
static ul_treeNodeType route_0xa600000105L_qhm_qup0_qhs_qup0_node =
{
  0xa600000105ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qhm_qup0_qhs_qup0_list,
  &route_0xa60000003bL_qhm_qup0_qhs_pmic_arb_node,
  &route_0xa600000119L_qhm_qup0_qhs_pka_wrapper_node
};
static ul_treeNodeType route_0xa600000118L_qhm_qup0_qhs_hwkm_node =
{
  0xa600000118ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qhm_qup0_qhs_hwkm_list,
  NULL,
  NULL
};
static ul_treeNodeType route_0xa600000119L_qhm_qup0_qhs_pka_wrapper_node =
{
  0xa600000119ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qhm_qup0_qhs_pka_wrapper_list,
  &route_0xa600000118L_qhm_qup0_qhs_hwkm_node,
  &route_0xaa00000108L_qup0_core_master_qup0_core_slave_node
};
static ul_treeNodeType route_0xaa00000108L_qup0_core_master_qup0_core_slave_node =
{
  0xaa00000108ULL,                        /* KEY: MASTER_ID:SLAVE_ID */
  &route_qup0_core_master_qup0_core_slave_list,
  NULL,
  NULL
};

/*============================================================================
                   EXTERNAL DATA DECLARATIONS
============================================================================*/
/* Pointer to the root node */
ul_treeNodeType * route_tree_root = 
  &route_0x300000000L_snoc_bimc_ebi_node;

const uint32 u32ul_arb_master_list_size   = 12;
ul_master_data_type *ul_arb_master_list[] =
{
  &master_anoc_snoc,
  &master_bimc_snoc,
  &master_mss_proc,
  &master_qhm_qup0,
  &master_qup0_core_master,
  &master_qxm_ipa,
  &master_qxm_mss,
  &master_qxm_mss_ce,
  &master_qxm_mss_nav,
  &master_qxm_wcss,
  &master_snoc_bimc,
  &master_snoc_cnoc,
};

const uint32 u32ul_arb_slave_list_size   = 23;
ul_slave_data_type *ul_arb_slave_list[] =
{
  &slave_anoc_snoc,
  &slave_bimc_snoc,
  &slave_ebi,
  &slave_qhs_clk_ctl,
  &slave_qhs_crypto0_cfg,
  &slave_qhs_hwkm,
  &slave_qhs_mesg_ram,
  &slave_qhs_pdm,
  &slave_qhs_pimem_cfg,
  &slave_qhs_pka_wrapper,
  &slave_qhs_pmic_arb,
  &slave_qhs_qup0,
  &slave_qhs_sdc1,
  &slave_qhs_sdc2,
  &slave_qhs_tcsr,
  &slave_qhs_tlmm,
  &slave_qhs_wcss,
  &slave_qup0_core_slave,
  &slave_qxs_imem,
  &slave_snoc_bimc,
  &slave_snoc_cnoc,
  &slave_srvc_cnoc,
  &slave_xs_qdss_stm,
};

/* Have to make the array size a const so we can export it */
const uint32 u32ul_arb_clk_node_list_size   = 5;
const char *ul_arb_clock_node_list[] =
{
  "/clk/bimc",
  "/clk/cnoc",
  "/clk/qup",
  "/clk/snoc",
  "/clk/snoc_periph",
};

